### ISSUE TITLE
'Unexpected exception in the selector loop' for long-running timers

### ISSUE THREAD

**Issue by zyclonite** [eclipse-vertx/vert.x#2201]
happens only on osx with the following exception
```
[WARN] i.n.c.n.NioEventLoop - Unexpected exception in the selector loop. 
java.io.IOException: Invalid argument
    at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
    at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
    at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
    at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
    at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
    at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
    at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:748)
```

can be reproduced by the following test
vertx 3.5.0, darwin 16.7.0, oracle jdk 1.8.0_152
```
  @Test
  public void test10yTimer(final TestContext ctx) {
    final Async async = ctx.async();
    final Vertx vertx = Vertx.vertx();
    vertx.setTimer(1000L * 60 * 60 * 24 * 365 * 10, t -> {
      logger.info("10y timer");
      async.complete();
    });
  }
```

different behavior on linux systems (as well higher delays are needed for the test)
vertx 3.5.0, linux 4.13.9, openjdk 1.8.0_144
```
  @Test
  public void test300yTimer(final TestContext ctx) {
    final Async async = ctx.async();
    final Vertx vertx = Vertx.vertx();
    vertx.setTimer(1000L * 60 * 60 * 24 * 365 * 300, t -> {
      logger.info("300y timer");
      async.complete();
    });
  }
```

the timer immediately triggers without any error or exception

**Comment by zyclonite** [comment]
should be handled on netty side with a proper exception already
https://github.com/netty/netty/issues/7365

**Comment by vietj** [comment]
I think you should make a Netty reproducer to help make this move forward properly

**Comment by normanmaurer** [comment]
Proposed fix https://github.com/netty/netty/pull/7402/

**Comment by zyclonite** [comment]
looks good on linux

if setting the timer too high, the IllegalArgumentException is thrown
´´´
java.lang.IllegalArgumentException: days: 109500 (expected: < 1068)

	at io.netty.channel.nio.NioEventLoop.validateScheduled(NioEventLoop.java:833)
	at io.netty.util.concurrent.AbstractScheduledEventExecutor.schedule(AbstractScheduledEventExecutor.java:153)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.<init>(VertxImpl.java:860)
	at io.vertx.core.impl.VertxImpl.scheduleTimeout(VertxImpl.java:465)
	at io.vertx.core.impl.VertxImpl.setTimer(VertxImpl.java:325)
	at MainTest.test(MainTest.java:8)
´´´

**Comment by zyclonite** [comment]
shows same consistent behaviour on osx as well
