### ISSUE TITLE
Event loop context executing with wrong thread

### ISSUE THREAD

**Issue by emmx** [eclipse-vertx/vert.x#2534]
Code to reproduce the error: https://gist.github.com/emmx/52e672b4f163d471ed36fed9fae8b93a

I'm running it on a AWS instance, it shouldn't matter but maybe network performance is important in case this is caused by a race condition.

Vert.x 3.5.2
Java 10.0.1

```
java.lang.IllegalStateException: Uh oh! Event loop context executing with wrong thread! Expected null got Thread[globalEventExecutor-1-1,5,main]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:318)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.http.impl.HttpClientRequestImpl.lambda$connect$10(HttpClientRequestImpl.java:639)
	at io.vertx.core.http.impl.ConnectionManager.lambda$getConnection$5(ConnectionManager.java:166)
	at io.vertx.core.http.impl.pool.Pool.lambda$createConnection$4(Pool.java:315)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.http.impl.HttpChannelConnector.connectFailed(HttpChannelConnector.java:280)
	at io.vertx.core.http.impl.HttpChannelConnector.lambda$doConnect$2(HttpChannelConnector.java:181)
	at io.vertx.core.net.impl.ChannelProvider.lambda$connect$0(ChannelProvider.java:54)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:34)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:431)
	at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:240)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by vietj** [comment]
the only error I can get when running this is:

javax.net.ssl.SSLHandshakeException: Failed to create SSL connection
	at io.vertx.core.http.impl.HttpChannelConnector.handshakeFailure(HttpChannelConnector.java:235)
	at io.vertx.core.http.impl.HttpChannelConnector.lambda$null$0(HttpChannelConnector.java:171)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:1726)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vietj** [comment]
can you add a breakpoint in `GlobalEventExecutor#execute(Runnable)` method and capture the stack trace ?

for instance if you are intellij, you can do this:

<img width="747" alt="screen shot 2018-07-11 at 17 32 55" src="https://user-images.githubusercontent.com/225674/42582950-7ac5b2a4-8530-11e8-97f6-c25c32cf150e.png">

it will log the stack trace to the console.

**Comment by emmx** [comment]
Breakpoint reached
	  at io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:205)
	  at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:760)
	  at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)
	  at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:113)
	  at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87)
	  at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:328)
	  at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	  at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
	  at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:49)
	  at io.vertx.core.http.impl.HttpChannelConnector.doConnect(HttpChannelConnector.java:185)
	  at io.vertx.core.http.impl.HttpChannelConnector.connect(HttpChannelConnector.java:97)
	  at io.vertx.core.http.impl.pool.Pool.createConnection(Pool.java:290)
	  at io.vertx.core.http.impl.pool.Pool.lambda$acquireConnection$3(Pool.java:200)
	  at io.vertx.core.http.impl.pool.Pool$$Lambda$97.279569212.run(Unknown Source:-1)
	  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:-1)
	  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	  at java.lang.Thread.run(Thread.java:844)

**Comment by emmx** [comment]
Here is something interesting. If you use just one client the error goes away, if you use multiple clients like in the example but you don't increase the pool size (.setMaxPoolSize(100)), it also works fine.

**Comment by emmx** [comment]
Reason the connection failed and global even loop was used:

```
io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioSocketChannel
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
	at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:49)
	at io.vertx.core.http.impl.HttpChannelConnector.doConnect(HttpChannelConnector.java:185)
	at io.vertx.core.http.impl.HttpChannelConnector.connect(HttpChannelConnector.java:97)
	at io.vertx.core.http.impl.pool.Pool.createConnection(Pool.java:290)
	at io.vertx.core.http.impl.pool.Pool.lambda$acquireConnection$3(Pool.java:200)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedConstructorAccessor11.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
	... 15 more
Caused by: io.netty.channel.ChannelException: Failed to open a socket.
	at io.netty.channel.socket.nio.NioSocketChannel.newSocket(NioSocketChannel.java:68)
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:85)
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:78)
	... 19 more
Caused by: java.net.SocketException: Too many open files
	at java.base/sun.nio.ch.Net.socket0(Native Method)
	at java.base/sun.nio.ch.Net.socket(Net.java:411)
	at java.base/sun.nio.ch.Net.socket(Net.java:404)
	at java.base/sun.nio.ch.SocketChannelImpl.<init>(SocketChannelImpl.java:104)
	at java.base/sun.nio.ch.SelectorProviderImpl.openSocketChannel(SelectorProviderImpl.java:60)
	at io.netty.channel.socket.nio.NioSocketChannel.newSocket(NioSocketChannel.java:66)
	... 21 more
```

**Comment by vietj** [comment]
thanks that's helpeful, I'll have a look at it

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/issues/2670
