### ISSUE TITLE
EventBus: if handler registration has pending messages to deliver, but handler has been set to null, results in NPE.

### ISSUE THREAD

**Issue by sfitts** [eclipse-vertx/vert.x#2608]
Version: 3.5.3

This one is a bit hard to reproduce outside of a larger system.  For us it happens when we have an Rx chain reading from an event bus consumer (implemented via `FlowableReadStream`).  If we cancel the subscription then this calls `FlowableReadStream.release()`.  This sets all of the handlers on the underlying stream (which is a `HandlerRegistration` in this case) to `null`.  It then resumes the stream which causes it to attempt to deliver any data that it has in its pending queue.  Since the handler is now `null` the resulting delivery attempt results in an NPE and lots of log spew, like this:

```
13:41:01.986 [vert.x-eventloop-thread-4] ERROR i.v.c.e.impl.HandlerRegistration - Failed to handleMessage. address: vantiq-local://cad8cdd0-ad5d-11e8-b442-7a15f23eec05
java.lang.NullPointerException: null
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:223)
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$checkNextTick$5(HandlerRegistration.java:248)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
13:41:01.992 [vert.x-eventloop-thread-4] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: null
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:223)
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$checkNextTick$5(HandlerRegistration.java:248)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

Either the HandlerRegistration code should check for the null handler and *silently* drop the data (perhaps invoking the discard handler -- see #2488) or the stream should offer a way to flush the pending data which can be called by `release`.  I'm assuming we don't want to flush the queue when the handler is set to `null`, though that would probably fix this as well.

**Comment by vietj** [comment]
thanks @sfitts would you mind checking this behavior with vertx master branch ?
