### ISSUE TITLE
Sporadic failures of ComplexHATest#testComplexFailover

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#2649]
```
*** Iteration 4/10 of test
Starting test: ComplexHATest#testComplexFailover 
A quorum has been obtained. Any deploymentIDs waiting on a quorum will now be deployed 
A quorum has been obtained. Any deploymentIDs waiting on a quorum will now be deployed 
A quorum has been obtained. Any deploymentIDs waiting on a quorum will now be deployed 
A quorum has been obtained. Any deploymentIDs waiting on a quorum will now be deployed 
A quorum has been obtained. Any deploymentIDs waiting on a quorum will now be deployed 
A quorum has been obtained. Any deploymentIDs waiting on a quorum will now be deployed 
A quorum has been obtained. Any deploymentIDs waiting on a quorum will now be deployed 
A quorum has been obtained. Any deploymentIDs waiting on a quorum will now be deployed 
node17e6bb8c-a7ff-4249-94c4-59da50d9ff3d says: Node c7ac2832-6129-4bc8-9fdd-d0a9d321815a has failed. This node will deploy 19 deploymentIDs from that node. 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
nodedb42e894-daa5-4968-b763-04df950514c2 says: Node f31ade06-e2cf-4f1d-b82e-58a36a5af8fd has failed. This node will deploy 27 deploymentIDs from that node. 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
node458e6814-f2b7-408f-92a8-cc098452d61e says: Node f7095b27-8efa-4976-a8ac-87fd34054a64 has failed. This node will deploy 21 deploymentIDs from that node. 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
node17e6bb8c-a7ff-4249-94c4-59da50d9ff3d says: Node 458e6814-f2b7-408f-92a8-cc098452d61e has failed. This node will deploy 39 deploymentIDs from that node. 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
nodedb42e894-daa5-4968-b763-04df950514c2 says: Node 17e6bb8c-a7ff-4249-94c4-59da50d9ff3d has failed. This node will deploy 31 deploymentIDs from that node. 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
nodefe0e4a21-74c4-4d1a-abe4-edf3dbf7591e says: Node 17e6bb8c-a7ff-4249-94c4-59da50d9ff3d has failed. This node will deploy 31 deploymentIDs from that node. 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
java.lang.AssertionError: expected:<31> but was:<45>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.vertx.test.core.AsyncTestBase.assertEquals(AsyncTestBase.java:235)
	at io.vertx.core.ComplexHATest.checkDeployments(ComplexHATest.java:224)
	at io.vertx.core.ComplexHATest.failedOverOnto(ComplexHATest.java:203)
	at io.vertx.core.ComplexHATest.lambda$createNodes$10(ComplexHATest.java:196)
	at io.vertx.core.impl.HAManager.lambda$checkFailover$10(HAManager.java:500)
	at io.vertx.core.impl.HAManager.lambda$runOnContextAndWait$13(HAManager.java:529)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.AssertionError: expected:<31> but was:<45>
	at org.junit.Assert.fail(Assert.java:88)
Unhandled exception 
java.lang.AssertionError: expected:<31> but was:<45>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.vertx.test.core.AsyncTestBase.assertEquals(AsyncTestBase.java:235)
	at io.vertx.core.ComplexHATest.checkDeployments(ComplexHATest.java:224)
	at io.vertx.core.ComplexHATest.failedOverOnto(ComplexHATest.java:203)
	at io.vertx.core.ComplexHATest.lambda$createNodes$10(ComplexHATest.java:196)
	at io.vertx.core.impl.HAManager.lambda$checkFailover$10(HAManager.java:500)
	at io.vertx.core.impl.HAManager.lambda$runOnContextAndWait$13(HAManager.java:529)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.vertx.test.core.AsyncTestBase.assertEquals(AsyncTestBase.java:235)
	at io.vertx.core.ComplexHATest.checkDeployments(ComplexHATest.java:224)
	at io.vertx.core.ComplexHATest.failedOverOnto(ComplexHATest.java:203)
	at io.vertx.core.ComplexHATest.lambda$createNodes$10(ComplexHATest.java:196)
	at io.vertx.core.impl.HAManager.lambda$checkFailover$10(HAManager.java:500)
	at io.vertx.core.impl.HAManager.lambda$runOnContextAndWait$13(HAManager.java:529)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
nodefe0e4a21-74c4-4d1a-abe4-edf3dbf7591e says: Node db42e894-daa5-4968-b763-04df950514c2 has failed. This node will deploy 17 deploymentIDs from that node. 
java.lang.AssertionError: expected:<31> but was:<45>
	at org.junit.Assert.fail(Assert.java:88)
	at io.vertx.test.core.AsyncTestBase.fail(AsyncTestBase.java:262)Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 

	at io.vertx.core.ComplexHATest.testComplexFailover(ComplexHATest.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at io.vertx.test.core.RepeatRule$RepeatStatement.evaluate(RepeatRule.java:37)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle1 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle3 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
Successfully redeployed verticle java:io.vertx.test.verticles.HAVerticle2 after failover 
java.lang.AssertionError: expected:<31> but was:<62>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.vertx.test.core.AsyncTestBase.assertEquals(AsyncTestBase.java:235)
	at io.vertx.core.ComplexHATest.checkDeployments(ComplexHATest.java:224)
	at io.vertx.core.ComplexHATest.failedOverOnto(ComplexHATest.java:203)
	at io.vertx.core.ComplexHATest.lambda$createNodes$10(ComplexHATest.java:196)
	at io.vertx.core.impl.HAManager.lambda$checkFailover$10(HAManager.java:500)
	at io.vertx.core.impl.HAManager.lambda$runOnContextAndWait$13(HAManager.java:529)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Unhandled exception 
java.lang.AssertionError: expected:<31> but was:<62>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.vertx.test.core.AsyncTestBase.assertEquals(AsyncTestBase.java:235)
	at io.vertx.core.ComplexHATest.checkDeployments(ComplexHATest.java:224)
	at io.vertx.core.ComplexHATest.failedOverOnto(ComplexHATest.java:203)
	at io.vertx.core.ComplexHATest.lambda$createNodes$10(ComplexHATest.java:196)
	at io.vertx.core.impl.HAManager.lambda$checkFailover$10(HAManager.java:500)
	at io.vertx.core.impl.HAManager.lambda$runOnContextAndWait$13(HAManager.java:529)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.387 sec <<< FAILURE! - in io.vertx.core.ComplexHATest
testComplexFailover(io.vertx.core.ComplexHATest)  Time elapsed: 2.379 sec  <<< FAILURE!
java.lang.AssertionError: expected:<31> but was:<45>
	at org.junit.Assert.fail(Assert.java:88)
	at io.vertx.test.core.AsyncTestBase.fail(AsyncTestBase.java:262)
	at io.vertx.core.ComplexHATest.testComplexFailover(ComplexHATest.java:77)
```

**Comment by tsegismont** [comment]
This has been fixed in master by @vietj
