### ISSUE TITLE
SSH incompatible event loop when NativeTransport set to true

### ISSUE THREAD

**Issue by asantoso** [eclipse-vertx/vert.x#2651]
java.io.IOException: java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.epoll.EpollEventLoop
	at io.termd.core.ssh.netty.Helper.toIOException(Helper.java:33)
	at io.termd.core.ssh.netty.NettyIoAcceptor.bind(NettyIoAcceptor.java:99)
	at org.apache.sshd.server.SshServer.start(SshServer.java:319)
	at io.vertx.ext.shell.term.impl.SSHServer.lambda$listen$6(SSHServer.java:212)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.epoll.EpollEventLoop
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:469)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:331)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:282)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:278)
	at io.termd.core.ssh.netty.NettyIoAcceptor.bind(NettyIoAcceptor.java:88)

**Comment by vietj** [comment]
yes taht's expected, there should be some lifting project to accomodate this

**Comment by vietj** [comment]
do you mind try contribute a fix for this ?

**Comment by jpforevers** [comment]
@vietj Can someone fix this?

**Comment by vietj** [comment]
this should be reopened in Vertx-shell project and checked against vertx 5
