### ISSUE TITLE
NPE on HttpServerResponse.setChunked(false) on 3.5.4

### ISSUE THREAD

**Issue by vsct-jburet** [eclipse-vertx/vert.x#2653]
java.lang.NullPointerException: null
at io.vertx.core.http.impl.headers.VertxHttpHeaders.set(VertxHttpHeaders.java:384)
at io.vertx.core.http.impl.HttpServerResponseImpl.setChunked(HttpServerResponseImpl.java:136)
at io.vertx.core.http.impl.HttpServerResponseImpl.setChunked(HttpServerResponseImpl.java:53)

**Comment by vsct-jburet** [comment]
not reproductible in 3.5.3

**Comment by vietj** [comment]
thanks for reporting
