### ISSUE TITLE
Problems decoding payload

### ISSUE THREAD

**Issue by brunomanzo** [eclipse-vertx/vert.x#2686]
Hello, I am making a really simple route in vert.x scala:

```scala
    router
      .put("/clients/:apiKey")
      .handler(handler => {
        handler.response().end()
      })
```

I have some payloads with "=" and "%", like this example:

`curl -v XPUT localhost:8085/clients/test -d '{"s":"Q==","":"%IM" }'`

For some strange reason when both are present I am getting this in log:
```
Caused by: java.lang.IllegalArgumentException: invalid hex byte 'IM' at index 8 of '=","":"%IM" }'
	at io.netty.util.internal.StringUtil.decodeHexByte(StringUtil.java:244)
	at io.netty.handler.codec.http.QueryStringDecoder.decodeComponent(QueryStringDecoder.java:351)
	at io.netty.handler.codec.http.QueryStringDecoder.decodeComponent(QueryStringDecoder.java:309)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.decodeAttribute(HttpPostStandardRequestDecoder.java:644)
```

What I cand do about? Not sure if it is vertx or netty issue.

**Comment by brunomanzo** [comment]
I added this to the curl: `-H 'Content-Type: application/json'`
Solved my problem.
