### ISSUE TITLE
NPE during h2c upgrade without host header

### ISSUE THREAD

**Issue by rvansa** [eclipse-vertx/vert.x#2699]
When the server receives h2c upgrade request without Host header, it throws NPE:

```
09:41:50,996 ERROR (vert.x-eventloop-thread-2) [i.v.c.n.i.ConnectionBase] value java.lang.NullPointerException: value
	at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:31)
	at io.netty.handler.codec.DefaultHeaders.set(DefaultHeaders.java:431)
	at io.netty.handler.codec.http2.DefaultHttp2Headers.authority(DefaultHttp2Headers.java:145)
	at io.vertx.core.http.impl.HttpServerImpl$Http2UpgradeHandler.channelRead(HttpServerImpl.java:966)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
```

The host header is mandatory, but upon client error the server should respond with error (right now it sends 101 Switching protocols and then the connection is terminated).

**Comment by vietj** [comment]
thanks, can you give try with 3.6.0-SNAPSHOT ?

**Comment by rvansa** [comment]
It seems that snapshot handles this correctly, closing. Thanks for a quick reaction.

**Comment by vietj** [comment]
it might be bugged in 3.5.x, for now we are focusing on 3.6.0 that will be released soon
