### ISSUE TITLE
NPE in OpenApi3Utils for dynamic number of query parameters in spec

### ISSUE THREAD

**Issue by radder5** [eclipse-vertx/vert.x#2712]
On exploring the use of` web-api-contract` and `OpenAPI3RouterFactory.create` and have the requirement to have a variable (dynamic) number of query parameters for an endpoint e.g. `/my/path/v1?param1=value1&param2=value2` etc. (for a search solution) but the parsing of this in OpenApi3Utils.class fails with a NPE.
```
Nov 15, 2018 8:41:36 AM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NullPointerException
    at io.vertx.ext.web.api.contract.openapi3.impl.OpenApi3Utils.solveObjectParameters(OpenApi3Utils.java:196)
    at io.vertx.ext.web.api.contract.openapi3.impl.OpenAPI3RequestValidationHandlerImpl.magicParameterExplodedObject(OpenAPI3RequestValidationHandlerImpl.java:293)
    at io.vertx.ext.web.api.contract.openapi3.impl.OpenAPI3RequestValidationHandlerImpl.checkSupportedAndNeedWorkaround(OpenAPI3RequestValidationHandlerImpl.java:371)
    at io.vertx.ext.web.api.contract.openapi3.impl.OpenAPI3RequestValidationHandlerImpl.parseParameter(OpenAPI3RequestValidationHandlerImpl.java:405)
    at io.vertx.ext.web.api.contract.openapi3.impl.OpenAPI3RequestValidationHandlerImpl.parseOperationSpec(OpenAPI3RequestValidationHandlerImpl.java:97)
    at io.vertx.ext.web.api.contract.openapi3.impl.OpenAPI3RequestValidationHandlerImpl.<init>(OpenAPI3RequestValidationHandlerImpl.java:87)
```
the relevant slice of my spec.yaml is
```
- name: params
  in: query
     schema:
        type: object
            type: string
     style: form
     explode: true
```
it parses fine in SwaggerUI for example with the correct output. 
A suggested workaround of an empty `{}` for the object properties sorted the NPE, but no `additionalProperties` are parsed from the url (which may be a secondary issue)

**Comment by radder5** [comment]
Moved to vertx-web
