### ISSUE TITLE
ClusteredEventBus with ZookeeperClusterManager loosing the messages when one of the nodes is leaving the cluster

### ISSUE THREAD

**Issue by gkozyryatskyy** [eclipse-vertx/vert.x#2738]
Hello guys!

It seems like vertx cluster event bus (zookeeper implementation) loosing some messages when some of the nodes leaving the cluster. This can be related to https://github.com/eclipse-vertx/vert.x/pull/1594 or https://github.com/vert-x3/vertx-hazelcast/issues/13 issues.
Theoretically, it is still sending the messages to the shutted down node.

Here is a code to reproduce:

Start zookeeper
`docker run -p 2181:2181 zookeeper:3.4.13`

Base class:
```
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import io.vertx.core.DeploymentOptions;
import io.vertx.core.Future;
import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;
import io.vertx.core.json.JsonObject;
import io.vertx.spi.cluster.zookeeper.ZookeeperClusterManager;

public class ShutdownTestBase {

    protected List<Vertx> cluster = Collections.synchronizedList(new ArrayList<>());

    public Future<Object> startClusterNode(String serviceName) {
        Future<Object> retval = Future.future();

        JsonObject zkConfig = new JsonObject();
        zkConfig.put("zookeeperHosts", "127.0.0.1");
        ZookeeperClusterManager cm = new ZookeeperClusterManager(zkConfig);
        VertxOptions options = new VertxOptions();
        options.setClusterManager(cm);
        // for cluster init do not throw any warnings
        options.setMaxEventLoopExecuteTime(8_000_000_000l);
        Vertx.clusteredVertx(options, res -> {
            if (res.succeeded()) {
                cluster.add(res.result());
                runService(serviceName, res.result()).setHandler(retval);
                System.out.println("................... Vertx deployed ...................");
            } else {
                res.cause().printStackTrace();
            }
        });

        return retval;
    }

    private Future<Object> runService(String serviceName, Vertx vertx) {
        Future<Object> retval = Future.future();
        vertx.deployVerticle(serviceName, new DeploymentOptions(), e -> {
            retval.complete();
        });
        return retval;
    }

}
```
Test class:
```
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;

import org.junit.Test;
import org.junit.runner.RunWith;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.CompositeFuture;
import io.vertx.core.Future;
import io.vertx.ext.unit.Async;
import io.vertx.ext.unit.TestContext;
import io.vertx.ext.unit.junit.VertxUnitRunner;

@RunWith(VertxUnitRunner.class)
public class ShutdownTest extends ShutdownTestBase {

    private static String ADDRESS = "test.shutdown";
    private static int INSTANCES_COUNT = 2;
    private int i = 0;

    // massages tracking map
    private static Map<Integer, Object> MESSAGE_MAP = Collections.synchronizedMap(new HashMap<>());

    @Test
    public void shutdownTest(TestContext context) {
        Async async = context.async();

        @SuppressWarnings("rawtypes")
        List<Future> servicesDeploy = new ArrayList<>();
        // start cluster
        for (int i = 0; i < INSTANCES_COUNT; i++) {
            servicesDeploy.add(startClusterNode(ShutdownTestMS.class.getName()));
        }
        // start test
        CompositeFuture.join(servicesDeploy).setHandler(e -> {
            System.out.println("Cluster: " + cluster);
            // sending messages
            long periodic = cluster.get(0).setPeriodic(10l, timer -> sendMessage());
            // closing last instance
            cluster.get(0).setTimer(500l, timer -> cluster.get(cluster.size() - 1).close());
            // stop sending messages
            cluster.get(0).setTimer(1000l, timer -> {
                cluster.get(0).cancelTimer(periodic);
            });
            // Closing all
            cluster.get(0).setTimer(2000l, timer -> {
                System.out.println("Failed messages " + MESSAGE_MAP);
                context.assertTrue(MESSAGE_MAP.isEmpty(),
                        "Message map should be empty, but was " + MESSAGE_MAP.toString());
                async.complete();
                cluster.forEach(vertx -> vertx.close());
            });

        });
    }

    private void sendMessage() {
        System.out.println("Sending message " + i);
        MESSAGE_MAP.put(i, i);
        cluster.get(0).eventBus().send(ADDRESS, String.valueOf(i));
        i++;
    }

    public static class ShutdownTestMS extends AbstractVerticle {

        private static AtomicInteger holder = new AtomicInteger(0);

        @Override
        public void start() throws Exception {
            int number = holder.incrementAndGet();
            vertx.eventBus().<String> consumer(ADDRESS, e -> {
                int message = Integer.parseInt(e.body());
                System.out.println(number + " got message " + message);
                MESSAGE_MAP.remove(message);
            });
        }

    }

}
```
Stack trace:
```
[WEAVO_MODE_IS_UNDEFINED] [NATIVE] 2018-11-29 18:29:36,668 [vert.x-worker-thread-0] INFO  [admins-MacBook-Pro.local] o.a.c.f.imps.CuratorFrameworkImpl - Starting
[WEAVO_MODE_IS_UNDEFINED] [NATIVE] 2018-11-29 18:29:36,668 [vert.x-worker-thread-0] INFO  [admins-MacBook-Pro.local] o.a.c.f.imps.CuratorFrameworkImpl - Starting
[WEAVO_MODE_IS_UNDEFINED] [NATIVE] 2018-11-29 18:29:41,785 [vert.x-worker-thread-0-EventThread] INFO  [admins-MacBook-Pro.local] o.a.c.f.state.ConnectionStateManager - State change: CONNECTED
[WEAVO_MODE_IS_UNDEFINED] [NATIVE] 2018-11-29 18:29:41,785 [vert.x-worker-thread-0-EventThread] INFO  [admins-MacBook-Pro.local] o.a.c.f.state.ConnectionStateManager - State change: CONNECTED
................... Vertx deployed ...................
................... Vertx deployed ...................
Cluster: [io.vertx.core.impl.VertxImpl@2fbb33e6, io.vertx.core.impl.VertxImpl@5c18005b]
Sending message 0
Sending message 1
1 got message 1
Sending message 2
1 got message 0
Sending message 3
Sending message 4
1 got message 3
Sending message 5
1 got message 5
Sending message 6
2 got message 2
2 got message 4
2 got message 6
Sending message 7
1 got message 7
Sending message 8
2 got message 8
...
Sending message 50
Sending message 51
1 got message 51
Sending message 52
Sending message 53
1 got message 53
Sending message 54
1 got message 54
Sending message 55
1 got message 55
[WEAVO_MODE_IS_UNDEFINED] [NATIVE] 2018-11-29 18:29:48,083 [Curator-Framework-0] INFO  [admins-MacBook-Pro.local] o.a.c.f.imps.CuratorFrameworkImpl - backgroundOperationsLoop exiting
Sending message 56
1 got message 56
[WEAVO_MODE_IS_UNDEFINED] [NATIVE] 2018-11-29 18:29:48,097 [vert.x-eventloop-thread-9] ERROR [admins-MacBook-Pro.local] i.v.c.e.impl.HandlerRegistration - Failed to propagate registration for handler io.vertx.spi.cluster.zookeeper.impl.AsyncMapTTLMonitor$$Lambda$191/1719340525@23cb1cde and address __VERTX_ZK_TTL_HANDLER_ADDRESS
[WEAVO_MODE_IS_UNDEFINED] [NATIVE] 2018-11-29 18:29:48,099 [vert.x-eventloop-thread-10] ERROR [admins-MacBook-Pro.local] i.v.c.e.i.c.ClusteredEventBus - Failed to remove sub
java.lang.IllegalStateException: instance must be started before calling this method
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkExists(CuratorFrameworkImpl.java:367)
	at io.vertx.spi.cluster.zookeeper.impl.ZKMap.lambda$checkExists$5(ZKMap.java:198)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:749)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:522)
	at org.apache.curator.framework.imps.SyncBuilderImpl$1.processResult(SyncBuilderImpl.java:108)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:634)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505)
Sending message 57
1 got message 57
Sending message 58
1 got message 58
Sending message 59
1 got message 59
...
Sending message 98
1 got message 98
Sending message 99
1 got message 99
Failed messages {50=50, 52=52}
[WEAVO_MODE_IS_UNDEFINED] [NATIVE] 2018-11-29 18:29:49,528 [vert.x-eventloop-thread-5] ERROR [admins-MacBook-Pro.local] io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.AssertionError: Message map should be empty, but was {50=50, 52=52}. Expected true
	at io.vertx.ext.unit.impl.TestContextImpl.reportAssertionError(TestContextImpl.java:467)
	at io.vertx.ext.unit.impl.TestContextImpl.assertTrue(TestContextImpl.java:307)
	at com.anyclip.weavo._test.gk.ShutdownTest.lambda$4(ShutdownTest.java:54)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

For now this is really blocking for my project. Is it possible to do something with this?

For example:

1. 
- Send a call to other nodes, that current node is leaving
- And just then start all shutdown procedure
2. 
- enable some retry mechanism on the event bus and track closed connections or something..
3. 
- Unsubscribe from receiving messages
- push to verticles all the messages, received by event bus, before vertx instance will be shutted down
- In this case I can fail the messages manually
- stop the event bus and stop the instance

I will be very grateful for any help!

**Comment by tsegismont** [comment]
@gkozyryatskyy can you report this in the [vertx-zookeeper](https://github.com/vert-x3/vertx-zookeeper/issues/new) repo? Thank you

**Comment by gkozyryatskyy** [comment]
@tsegismont 
Yes, I will! Thank you for fast reply.

But also, Im experiencing the same issue with HazelcastClusterManager.. So it seems like not just ClusterManager issue.
