### ISSUE TITLE
NoSuchMethodError io.vertx.core.impl.VertxInternal.getOrCreateContext()

### ISSUE THREAD

**Issue by mountainowl** [eclipse-vertx/vert.x#2760]
**Version 3.6.0**

**Dependencies**
    compile "io.vertx:vertx-core:${vertxVersion}"
    compile "io.vertx:vertx-web-client:${vertxVersion}"
    compile "io.vertx:vertx-web:${vertxVersion}"
    compile "io.vertx:vertx-service-discovery:${vertxVersion}"
    compile "io.vertx:vertx-service-proxy:${vertxVersion}:processor"
    compile "io.vertx:vertx-codegen:${vertxVersion}"
    compile "io.vertx:vertx-codetrans:${vertxVersion}"
    compile "io.vertx:vertx-service-discovery-bridge-consul:${vertxVersion}"
    compile "io.vertx:vertx-web-api-contract:${vertxVersion}"
    compile "io.vertx:vertx-circuit-breaker:${vertxVersion}"
    compile "io.vertx:vertx-tcp-eventbus-bridge:${vertxVersion}"

**Stack Trace**

Dec 11, 2018 3:21:52 PM io.vertx.servicediscovery.consul.ConsulServiceImporter
INFO: Importing service consul (consul) from consul
Dec 11, 2018 3:21:52 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NoSuchMethodError: io.vertx.core.impl.VertxInternal.getOrCreateContext()Lio/vertx/core/impl/ContextImpl;
	at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMultiMap.get(HazelcastAsyncMultiMap.java:96)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.sendOrPub(ClusteredEventBus.java:228)
	at io.vertx.core.eventbus.impl.EventBusImpl$OutboundDeliveryContext.next(EventBusImpl.java:483)
	at io.vertx.core.eventbus.impl.EventBusImpl.sendOrPubInternal(EventBusImpl.java:440)
	at io.vertx.core.eventbus.impl.EventBusImpl.publish(EventBusImpl.java:148)
	at io.vertx.core.eventbus.impl.EventBusImpl.publish(EventBusImpl.java:143)
	at io.vertx.servicediscovery.impl.DiscoveryImpl.lambda$publish$6(DiscoveryImpl.java:319)
	at io.vertx.servicediscovery.impl.DefaultServiceDiscoveryBackend.lambda$null$0(DefaultServiceDiscoveryBackend.java:74)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:284)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

**This does not happen with 3.5.4**

**Comment by vietj** [comment]
can you make sure you are using the same 3.6 jars everywehre ?

**Comment by mountainowl** [comment]
Thx for the pointer. 
I had vert.x hazelcast being pulled in at 3.5.0. 
Moving that version up to 3.6.0 resolved it.
