### ISSUE TITLE
HttpClientRequest random timeout when reuse keep-alive connecton and  server close connection

### ISSUE THREAD

**Issue by wujimin** [eclipse-vertx/vert.x#2772]
- vertx HttpClient request to server successfully, and connection keep-alive
- client send the second request with the connection from pool, but the connection is closed by server
   sometimes HttpClientRequest can not handle this correctly, will cause a timeout problem, not invoke excepton handler immediately
- test with vertx 3.5.3/3.6.2, both have the problem

## analysis:
- io.netty.channel.AbstractChannel.AbstractUnsafe#close(io.netty.channel.ChannelPromise, java.lang.Throwable, java.nio.channels.ClosedChannelException, boolean)
  - (1) deactive channel
  - (2) fire channel inactive and deregister (async task)
- vertx process connecton close based on (2)
- vertx invoke netty channel write with VoidPromise, can not know write failed, can only waiting for timeout.
so when a client request is created and sent between (1) and (2), which can be done by runOnContext, will cause a timeout problem

## reproducer code:
it's a random problem, and difficult to reproduce
so i build the reproducer case with javassist, controll the work flow to make the problem always triggered.
```
package test;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.vertx.core.Context;
import io.vertx.core.Vertx;
import io.vertx.core.http.HttpClient;
import io.vertx.core.http.HttpClientRequest;
import io.vertx.core.http.HttpClientResponse;
import io.vertx.core.http.HttpConnection;
import javassist.CannotCompileException;
import javassist.ClassPool;
import javassist.CtClass;
import javassist.CtMethod;
import javassist.NotFoundException;

public class ClientTimeoutReproducer {
  private static final Logger LOGGER = LoggerFactory.getLogger(ClientTimeoutReproducer.class);

  static ClassPool classPool = ClassPool.getDefault();

  static Vertx vertx;

  static HttpClient httpClient;

  static Context clientContext;

  static HttpConnection serverHttpConnection;

  static Context serverContext;

  public static void main(String[] args) throws NotFoundException, CannotCompileException {
    injectNetty();

    vertx = Vertx.vertx();

    clientContext = vertx.getOrCreateContext();

    vertx.createHttpServer()
        .connectionHandler(c -> serverHttpConnection = c)
        .requestHandler(req -> req.response().end("hi"))
        .listen(5000, ar -> {
          Thread.currentThread().setName("server");
          serverContext = Vertx.currentContext();

          if (ar.failed()) {
            LOGGER.info("listen failed", ar.cause());
            System.exit(-1);
          }

          clientContext.runOnContext(v -> {
            Thread.currentThread().setName("client");
            httpClient = vertx.createHttpClient();
            sendRequest();
          });
        });
  }

  private static void sendRequest() {
    HttpClientRequest req = httpClient.get(5000, "localhost", "/", ClientTimeoutReproducer::onResponse);
    LOGGER.info("create new client request: {}", req);
    req.setTimeout(3000)
        .exceptionHandler(e -> {
          LOGGER.info("exception, req: {}, local: {}, {}", req, req.connection().localAddress(), e.getMessage());
          System.exit(-1);
        })
        .end();
  }

  private static void onResponse(HttpClientResponse httpClientResponse) {
    httpClientResponse.bodyHandler(buf -> {
      LOGGER.info("get resp: {}, local: {}", buf, httpClientResponse.request().connection().localAddress());

      LOGGER.info("                                          ");
      LOGGER.info("************* begin reproduce ************");
      LOGGER.info("notify server close connection");
      serverContext.runOnContext(v -> serverHttpConnection.close());
    });
  }

  public static void beforeFireChannelInactiveAndDeregister() {
    if ("client".equals(Thread.currentThread().getName())) {
      LOGGER.info(
          "*** before io.netty.channel.AbstractChannel$AbstractUnsafe.fireChannelInactiveAndDeregister, mock some other thread submit a runOnContext task to send request ***");
      clientContext.runOnContext(v -> sendRequest());
    }
  }

  private static void injectNetty() throws NotFoundException, CannotCompileException {
    CtClass abstractUnsafe = classPool.get("io.netty.channel.AbstractChannel$AbstractUnsafe");

    CtMethod fireChannelInactiveAndDeregister = abstractUnsafe.getDeclaredMethod("fireChannelInactiveAndDeregister");
    fireChannelInactiveAndDeregister
        .insertBefore("test.ClientTimeoutReproducer.beforeFireChannelInactiveAndDeregister();");

    abstractUnsafe.toClass();
  }
}
```

run result:
```
2018-12-19 22:47:30,335 [INFO] [client] - create new client request: io.vertx.core.http.impl.HttpClientRequestImpl@44657f26 (ClientTimeoutReproducer.java:78)
2018-12-19 22:47:30,492 [INFO] [client] - get resp: hi, local: 127.0.0.1:63355 (ClientTimeoutReproducer.java:89)
2018-12-19 22:47:30,492 [INFO] [client] -                                            (ClientTimeoutReproducer.java:91)
2018-12-19 22:47:30,492 [INFO] [client] - ************* begin reproduce ************ (ClientTimeoutReproducer.java:92)
2018-12-19 22:47:30,492 [INFO] [client] - notify server close connection (ClientTimeoutReproducer.java:93)
2018-12-19 22:47:30,492 [INFO] [client] - *** before io.netty.channel.AbstractChannel$AbstractUnsafe.fireChannelInactiveAndDeregister, mock some other thread submit a runOnContext task to send request *** (ClientTimeoutReproducer.java:100)
2018-12-19 22:47:30,492 [INFO] [client] - create new client request: io.vertx.core.http.impl.HttpClientRequestImpl@563144b4 (ClientTimeoutReproducer.java:78)
2018-12-19 22:47:33,518 [INFO] [client] - exception, req: io.vertx.core.http.impl.HttpClientRequestImpl@563144b4, local: 127.0.0.1:63355, The timeout period of 3000ms has been exceeded while executing GET / for host localhost (ClientTimeoutReproducer.java:81)
```

**Comment by vietj** [comment]
can you share it as a github project ?

**Comment by vietj** [comment]
normally, as the client request is on the Http1xClientConnection and set, the close event should invoke the request exception handler on the `requestInProgress`, since this is set

**Comment by wujimin** [comment]
i will push the project to github tomorrow morning

yes. normally no problem, but this case have problem

**Comment by vietj** [comment]
thanks, that will be helpful

**Comment by wujimin** [comment]
https://github.com/wujimin/vertx-client-timeout-reproducer

**Comment by vietj** [comment]
when I run it from IDE I get:

Exception in thread "main" javassist.NotFoundException: io.netty.channel.AbstractChannel$AbstractUnsafe
	at javassist.ClassPool.get(ClassPool.java:452)
	at test.ClientTimeoutReproducer.injectNetty(ClientTimeoutReproducer.java:107)
	at test.ClientTimeoutReproducer.main(ClientTimeoutReproducer.java:50)

**Comment by vietj** [comment]
that's with OpenJDK 11 - it seems ok with Java 8

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/issues/2773
