### ISSUE TITLE
io.vertx.core.VertxException: Thread blocked

### ISSUE THREAD

**Issue by JuKu** [eclipse-vertx/vert.x#2798]
Hi there,

i am already using **vertx.executeBlocking()** but i always get this exception:
```java
Jan 13, 2019 4:18:24 PM io.vertx.core.impl.BlockedThreadChecker
WARNUNG: Thread Thread[vert.x-worker-thread-1,5,main] has been blocked for 5644 ms, time limit is 0
io.vertx.core.VertxException: Thread blocked
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at com.jukusoft.mmo.gs.region.RegionContainerImpl.lambda$init$3(RegionContainerImpl.java:220)
	at com.jukusoft.mmo.gs.region.RegionContainerImpl$$Lambda$116/89177479.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273)
	at io.vertx.core.impl.ContextImpl$$Lambda$10/1232703108.run(Unknown Source)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.vertx.core.impl.TaskQueue$$Lambda$9/303846650.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

Jan 13, 2019 4:18:24 PM io.vertx.core.impl.BlockedThreadChecker
WARNUNG: Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 5593 ms, time limit is 0
io.vertx.core.VertxException: Thread blocked
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.commons.net.io.Util.copyStream(Util.java:102)
	at org.apache.commons.net.ftp.FTPClient._retrieveFile(FTPClient.java:1920)
	at org.apache.commons.net.ftp.FTPClient.retrieveFile(FTPClient.java:1885)
	at com.jukusoft.mmo.gs.region.ftp.FTPUtil.downloadSingleFile(FTPUtil.java:41)
	at com.jukusoft.mmo.gs.region.ftp.FTPUtil.downloadDirectory(FTPUtil.java:102)
	at com.jukusoft.mmo.gs.region.ftp.FTPUtil.downloadDirectory(FTPUtil.java:96)
	at com.jukusoft.mmo.gs.region.ftp.FTPUtil.downloadDirectory(FTPUtil.java:96)
	at com.jukusoft.mmo.gs.region.ftp.FTPUtil.downloadDirectory(FTPUtil.java:96)
	at com.jukusoft.mmo.gs.region.ftp.FTPUtil.downloadDirectory(FTPUtil.java:96)
	at com.jukusoft.mmo.gs.region.ftp.FTPUtil.downloadDirectory(FTPUtil.java:60)
	at com.jukusoft.mmo.gs.region.RegionContainerImpl.lambda$downloadFilesFromFtp$5(RegionContainerImpl.java:256)
	at com.jukusoft.mmo.gs.region.RegionContainerImpl$$Lambda$112/113015548.handle(Unknown Source)
	at com.jukusoft.mmo.gs.region.ftp.NFtpFactory.lambda$create$1(NFtpFactory.java:52)
	at com.jukusoft.mmo.gs.region.ftp.NFtpFactory$$Lambda$114/113714097.handle(Unknown Source)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:289)
	at io.vertx.core.impl.ContextImpl$$Lambda$11/2011477534.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.vertx.core.impl.ContextImpl$$Lambda$12/727546868.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

source code:
```java
//download files for region from ftp server (in another thread to avoid blocking og this thread)
vertx.executeBlocking(future -> {
    downloadFilesFromFtp();//this operation takes about 6-10 seconds
    future.complete();
}, (Handler<AsyncResult<Void>>) event -> {
    //don't do anything here
});
```

For explanaition:
I download some files from ftp server and this takes some time. So i have also tried to set the checker interval:
```java
vertxOptions.setBlockedThreadCheckInterval(30000);
```
but this doesn't have any effect.
It is a **clustered vertx instance** ([source file](https://github.com/JuKu/mmo-gameserver-2.0/blob/master/server/src/main/java/com/jukusoft/mmo/gs/frontend/utils/VertxManager.java)).

What can i do to solve this problem? Or how can i increase the limit?

**Comment by vietj** [comment]
it seems your code is also blocking the event-loop, your comment said `don't do anything here` but from what I can read, there is code executed at this place that also blocks the event loop (the second stack trace), can you check ?

**Comment by JuKu** [comment]
@vietj Thanks for your fast answer!

No, the comment `don't do anything here` is 1:1 copied from source file:
https://github.com/JuKu/mmo-gameserver-2.0/blob/master/region/src/main/java/com/jukusoft/mmo/gs/region/RegionContainerImpl.java (line 143 and 228).

**Comment by vietj** [comment]
it seems that this class use executeBlocking to wait for a latch, and it should not do that. execute blocking is meant to be used for shorter time than this. Instead I think it should use a dedicated thread to achieve this as copying file might take a lot of time.

**Comment by vietj** [comment]
so I believe an issue should be open in mmo-game to address the file copy in a better fashion.

**Comment by vietj** [comment]
I'm closing this issue for now and we can re-open if there is an acutal issue in vertx

**Comment by JuKu** [comment]
@vietj Thank you very much!
This hears good to me.

`execute blocking is meant to be used for shorter time than this`
Okay, i didn't knew this before, now the exception makes more sense.

**Comment by vietj** [comment]
I will add clarification in documentation about execute blocking usage.

**Comment by thuringia** [comment]
@vietj Sorry to comment on this old issue, but what is the actual recommendation here?
Our service needs to ingest multiply GBs of data, which does not fit into the definition of "reasonable" in the docs.
However, even moving the worker code into a separate `Runnable` which is only started from a worker verticle causes the blocked thread issue which even causes the whole service to become unresponsive.

As the documentation is very unclear in this area, how does Vert.x need indefinitely running tasks to be modeled?
The docs mention `runOnContext`, but does not go into detail, how this is supposed to be used.

Any help or insight is greatly appreciated.

**Comment by vietj** [comment]
we do recommend to go with your own thread or executor. If you need to communicate with Vert.x you can use its API from any thread or you can use the event bus send message. If you need to cooperate with your running thread then you should use a shared memory, e.g

```java
new Thread(() -> {
  AtomicBoolean doWork = new AtomicBoolean();
  while (doWork.get()) {
    int result = performBlockingTask();
    vertx.eventBus().send("some.address", result, ar -> {
      if (ar.succeeded() && ar.result()) {
        doWorker.set(false);
      }
    });
  }
}).start();
```
