### ISSUE TITLE
API design flaw - conflicting interests between requestHandler and router?

### ISSUE THREAD

**Issue by ORESoftware** [eclipse-vertx/vert.x#2810]
I have this error:

```console
java.lang.IllegalStateException: Set request or websocket handler first
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:196)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:191)
        at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:187)
        at huru.MainVerticle.start(MainVerticle.java:206)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.j
```

here is the culprit (the main verticle):

```java
package huru;

import huru.middleware.JWTHandler;
import io.vertx.core.AbstractVerticle;
import io.vertx.core.Vertx;
import io.vertx.core.eventbus.EventBus;
import io.vertx.core.http.HttpMethod;
import io.vertx.core.http.HttpServerRequest;
import io.vertx.core.http.HttpServerResponse;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.sql.SQLRowStream;
import io.vertx.ext.web.Router;
import io.vertx.ext.asyncsql.PostgreSQLClient;
import io.vertx.ext.jdbc.JDBCClient;
import io.vertx.ext.sql.ResultSet;
import io.vertx.ext.sql.SQLClient;
import io.vertx.ext.sql.SQLConnection;
import io.vertx.ext.web.RoutingContext;
import org.apache.log4j.Logger;
import io.vertx.core.Future;
import io.vertx.ext.web.handler.BodyHandler;


public class MainVerticle extends AbstractVerticle {
  
  private final Logger log = Logger.getLogger(MainVerticle.class);
 
  @Override
  public void start(Future<Void> f) throws Exception {
    
    super.start();
    
    final Router router = Router.router(vertx);
    router.route().handler(BodyHandler.create());
    router.route().handler(new JWTHandler());
    
    final EventBus eventBus = vertx.eventBus();
    
    eventBus.consumer("address", receivedMessage -> {
      log.debug("Received message: " + receivedMessage.body());
      receivedMessage.reply("my reply");
    });
    
    router.route(HttpMethod.GET, "/hello/:name").handler(ctx -> {
      // Retrieving request and response objects
      HttpServerRequest request = ctx.request();
      HttpServerResponse response = ctx.response();
      
      String name = request.getParam("name");
 
      response.putHeader("Content-Type", "text/plain");
      response.setChunked(true);
      response.write("Hello " + name);
      response.setStatusCode(200);
      response.end();
    });
    
    router.route("/").handler(ctx -> {
      HttpServerResponse response = ctx.response();
      response
        .putHeader("content-type", "text/html")
        .end("<h1>Hello from non-clustered messenger example!</h1>");
    });
    
    router.post("/send/:message").handler(this::sendMessage);

    router.route().last().handler(ctx -> {
      ctx.response().setStatusCode(404).end();
    });
    
    JsonObject config = new JsonObject()
      .put("username", "postgres")
      .put("password", "postgres")
      .put("database", "oleg")
      .put("host", "localhost")
      .put("port", 5432);
    
    SQLClient client = PostgreSQLClient.createShared(vertx, config);
  
    int port = 3005;
    
    vertx.createHttpServer()
      .exceptionHandler(ctx -> {
        
        log.error("In the exception handler.");
        log.error(ctx.getCause());
        
      })
//      .requestHandler(req -> {
//            the culprit? this request handler is commented out
//      })
      .listen(port, res -> {
        if (res.succeeded()) {
          System.out.println("Server listening on port " + port);
          f.complete();
        } else {
          System.out.println("Failed to launch server");
          f.fail(res.cause());
        }
      });
    
  }
  
}
```

there seems to be a conflict of interested between 

```java
    vertx.createHttpServer()
     .requestHandler(req -> {
            the culprit? this request handler is commented out
      })
```

and 

```java
    final Router router = Router.router(vertx);
```

**Comment by ORESoftware** [comment]
My only guess is that we'd want to tell the server to use the router, something like this:

```java
  vertx.createHttpServer()
     .requestHandler(router);
```

?

**Comment by tsegismont** [comment]
As indicated by @aesteve , you must set a request handler before starting the server.

**Comment by aesteve** [comment]
Feel free to adapt the examples and submit a pull request !
