### ISSUE TITLE
Calling unregister on a consumer that has not been fully registered across a cluster can result in metrics SPI call with null parameter.

### ISSUE THREAD

**Issue by sfitts** [eclipse-vertx/vert.x#2892]
Version 3.6.3

If you create a non-local event bus consumer and then invoke `unregister` on it before it has invoked its completion handler this can lead to calls to `EventBusMetrics.handlerUnregistered` where the `handler` parameter is `null`.  This would seem to violate the implied SPI contract and can trigger NPE's in at least some implementations.  See https://github.com/vert-x3/vertx-micrometer-metrics/issues/74 for one example.

This happens because the `HandlerRegistration.metrics` field isn't populated until `HandlerRegistration.setResult` is called and that doesn't occur until the consumer's subscription has been fully propagated across the cluster.

Note that this may not be the only issue with the premature call to `unregister` it is just the most obvious.

It would seem that either:

a) The premature `unregister` call should be rejected (especially if there are other, unwanted side-effects of this).
b) The SPI call should be made in a way that ensures a non-null `handler` parameter.
c) The SPI should be clarified to say that `null` is a legal value and then all implementations of the SPI updated to account for this.

I do not yet have a minimal reproduction.

**Comment by sfitts** [comment]
We also see this in the Websocket shutdown code during our server stress testing:

```
java.lang.NullPointerException: null
    at io.vertx.micrometer.impl.VertxEventBusMetrics.handlerUnregistered(VertxEventBusMetrics.java:79)
    at io.vertx.micrometer.impl.VertxEventBusMetrics.handlerUnregistered(VertxEventBusMetrics.java:33)
    at io.vertx.core.eventbus.impl.HandlerHolder.setRemoved(HandlerHolder.java:48)
    at io.vertx.core.eventbus.impl.EventBusImpl.removeLocalRegistration(EventBusImpl.java:307)
    at io.vertx.core.eventbus.impl.EventBusImpl.removeRegistration(EventBusImpl.java:289)
    at io.vertx.core.eventbus.impl.HandlerRegistration.doUnregister(HandlerRegistration.java:176)
    at io.vertx.core.eventbus.impl.HandlerRegistration.unregister(HandlerRegistration.java:135)
    at io.vertx.ext.web.handler.sockjs.impl.SockJSSocketBase.close(SockJSSocketBase.java:87)
    at io.vertx.ext.web.handler.sockjs.impl.RawWebSocketTransport$RawWSSockJSSocket.access$001(RawWebSocketTransport.java:56)
    at io.vertx.ext.web.handler.sockjs.impl.RawWebSocketTransport$RawWSSockJSSocket.lambda$new$0(RawWebSocketTransport.java:66)
    at io.vertx.core.http.impl.WebSocketImplBase.handleClosed(WebSocketImplBase.java:454)
    at io.vertx.core.http.impl.Http1xServerConnection.handleClosed(Http1xServerConnection.java:474)
    at io.vertx.core.net.impl.VertxHandler.lambda$channelInactive$5(VertxHandler.java:164)
```

**Comment by sfitts** [comment]
That one unfortunately looks like something we cannot prevent.  My guess is that the websocket is coming and going fast enough that the close happens before the cluster wide registration done at line 72 of `SockJSSocketBase` has a chance to complete.  I think to keep this from happening the WS code would have to install a completion handler and then defer any call to `unregister` until after that gets called.

**Comment by vietj** [comment]
yes this race has been reported in other places.

do you have some code to reproduce it ?

**Comment by sfitts** [comment]
@vietj unfortunately no.  We can't get it to happen outside of our full server running under heavy load (these all show up during our stress testing).  I think part of this is also loading up the cluster wide maps enough that the latency there gets high enough to notice (we're using Hazelcast as the cluster manager FWIW).  So even when you spin up a mini cluster in a single test, it isn't doesn't reproduce since you are all in one process and can't get the registration to run slowly enough.

**Comment by vietj** [comment]
ok Sean, I will investigate myself and reason about how to make this happen.

**Comment by vietj** [comment]
I think that in vertx-web we should actually change the consumer for being a local consumer, so this race condition will not happen anymore, that being said, this is a bug that should be fixed as well.

**Comment by vietj** [comment]
see https://github.com/vert-x3/vertx-web/issues/1221

**Comment by vietj** [comment]
@sfitts I believe it should be fixed, can you have a try with latest master ?

**Comment by sfitts** [comment]
Will do -- likely won't be until later in the week (we're in the midst of a release).
