### ISSUE TITLE
Vertx-web-client  setTryUseCompression error:decompression failure

### ISSUE THREAD

**Issue by shenzhou-6** [eclipse-vertx/vert.x#2920]
hello,
I use webclient request "http://api.bilibili.com/x/v1/dm/list.so?oid=87113082"

code :
```
val userAgent = "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
    val webClientOptions = webClientOptionsOf(userAgent=userAgent,followRedirects = true,tryUseCompression = true)
    val weblient = WebClient.create(vertx,webClientOptions)
val response = webClient
        .get(bilibiliApiUrl, "/x/v1/dm/list.so")
        .putHeader("Accept-Encoding","gzip, deflate")
        .addQueryParam("oid", cid.toString())
        .addQueryParam("page", i.toString())
        .sendAwait()
```
But there was an error：
```

io.netty.handler.codec.compression.DecompressionException: decompression failure
        at io.netty.handler.codec.compression.JdkZlibDecoder.decode(JdkZlibDecoder.java:230)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:325)
        at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:234)
        at io.netty.handler.codec.http.HttpContentDecoder.decodeContent(HttpContentDecoder.java:155)
        at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:147)
        at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:46)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.util.zip.DataFormatException: incorrect header check
        at java.base/java.util.zip.Inflater.inflateBytesBytes(Native Method)
        at java.base/java.util.zip.Inflater.inflate(Inflater.java:378)
        at io.netty.handler.codec.compression.JdkZlibDecoder.decode(JdkZlibDecoder.java:187)
        ... 38 more

```

**Comment by shenzhou-6** [comment]
when I chanage  
Constructor parm ZlibWrapper = ZlibWrapper.None for JdkZlibDecoder
The program is running normally

**Comment by shenzhou-6** [comment]
I found in class HttpContentDecompressor newContentDecoder in netty
Nothing is used in any situation.
ZlibWrapper.None
Maybe I should go to the netty question

**Comment by shenzhou-6** [comment]
sorry, I find Construction　param strict in netty class HttpContentDecompressor 
iif {@code true} use strict handling of deflate if used, otherwise handle it in a
more lenient fashion.

I think it should be used　strict=false .......

**Comment by shenzhou-6** [comment]
I think it should be lenient fashion in Webclient

**Comment by vietj** [comment]
can you provide a test for this in Vert.x HTTP test suite (`HttpTest`) as the fix seems easy ?

**Comment by shenzhou-6** [comment]
> i can try
