### ISSUE TITLE
NullPointerException on Clustered EventBus

### ISSUE THREAD

**Issue by AgnibhaBose** [eclipse-vertx/vert.x#2922]
```
[{}] 2019-04-23 18:17:34.404 ERROR [vert.x-eventloop-thread-0] VertxFactory:lambda$null$0:44 - VertX Exception ->
java.lang.NullPointerException: null
	at io.vertx.core.net.impl.NetServerImpl.lambda$connected$13(NetServerImpl.java:471) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.vertx.core.net.impl.NetServerImpl.connected(NetServerImpl.java:467) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.vertx.core.net.impl.NetServerImpl.access$200(NetServerImpl.java:54) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.vertx.core.net.impl.NetServerImpl$1.initChannel(NetServerImpl.java:216) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:472) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.vertx.core.net.impl.VertxEventLoopGroup.register(VertxEventLoopGroup.java:53) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:254) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

```

**Comment by tsegismont** [comment]
Can you provide a snippet?

**Comment by AgnibhaBose** [comment]
My Message Receiver:
```
public class Main {
    public static void main (String[] args) {
        HazelcastInstance hazelcastInstance = ServiceDependencyResolver.getDependency(HazelcastInstance.class);

        ClusterManager clusterManager = new HazelcastClusterManager(hazelcastInstance);
        VertxOptions   vertxOptions   = new VertxOptions().setClusterManager(clusterManager);

        Vertx.clusteredVertx(vertxOptions, (res) -> {
            if (res.succeeded()) {
                Vertx    vertx    = res.result();
                EventBus eventBus = vertx.eventBus();
                eventBus.consumer("address", message -> System.out.println("Received message = " + message));
            }
        });
    }
}
```

My Message Receiver: 
```
public class Main2 {
    public static void main (String[] args) {
        HazelcastInstance hazelcastInstance = ServiceDependencyResolver.getDependency(HazelcastInstance.class);

        ClusterManager clusterManager = new HazelcastClusterManager(hazelcastInstance);
        VertxOptions   vertxOptions   = new VertxOptions().setClusterManager(clusterManager);

        Vertx.clusteredVertx(vertxOptions, (res) -> {
            if (res.succeeded()) {
                Vertx vertx = res.result();
                vertx.setPeriodic(2000, handler -> {
                    EventBus eventBus = vertx.eventBus();
                    System.out.println("Publishing Message To The Event Bus");
                    eventBus.publish("address", "Some Message");
                });
            }
        });
    }
}
```

And the HazelCast Instance Provider:

        ```
Config        config                 = new Config();
        NetworkConfig hazelCastNetworkConfig = config.getNetworkConfig();
        config.setLiteMember(false);
        hazelCastNetworkConfig.setPort(configurationManager.getHazelcastPort());
        hazelCastNetworkConfig.setPortCount(50);
        hazelCastNetworkConfig.setPortAutoIncrement(true);

        JoinConfig joinConfig = hazelCastNetworkConfig.getJoin();

        MulticastConfig multicastConfig = joinConfig.getMulticastConfig();
        multicastConfig.setEnabled(false);

        AwsConfig awsConfig = joinConfig.getAwsConfig();
        awsConfig.setEnabled(false);

        TcpIpConfig hazelcastTCPConfig = joinConfig.getTcpIpConfig();

        String members = configurationManager.getHazelcastMembers();
        hazelcastTCPConfig.addMember(members);
        hazelcastTCPConfig.setEnabled(true);


        InterfacesConfig interfaces = hazelCastNetworkConfig.getInterfaces();
        interfaces.addInterface(configurationManager.getHazelcastMembers());

        instance = Hazelcast.newHazelcastInstance(config);
```

Vertx Version: **3.7.0**

**Comment by tsegismont** [comment]
Can you try with version 3.6.3? Trying to understand if it's a regression.

Given you don't use the TCP client directly I suppose this is from the clustered event bus implementation. Perhaps under some circumstances (yet to be determined) the returned connection obj is null.

**Comment by TechnicalRhino** [comment]
Tried with **3.5.0**.. And the issue is there.. I guess eventually 3.6.3 will also have it... But I will also give it a shot and will let you know

**Comment by tsegismont** [comment]
@TechnicalRhino thank you

**Comment by vietj** [comment]
@TechnicalRhino any news ?

**Comment by AgnibhaBose** [comment]
Same Exception Coming @vietj

**Comment by tsegismont** [comment]
@AgnibhaBose @TechnicalRhino there might be a race condition in the TCP server connection management. I've pushed this branch with a potential fix: https://github.com/tsegismont/vert.x/tree/patch-2922

Can you build this branch and try again? Thank you.

@vietj can you take a look at https://github.com/tsegismont/vert.x/commit/07c7a960a83fb0e4e7805920a6841598c02cfc3d ?

**Comment by vietj** [comment]
can we add such integration test to Hazelcast TCK or have something that reproduces with Vert.x and without Hazelcast ?

**Comment by vietj** [comment]
I'm assuming this is because cluster manager use execute blocking ?

**Comment by tsegismont** [comment]
>can we add such integration test to Hazelcast TCK or have something that reproduces with Vert.x and without Hazelcast ?

I haven't been able to reproduce with or whiteout Hazelcast unfortunately.

>I'm assuming this is because cluster manager use execute blocking ?

No. This happens on an event loop. I assume this happens when the TCP server created by `ClusteredEventBus` receives a connection from another node.
