### ISSUE TITLE
vertx  java.lang.IllegalStateException: Response is closed

### ISSUE THREAD

**Issue by Double2hao** [eclipse-vertx/vert.x#2944]
I don't know where catch this Exception,EveryWhere like 'response.end()'  i have added 'if (response.closed()||response.ended())'
The version of Vertx  is 3.7.0

Do anybody know how to fix this issue?

`May 13, 2019 2:42:50 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.IllegalStateException: Response is closed
	at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:575)
	at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:323)
	at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:312)
	at io.vertx.ext.web.impl.RoutingContextImplBase.unhandledFailure(RoutingContextImplBase.java:169)
	at io.vertx.ext.web.impl.RoutingContextImpl.checkHandleNoMatch(RoutingContextImpl.java:143)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:135)
	at io.vertx.ext.web.impl.RoutingContextImpl.doFail(RoutingContextImpl.java:483)
	at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:179)
	at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:172)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.lambda$new$3(BodyHandlerImpl.java:211)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleException(HttpServerRequestImpl.java:590)
	at io.vertx.core.http.impl.Http1xServerConnection.handleClosed(Http1xServerConnection.java:464)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelInactive$5(VertxHandler.java:164)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180)
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:164)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by vietj** [comment]
this will be improved in 3.7.1

**Comment by Double2hao** [comment]
> this will be improved in 3.7.1

Thank you for your reply！

**Comment by onurdemir55** [comment]
version 3.7.1 still have this case

**Comment by roottraveller** [comment]
Hi, I am getting this error too. have you figured out the cause and able to fix this?

**Comment by vietj** [comment]
@roottraveller upgrade to a more recent version, this does not happen anymore.

**Comment by roottraveller** [comment]
@vietj I have upgraded to `3.9.0` and still seeing this error. Any idea why? 
https://mvnrepository.com/artifact/io.vertx/vertx-core

**Comment by vietj** [comment]
can you show a stack trace ?

**Comment by roottraveller** [comment]
`io.vertx.core.eventbus.ReplyException: Timed out after waiting 30000(ms) for a reply. address: __vertx.reply.74, repliedAddress: looks.find
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$new$0(HandlerRegistration.java:77) ~[vertx-core-3.9.0.jar!/:3.9.0]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:923) [vertx-core-3.9.0.jar!/:3.9.0]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:887) [vertx-core-3.9.0.jar!/:3.9.0]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369) [vertx-core-3.9.0.jar!/:3.9.0]
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43) [vertx-core-3.9.0.jar!/:3.9.0]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232) [vertx-core-3.9.0.jar!/:3.9.0]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:224) [vertx-core-3.9.0.jar!/:3.9.0]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:913) [vertx-core-3.9.0.jar!/:3.9.0]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.23.Final.jar!/:4.1.23.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125) [netty-common-4.1.23.Final.jar!/:4.1.23.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.23.Final.jar!/:4.1.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.23.Final.jar!/:4.1.23.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.23.Final.jar!/:4.1.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-common-4.1.23.Final.jar!/:4.1.23.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.23.Final.jar!/:4.1.23.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
2020-04-12 21:30:25,316  WARN BlockedThreadChecker::(vertx-blocked-thread-checker) - Thread Thread[LooksVerticle-worker-pool-12,5,main]=Thread[LooksVerticle-worker-pool-12,5,main] has been blocked for 62037 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
	at java.util.HashMap.hash(HashMap.java:339) ~[?:1.8.0_181]
	at java.util.HashMap.get(HashMap.java:557) ~[?:1.8.0_181]
	at com.myntra.strategy.looks.WeightsRankingStrategy.getTotalCount(WeightsRankingStrategy.java:142) ~[classes!/:?]`

**Comment by roottraveller** [comment]
@vietj 
```io.vertx.core.eventbus.ReplyException: Timed out after waiting 30000(ms) for a reply. address: __vertx.reply.74, repliedAddress: looks.find
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$new$0(HandlerRegistration.java:77) ~[vertx-core-3.9.0.jar!/:3.9.0]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:923) [vertx-core-3.9.0.jar!/:3.9.0]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:887) [vertx-core-3.9.0.jar!/:3.9.0]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369) [vertx-core-3.9.0.jar!/:3.9.0]
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43) [vertx-core-3.9.0.jar!/:3.9.0]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232) [vertx-core-3.9.0.jar!/:3.9.0]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:224) [vertx-core-3.9.0.jar!/:3.9.0]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:913) [vertx-core-3.9.0.jar!/:3.9.0]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.23.Final.jar!/:4.1.23.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125) [netty-common-4.1.23.Final.jar!/:4.1.23.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.23.Final.jar!/:4.1.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.23.Final.jar!/:4.1.23.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.23.Final.jar!/:4.1.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-common-4.1.23.Final.jar!/:4.1.23.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.23.Final.jar!/:4.1.23.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
2020-04-12 21:30:25,316  WARN BlockedThreadChecker::(vertx-blocked-thread-checker) - Thread Thread[LooksVerticle-worker-pool-12,5,main]=Thread[LooksVerticle-worker-pool-12,5,main] has been blocked for 62037 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
	at java.util.HashMap.hash(HashMap.java:339) ~[?:1.8.0_181]
	at java.util.HashMap.get(HashMap.java:557) ~[?:1.8.0_181]
	at com.myntra.strategy.looks.WeightsRankingStrategy.getTotalCount(WeightsRankingStrategy.java:142) ~[classes!/:?]```
