### ISSUE TITLE
Http server slow start up 

### ISSUE THREAD

**Issue by aygalinc** [eclipse-vertx/vert.x#3012]
Hi,

I work on a constraint device and start a webserver seems quite long. 
I check some value and : 
* Starting vert.x (version 3.7.1) takes and execute a task on context take 6 seconds. 
* Starting vert.x & deploy a verticle which deploy a Http server take 13 seconds. 

The webserver is deployed with : 

```
@Override
    public void start() {
      vertx.createHttpServer().requestHandler(ignored ->{}).listen(8081,ar -> {
        System.out.println("Hello from vert.x after " + (System.currentTimeMillis()- start));
      });
    }
```

I got some stack trace that seems to indicate that event loop block at some point but they are not the same from one launch to another : 

```
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2191 ms, time limit is 2000 ms
Jul 01, 2019 4:45:13 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3190 ms, time limit is 2000 ms
Jul 01, 2019 4:45:14 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4348 ms, time limit is 2000 ms
Jul 01, 2019 4:45:15 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 5348 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.netty.resolver.dns.DnsNameResolver.<clinit>(DnsNameResolver.java:131)
	at io.netty.resolver.dns.DnsNameResolverBuilder.<init>(DnsNameResolverBuilder.java:49)
	at io.netty.resolver.dns.DnsAddressResolverGroup.<init>(DnsAddressResolverGroup.java:64)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1$1.<init>(DnsResolverProvider.java:137)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1.newResolver(DnsResolverProvider.java:137)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
	at io.vertx.core.impl.AddressResolver.resolveHostname(AddressResolver.java:82)
	at io.vertx.core.impl.VertxImpl.resolveAddress(VertxImpl.java:803)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.doBind(AsyncResolveConnectHelper.java:82)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:304)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:190)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:186)
	at com.se.gxl.forum.deployment.TestMain$DeployerVerticle.start(TestMain.java:71)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
	at io.vertx.core.impl.DeploymentManager$$Lambda$8/8582895.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$9/16818525.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Jul 01, 2019 4:45:16 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 6349 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at java.util.zip.Inflater.inflateBytes(Native Method)
	at java.util.zip.Inflater.inflate(Inflater.java:259)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:152)
	at sun.misc.Resource.getBytes(Resource.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:463)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.netty.buffer.ByteBufAllocator.<clinit>(ByteBufAllocator.java:24)
	at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:58)
	at io.netty.channel.socket.DefaultDatagramChannelConfig.<init>(DefaultDatagramChannelConfig.java:54)
	at io.netty.channel.socket.nio.NioDatagramChannelConfig.<init>(NioDatagramChannelConfig.java:117)
	at io.netty.channel.socket.nio.NioDatagramChannel.<init>(NioDatagramChannel.java:149)
	at io.netty.channel.socket.nio.NioDatagramChannel.<init>(NioDatagramChannel.java:116)
	at io.vertx.core.net.impl.transport.Transport.datagramChannel(Transport.java:150)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1.lambda$newResolver$0(DnsResolverProvider.java:136)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1$$Lambda$15/26381689.newChannel(Unknown Source)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320)
	at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:234)
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:395)
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:430)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1$1.newNameResolver(DnsResolverProvider.java:183)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:94)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:79)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1.newResolver(DnsResolverProvider.java:187)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
	at io.vertx.core.impl.AddressResolver.resolveHostname(AddressResolver.java:82)
	at io.vertx.core.impl.VertxImpl.resolveAddress(VertxImpl.java:803)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.doBind(AsyncResolveConnectHelper.java:82)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:304)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:190)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:186)
	at com.se.gxl.forum.deployment.TestMain$DeployerVerticle.start(TestMain.java:71)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
	at io.vertx.core.impl.DeploymentManager$$Lambda$8/8582895.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$9/16818525.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Hello from vert.x after 13043
```

another : 
```
Jul 01, 2019 4:42:30 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2187 ms, time limit is 2000 ms
Jul 01, 2019 4:42:31 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3187 ms, time limit is 2000 ms
Jul 01, 2019 4:42:32 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4277 ms, time limit is 2000 ms
Jul 01, 2019 4:42:33 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 5277 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.netty.handler.codec.dns.DnsRecordDecoder.<clinit>(DnsRecordDecoder.java:29)
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.<init>(DatagramDnsResponseDecoder.java:43)
	at io.netty.resolver.dns.DnsNameResolver.<clinit>(DnsNameResolver.java:160)
	at io.netty.resolver.dns.DnsNameResolverBuilder.<init>(DnsNameResolverBuilder.java:49)
	at io.netty.resolver.dns.DnsAddressResolverGroup.<init>(DnsAddressResolverGroup.java:64)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1$1.<init>(DnsResolverProvider.java:137)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1.newResolver(DnsResolverProvider.java:137)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
	at io.vertx.core.impl.AddressResolver.resolveHostname(AddressResolver.java:82)
	at io.vertx.core.impl.VertxImpl.resolveAddress(VertxImpl.java:803)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.doBind(AsyncResolveConnectHelper.java:82)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:304)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:190)
	at com.se.gxl.forum.deployment.TestMain$DeployerVerticle.start(TestMain.java:71)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
	at io.vertx.core.impl.DeploymentManager$$Lambda$8/8582895.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$9/16818525.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Jul 01, 2019 4:42:34 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 6277 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at java.lang.reflect.Proxy.<clinit>(Proxy.java:240)
	at sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:305)
	at sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:303)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.annotation.AnnotationParser.annotationForMap(AnnotationParser.java:303)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:293)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseSelectAnnotations(AnnotationParser.java:101)
	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:145)
	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:266)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.createAnnotationData(Class.java:3526)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.Class.isAnnotationPresent(Class.java:3425)
	at io.netty.channel.ChannelHandlerAdapter.isSharable(ChannelHandlerAdapter.java:57)
	at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:599)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:202)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:385)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:372)
	at io.netty.bootstrap.Bootstrap.init(Bootstrap.java:265)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:321)
	at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:234)
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:395)
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:430)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1$1.newNameResolver(DnsResolverProvider.java:183)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:94)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:79)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1.newResolver(DnsResolverProvider.java:187)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
	at io.vertx.core.impl.AddressResolver.resolveHostname(AddressResolver.java:82)
	at io.vertx.core.impl.VertxImpl.resolveAddress(VertxImpl.java:803)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.doBind(AsyncResolveConnectHelper.java:82)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:304)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:190)
	at com.se.gxl.forum.deployment.TestMain$DeployerVerticle.start(TestMain.java:71)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
	at io.vertx.core.impl.DeploymentManager$$Lambda$8/8582895.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$9/16818525.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Hello from vert.x after 12938

```

Does this value seems reasonnable or something is realy blocking the event loop ?

**Comment by tsegismont** [comment]
The blocked thread checker logs warnings not only when a blocking API is
invoked, but when code execution takes too much time.

It seems your device is very much constrained. How much memory do you have
available?

Le lun. 1 juil. 2019 à 16:54, Colin Aygalinc <notifications@github.com> a
écrit :

**Comment by vietj** [comment]
you can avoid the warnings by setting a longer checker period.

one solution would be also to unzip the vertx jars in a directory and use it as a classpath, that would save memory and speed up boot time.

**Comment by aygalinc** [comment]
@tsegismont : 
The total memory of my platform is 256M. 
But I cannot use the whole RAM.  
But I try to launch with java -Xmx64M -Xms64M or java -Xmx128M -Xms128M and I not see a big difference (around 600 ms in average).

I will try @vietj advice and see if it is improving things.
It is just that i see a lot of DNS resolving thing in log and i'm wondering if it's normal that it takes such amount of time.
  
Thx for the feedback.

**Comment by tsegismont** [comment]
You should be able to start with 64M heap.

What do you mean with a lot of DNS resolving?

Le mar. 2 juil. 2019 à 09:34, Colin Aygalinc <notifications@github.com> a
écrit :

**Comment by aygalinc** [comment]
The logs are not very consistent for each launch, but as you said the blocked thread checker prints stack trace when code execution takes too much time so it must be a slow execution and not a blocking point. 

But the common part in logging is that I see the io.netty.resolver.dns.DnsNameResolver or Vertx resolver always in the stack trace. That s all :)

**Comment by tsegismont** [comment]
I looked at your logs again. Indeed, the stack traces show DnsNameResolver
but this is not where the time seems to be spent. The time seems to be
spent in loading class files and inspecting bytecode.

What is the media for the app files storage? Is it very slow on your device?

Julien seemed to think it could also be the CPU that has hard time
uncompressing the JAR files.

Le mar. 2 juil. 2019 à 09:59, Colin Aygalinc <notifications@github.com> a
écrit :

**Comment by aygalinc** [comment]
Decompress the jar file and use it directly does not triggered any performance improvement. 

In all cases thx for the hints & feedbacks.

**Comment by aygalinc** [comment]
I try to run Netty Snoop server (https://netty.io/4.0/xref/io/netty/example/http/snoop/package-summary.html) on my target and it starts in 6 seconds.

**Comment by vietj** [comment]
how long to have the JVM up and running printing hello world ?

**Comment by aygalinc** [comment]
My testbench : 
* I use Hotspot Java 8 SE embeded arm32 Hard Float in cp3 with Class Data Sharing. 

Apps that just print Hello World : 
**554,8200684** ms

I deploy a verticle that simply do (start value is compute after main) : 
``` 
@Override
    public void start() {
      vertx.createHttpServer().requestHandler(ignored ->{}).listen(8081,ar -> {
        System.out.println("Hello from vert.x after " + (System.currentTimeMillis()- start));
      });
    } 
```
On 10 launch, It takes **10647** ms .
I did not compute the first response time that can take a little bit longer due to lazy thing I think. 

On Netty exemple, I just replace the line after  : 
````
   Channel ch = b.bind(PORT).sync().channel();
````

by : 
````
        System.err.println("Open your web browser and navigate to " +
            (SSL? "https" : "http") + "://127.0.0.1:" + PORT + '/' + " at " + (System.currentTimeMillis()- start));
````

The launch time is **3264** .

**Comment by vietj** [comment]
it looks like your JVM is very slow

**Comment by aygalinc** [comment]
@vietj : Yes, the JVM seems quite slow :) 
But after digging a little bit, I find that the expensive operation that explained the major difference between vert.x & netty use case was in the SSLHelper class at : 
https://github.com/eclipse-vertx/vert.x/blob/e750004270eb608c64fcd33d4bb006978eda8afd/src/main/java/io/vertx/core/net/impl/SSLHelper.java#L104-L115

the getInstance operation takes around 6 seconds... 

I'm wondering why this part is in a static initializer because I don't start an HTTPS server. Is this static initializer really necessary in non SSL case ?

**Comment by vietj** [comment]
that's a valid point, I think that when SSL is not enabled we should not use SSL Helper instead of creating an SSLHelper that does nothing.

I can do a branch where that happens and you can check on your side this branch to see if it makes any difference ? WDYT ?

**Comment by aygalinc** [comment]
Yes for sure !

**Comment by vietj** [comment]
I'll keep you posted here

**Comment by aygalinc** [comment]
On my side, I have patch the SSL (just remove the try catch) and performances are close to plain netty.

**Comment by vietj** [comment]
you can try this https://github.com/vietj/vert.x/tree/dont-instantiate-ssl-helper-in-http-server ? (it is only for http server)

**Comment by vietj** [comment]
it seems that loading JDK SSL is what is costly

**Comment by aygalinc** [comment]
I will give you feedback on monday.

**Comment by aygalinc** [comment]
Your fix definitely improves the start up in non ssl case.

**Comment by vietj** [comment]
do you have something comparable with bare netty ?

**Comment by aygalinc** [comment]
Here is the number : 
* Bare netty : 6500 ms
* Vertx http server: 9500 ms (previously 14500 ms)

So definitely better but not equal to bare netty.
But as stated the JVM seems kind of slow in classloading and object instantiation. But I will keep searching if some leads can be explored to improve start up and be as close as possible to netty. 
Does vertx team has quantified the overhead introduced by vert.x compare to bare netty ?

**Comment by vietj** [comment]
it depends what you measure I guess. For runtime server/client (HTTP / TCP) there is almost no overhead, for startup time we haven't investigated so there is a little and in your case (slow JVM) it makes a larger difference than in most common cases. Usually we do our best to have as little overhead as possible. Keep us informed of your findings, I think in 3.8 we will at least have this patch for HTTP. For plain TCP it seems harder to lazy create the SSL Helper because of StartTLS (although not impossible but requires some work)

**Comment by vietj** [comment]
I will push another patch today that makes lazy loading different relying on Java classloading to make things simpler, is that something you can validate look at today ?

**Comment by vietj** [comment]
@aygalinc would you mind trying the same branch which has been updated with a lazy loading of the cipher suite that should work for all IOs.

**Comment by aygalinc** [comment]
For sure.

**Comment by aygalinc** [comment]
Seems ok on my side and code looks good !
Nice improvement.

**Comment by vietj** [comment]
alright thanks for the feedback, I'll close this issue in the meantime and if you have other findings don't hesitate to discuss again
