### ISSUE TITLE
Test failures on Ubuntu 16.04 on X86 architecture

### ISSUE THREAD

**Issue by SantoshMagdum** [eclipse-vertx/vert.x#3051]
I am trying to build Eclipse Vert.x package master branch on Ubuntu 16.04 platform on X86 architecture. I could build the package but I am getting around 8 test case failures.

These are the steps that I followed -
	- Installed Java version: 1.8.0
	- Installed Apache Maven 3.6.0
	- Cloned the master copy of eclipse-vertx git code base.
	- Triggered the build

I am currently trying to look at the logs to investigate the failures, however any pointers on any additional dependencies / configuration required for these, which I may be missing would be of great help.

Appreciate your help in advance.

Below are the test cases which are failing. Please let me if I should share more specific details.

	io.vertx.core.DeploymentTest.txt:Tests run: 76, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 38.469 sec <<< FAILURE! - in io.vertx.core.DeploymentTest
	io.vertx.core.file.FileSystemTest.txt:Tests run: 101, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.874 sec <<< FAILURE! - in io.vertx.core.file.FileSystemTest
	io.vertx.core.http.Http1xTest.txt:Tests run: 404, Failures: 1, Errors: 1, Skipped: 1, Time elapsed: 214.646 sec <<< FAILURE! - in io.vertx.core.http.Http1xTest
	io.vertx.core.http.Http2Test.txt:Tests run: 293, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 214.5 sec <<< FAILURE! - in io.vertx.core.http.Http2Test
	io.vertx.core.net.NetTest.txt:Tests run: 125, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 31.268 sec <<< FAILURE! - in io.vertx.core.net.NetTest

**Comment by vietj** [comment]
can you provide more details ?

**Comment by SantoshMagdum** [comment]
We had also setup a travis job to build eclipse vert.x on ppc64le. We see similar test case failures on ppc64le as well. Please note, I had removed the errors related to open ssl on my local ppc64le build.
Locally I had built ‘Hawtnji’ and ‘netty-tcnative-master’ on ppc64le and still building dependent ‘netty’ package.

Below is the travis ppc64le build job log -
                https://travis-ci.org/SantoshMagdum/vert.x/jobs/566829629

Below are the exact test case failures on Ubuntu intel X86 platform. These tests also fails on ppc64le in addition to netty package dependency errors.

-------------------------------------------------------------------------------
Test set: io.vertx.core.DeploymentTest
-------------------------------------------------------------------------------
Tests run: 76, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 38.469 sec <<< FAILURE! - in io.vertx.core.DeploymentTest
testIsolationGroup1(io.vertx.core.DeploymentTest)  Time elapsed: 0.114 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.vertx.test.core.AsyncTestBase.assertEquals(AsyncTestBase.java:241)
        at io.vertx.core.DeploymentTest.lambda$testIsolationGroup1$101(DeploymentTest.java:1034)

testIsolationGroupSameGroup(io.vertx.core.DeploymentTest)  Time elapsed: 10.072 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.vertx.test.core.AsyncTestBase.assertTrue(AsyncTestBase.java:378)
        at io.vertx.test.core.AsyncTestBase.awaitLatch(AsyncTestBase.java:602)
        at io.vertx.test.core.AsyncTestBase.awaitLatch(AsyncTestBase.java:598)
        at io.vertx.core.DeploymentTest.testIsolationGroup(DeploymentTest.java:1513)
        at io.vertx.core.DeploymentTest.testIsolationGroupSameGroup(DeploymentTest.java:1057)

testIsolationGroupDifferentGroup(io.vertx.core.DeploymentTest)  Time elapsed: 10.062 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.vertx.test.core.AsyncTestBase.assertTrue(AsyncTestBase.java:378)
        at io.vertx.test.core.AsyncTestBase.awaitLatch(AsyncTestBase.java:602)
        at io.vertx.test.core.AsyncTestBase.awaitLatch(AsyncTestBase.java:598)
        at io.vertx.core.DeploymentTest.testIsolationGroup(DeploymentTest.java:1513)
        at io.vertx.core.DeploymentTest.testIsolationGroupDifferentGroup(DeploymentTest.java:1069)

testIsolationGroupSameGroupWildcard(io.vertx.core.DeploymentTest)  Time elapsed: 10.082 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.vertx.test.core.AsyncTestBase.assertTrue(AsyncTestBase.java:378)
        at io.vertx.test.core.AsyncTestBase.awaitLatch(AsyncTestBase.java:602)
        at io.vertx.test.core.AsyncTestBase.awaitLatch(AsyncTestBase.java:598)
        at io.vertx.core.DeploymentTest.testIsolationGroup(DeploymentTest.java:1513)
        at io.vertx.core.DeploymentTest.testIsolationGroupSameGroupWildcard(DeploymentTest.java:1063)

-------------------------------------------------------------------------------
Test set: io.vertx.core.file.FileSystemTest
-------------------------------------------------------------------------------
Tests run: 101, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.874 sec <<< FAILURE! - in io.vertx.core.file.FileSystemTest
testChownToRootFails(io.vertx.core.file.FileSystemTest)  Time elapsed: 0.037 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.vertx.test.core.AsyncTestBase.assertTrue(AsyncTestBase.java:378)
        at io.vertx.core.file.FileSystemTest.lambda$testChownFails$146(FileSystemTest.java:528)

-------------------------------------------------------------------------------
Test set: io.vertx.core.http.Http1xTest
-------------------------------------------------------------------------------
Tests run: 404, Failures: 1, Errors: 1, Skipped: 1, Time elapsed: 214.646 sec <<< FAILURE! - in io.vertx.core.http.Http1xTest
testCloseTheConnectionAfterResetBeforeKeepAliveResponseReceived(io.vertx.core.http.Http1xTest)  Time elapsed: 120.114 sec  <<< ERROR!
java.lang.IllegalStateException: Timed out in waiting for test complete
        at io.vertx.test.core.AsyncTestBase.await(AsyncTestBase.java:133)
        at io.vertx.test.core.AsyncTestBase.await(AsyncTestBase.java:121)
        at io.vertx.core.http.Http1xTest.testCloseTheConnectionAfterResetBeforeResponseReceived(Http1xTest.java:3478)
        at io.vertx.core.http.Http1xTest.testCloseTheConnectionAfterResetBeforeKeepAliveResponseReceived(Http1xTest.java:3383)

testListenInvalidPort(io.vertx.core.http.Http1xTest)  Time elapsed: 0.136 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertFalse(Assert.java:64)
        at org.junit.Assert.assertFalse(Assert.java:74)
        at io.vertx.test.core.AsyncTestBase.assertFalse(AsyncTestBase.java:214)
        at io.vertx.test.core.AsyncTestBase.lambda$onFailure$0(AsyncTestBase.java:592)
        at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:287)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:178)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:40)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

-------------------------------------------------------------------------------
Test set: io.vertx.core.http.Http2Test
-------------------------------------------------------------------------------
Tests run: 293, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 214.5 sec <<< FAILURE! - in io.vertx.core.http.Http2Test
testListenInvalidPort(io.vertx.core.http.Http2Test)  Time elapsed: 0.137 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertFalse(Assert.java:64)
        at org.junit.Assert.assertFalse(Assert.java:74)
        at io.vertx.test.core.AsyncTestBase.assertFalse(AsyncTestBase.java:214)
        at io.vertx.test.core.AsyncTestBase.lambda$onFailure$0(AsyncTestBase.java:592)
        at io.vertx.core.http.impl.HttpServerImpl.lambda$null$5(HttpServerImpl.java:287)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:178)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:40)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

-------------------------------------------------------------------------------
Test set: io.vertx.core.net.NetTest
-------------------------------------------------------------------------------
Tests run: 125, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 31.268 sec <<< FAILURE! - in io.vertx.core.net.NetTest
testListenInvalidPort(io.vertx.core.net.NetTest)  Time elapsed: 0.043 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.vertx.test.core.AsyncTestBase.assertTrue(AsyncTestBase.java:378)
        at io.vertx.core.net.NetTest.lambda$testListenInvalidPort$59(NetTest.java:917)

**Comment by vietj** [comment]
what is your JDK ?

**Comment by SantoshMagdum** [comment]
JDK version is 1.8

**Comment by vietj** [comment]
which version of Vert.x ? it is not possible to map your stack traces to actual code

**Comment by SantoshMagdum** [comment]
Hi Julien,
Thanks for helping me in resolving the build issues. 
On Ubuntu 16.04 X86, I had cloned from below master branch -
https://github.com/eclipse-vertx/vert.x
$ git describe
4.0.0-milestone1-6-g6ffd71f
JAVA Version - openjdk version "1.8.0_222"
OpenSSL Version - OpenSSL 1.0.2g  1 Mar 2016
mvn  -  Apache Maven 3.6.0
I had then just triggered the build.
Kindly please let me know any other specific information I should share.


Additionally, I am also trying to build on RHEL 7.6 ppc64le and I see SSL issues reported during the build. I am still looking into.
Please suggest which specific version/branch I should clone to build below components –

Eclipse Vert.x 
netty 
netty-tcnative
hawtnji
openssl
JDK

**Comment by vietj** [comment]
I do have access to an ubuntu machine, I will try on this machine to see what I can correlate.

Do you see same issues with 3.8 branch ?

**Comment by vietj** [comment]
a few comments

- the file system test : I think this test fails because of some permission issue
- invalid port test : same than previous
- testCloseTheConnectionAfterResetBeforeKeepAliveResponseReceived : this is a test that might be incorrect and fails sometimes depending on race conditions
- deployment test : I don't know they should not fail, I think it should come from JDK but I am not sure

**Comment by SantoshMagdum** [comment]
Thanks for suggesting the probable failure cases. I rebuilt the package in a separate user environment and now I am getting below single error.
Could it be any specific JAVA environment issues or should I need to upgrade JDK.


-------------------------------------------------------------------------------
Test set: io.vertx.core.DeploymentTest
-------------------------------------------------------------------------------
Tests run: 76, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 36.8 sec <<< FAILURE! - in io.vertx.core.DeploymentTest
testIsolationGroup1(io.vertx.core.DeploymentTest)  Time elapsed: 0.056 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at io.vertx.test.core.AsyncTestBase.assertEquals(AsyncTestBase.java:241)
        at io.vertx.core.DeploymentTest.lambda$testIsolationGroup1$101(DeploymentTest.java:1034)

testIsolationGroupSameGroup(io.vertx.core.DeploymentTest)  Time elapsed: 10.03 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.vertx.test.core.AsyncTestBase.assertTrue(AsyncTestBase.java:378)
        at io.vertx.test.core.AsyncTestBase.awaitLatch(AsyncTestBase.java:602)
        at io.vertx.test.core.AsyncTestBase.awaitLatch(AsyncTestBase.java:598)
        at io.vertx.core.DeploymentTest.testIsolationGroup(DeploymentTest.java:1513)
        at io.vertx.core.DeploymentTest.testIsolationGroupSameGroup(DeploymentTest.java:1057)

testIsolationGroupDifferentGroup(io.vertx.core.DeploymentTest)  Time elapsed: 10.029 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.vertx.test.core.AsyncTestBase.assertTrue(AsyncTestBase.java:378)
        at io.vertx.test.core.AsyncTestBase.awaitLatch(AsyncTestBase.java:602)
        at io.vertx.test.core.AsyncTestBase.awaitLatch(AsyncTestBase.java:598)
        at io.vertx.core.DeploymentTest.testIsolationGroup(DeploymentTest.java:1513)
        at io.vertx.core.DeploymentTest.testIsolationGroupDifferentGroup(DeploymentTest.java:1069)

testIsolationGroupSameGroupWildcard(io.vertx.core.DeploymentTest)  Time elapsed: 10.024 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.vertx.test.core.AsyncTestBase.assertTrue(AsyncTestBase.java:378)
        at io.vertx.test.core.AsyncTestBase.awaitLatch(AsyncTestBase.java:602)
        at io.vertx.test.core.AsyncTestBase.awaitLatch(AsyncTestBase.java:598)
        at io.vertx.core.DeploymentTest.testIsolationGroup(DeploymentTest.java:1513)
        at io.vertx.core.DeploymentTest.testIsolationGroupSameGroupWildcard(DeploymentTest.java:1063)

**Comment by vietj** [comment]
yes this one looks weird and I can't explain it.

can you modify the test and using this:

Replace `testIsolationGroup1()` in `DeploymentTest` with

```java
   @Test
  public void testIsolationGroup1() throws Exception {
    boolean expectedSuccess = Thread.currentThread().getContextClassLoader() instanceof URLClassLoader;
    List<String> isolatedClasses = Arrays.asList(TestVerticle.class.getCanonicalName());
    try {
      vertx.deployVerticle("java:" + TestVerticle.class.getCanonicalName(),
        new DeploymentOptions().setIsolationGroup("somegroup").setIsolatedClasses(isolatedClasses), ar -> {
          assertTrue(ar.succeeded());
          System.out.println(TestVerticle.instanceCount.hashCode());
          assertEquals(0, TestVerticle.instanceCount.get());
          testComplete();
      });
      assertTrue(expectedSuccess);
      await();
    } catch (IllegalStateException e) {
      assertFalse(expectedSuccess);
    }
  }
```

replace the `start()` method of `TestVerticle` with

```java
  @Override
  public void start() throws Exception {
    processArgs = context.processArgs();
    conf = context.config();
//    if (Thread.currentThread().getContextClassLoader() != getClass().getClassLoader()) {
//      throw new IllegalStateException("Wrong tccl!");
//    }
    System.out.println("using " + instanceCount.hashCode());
    vertx.eventBus().send("testcounts",
      new JsonObject().put("deploymentID", context.deploymentID()).put("count", instanceCount.incrementAndGet()));
  }
```

**Comment by vietj** [comment]
normally the hashcode should be different

**Comment by SantoshMagdum** [comment]
Hi Julien,

I tried to replace the above code but did not get luck. I still get test case failures for "Test set: io.vertx.core.DeploymentTest" on Ubuntu : 16.04.
In parallel I am trying to build on rhel ppc64le

**Comment by vietj** [comment]
actually I wanted you to show what was printed on the console by the hashcode of the java object (a number) twice to see if that's the same object or not

**Comment by SantoshMagdum** [comment]
Hi Julien,
Many thanks for the pointers. I am able to build and run test cases on ubuntu and rhel 7.6 on ppc64le.
But I had to bypass the test cases for 'netty' dependency package on ppc64le as test cases for below sub moduloes from netty package were failing.
    •	handler
    •	resolver
    •	testsuit
    •	transport-native-epoll
Also netty tests need conscript which has dependency on boring SSL and android sdk.

Do eclipse vert-x consumes these modules? If these modules are not used in eclipse then can we skip the test cases for these sub-components?
Please suggest.

**Comment by SantoshMagdum** [comment]
I had got netty package build on ppc64le and with that eclipse vert-x also was built.
Closing the ticket.
