### ISSUE TITLE
Calling unregister on an event bus handler causes an NullPointerException in the metrics code

### ISSUE THREAD

**Issue by doctorpangloss** [eclipse-vertx/vert.x#3053]
Related to #2892 

vertx 3.8.0 **not clustered**

Exception:

```
java.lang.NullPointerException: null
        at io.vertx.ext.dropwizard.impl.EventBusMetricsImpl$HandlerMetric.remove(EventBusMetricsImpl.java:265)
        at io.vertx.ext.dropwizard.impl.EventBusMetricsImpl.handlerUnregistered(EventBusMetricsImpl.java:127)
        at io.vertx.ext.dropwizard.impl.EventBusMetricsImpl.handlerUnregistered(EventBusMetricsImpl.java:34)
        at io.vertx.core.eventbus.impl.HandlerRegistration.doUnregister(HandlerRegistration.java:187)
        at io.vertx.core.eventbus.impl.HandlerRegistration.unregister(HandlerRegistration.java:140)

...
```

The metrics options:
```
		return new DropwizardMetricsOptions().setEnabled(true)
				.addMonitoredEventBusHandler(new Match().setValue("\\w+/.*").setType(MatchType.REGEX));
```

This is a sometimes-issue.

My work around at the moment is to disable metrics since I really need this consumer to close.

**Comment by vietj** [comment]
can you provide a reproducer ?

**Comment by doctorpangloss** [comment]
I've been trying outside the actual environment :) I'll update this when I succeed.

**Comment by vietj** [comment]
thanks

**Comment by vietj** [comment]
it should be fixed by https://github.com/eclipse-vertx/vert.x/issues/3054
