### ISSUE TITLE
3.7.1 version still  "java.lang.IllegalStateException: Response is closed"

### ISSUE THREAD

**Issue by onurdemir55** [eclipse-vertx/vert.x#3061]
issue #2944  is written that it will be handled in version vertx 3.7.1 but still have this case.

May be we should check response isClosed() or catch the exception and swallow it. Or is there any suggestions ? 

What was the improvement for this case in version 3.7.1 ? 

`java.lang.IllegalStateException: Response is closed
	at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:617)
	at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:157)
	at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:54)
	at com.cloud.transaction.api.repository.TransactionRepository.lambda$send$6(TransactionRepository.java:100)
	at com.mongodb.async.client.MongoIterableImpl$2$2.onResult(MongoIterableImpl.java:113)
	at com.mongodb.async.client.MongoIterableImpl$2$2.onResult(MongoIterableImpl.java:107)
	at com.mongodb.async.client.MongoIterableImpl$4.onResult(MongoIterableImpl.java:182)
	at com.mongodb.async.client.MongoIterableImpl$4.onResult(MongoIterableImpl.java:177)
	at com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:139)
	at com.mongodb.operation.AsyncQueryBatchCursor.next(AsyncQueryBatchCursor.java:99)
	at com.mongodb.async.client.MongoIterableImpl.loopCursor(MongoIterableImpl.java:177)
	at com.mongodb.async.client.MongoIterableImpl.access$000(MongoIterableImpl.java:39)
	at com.mongodb.async.client.MongoIterableImpl$4.onResult(MongoIterableImpl.java:188)
	at com.mongodb.async.client.MongoIterableImpl$4.onResult(MongoIterableImpl.java:177)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.operation.AsyncQueryBatchCursor.handleGetMoreQueryResult(AsyncQueryBatchCursor.java:272)
	at com.mongodb.operation.AsyncQueryBatchCursor.access$300(AsyncQueryBatchCursor.java:55)
	at com.mongodb.operation.AsyncQueryBatchCursor$CommandResultSingleResultCallback.onResult(AsyncQueryBatchCursor.java:303)
	at com.mongodb.operation.AsyncQueryBatchCursor$CommandResultSingleResultCallback.onResult(AsyncQueryBatchCursor.java:277)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:207)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:102)
	at com.mongodb.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:458)
	at com.mongodb.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:110)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:381)
	at com.mongodb.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:359)
	at com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:651)
	at com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:618)
	at com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:487)
	at com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:484)
	at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:233)
	at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:216)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
	at sun.nio.ch.Invoker.invokeDirect(Invoker.java:157)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:553)
	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:276)
	at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:297)
	at com.mongodb.connection.AsynchronousSocketChannelStream.readAsync(AsynchronousSocketChannelStream.java:128)
	at com.mongodb.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:484)
	at com.mongodb.connection.InternalStreamConnection.access$1100(InternalStreamConnection.java:74)
	at com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:608)
	at com.mongodb.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:593)
	at com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:487)
	at com.mongodb.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:484)
	at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:233)
	at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:216)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:430)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)"`

**Comment by vietj** [comment]
we changed this for the end/write methods not putHeader that's the reason

**Comment by vietj** [comment]
so I guess we should improve it

**Comment by onurdemir55** [comment]
our response code like this.

`routingContext.response()
                                .putHeader("content-type", "application/json")
                                .setStatusCode(HttpResponseStatus.OK.code())
                                .end(Json.encodePrettily(result));`

**Comment by vietj** [comment]
can you set the header eagerly before the calling end ?

**Comment by ggetv** [comment]
using 3.8.0 and seeing the same error, we have an executeBlocking block that calls another backend and generate response. Since we also have a timeout handler, sometimes the timeout will kick in and send the response before the executeBlocking finishes and sends back response.

So, how do we check? Tried HttpServerResponse.closed(), ended(), not really working. Only way seems to put a try...catch... block.
