### ISSUE TITLE
null value header getting into request and validateHeaderValue throwing NullPointerException

### ISSUE THREAD

**Issue by lbroman** [eclipse-vertx/vert.x#3116]
Vert.x version 3.8.1

I have a problem with a proxied request with additional headers which somehow allows a header with null value to get into the request and subsequently the validateHeaderValue will throw a nullpointerexception which is only handled in the vertx exception handler.

Some code
`
proxyRequest.putHeaders(clientRequest.headers());
proxyRequest.putHeader("X-Test",null);

clientRequest.bodyHandler(bb -> {
	proxyRequest.sendBuffer(bb, ar -> {
`

The proxy is mapping headers from clientRequest to the proxyRequest and adding an null header (our fault). Vertx will later trigger an exception.

`
java.lang.NullPointerException
        at io.vertx.core.http.impl.HttpUtils.validateHeaderValue(HttpUtils.java:685)
        at io.vertx.core.http.impl.HttpUtils.validateHeader(HttpUtils.java:673)
        at io.vertx.core.http.impl.headers.VertxHttpHeaders.add0(VertxHttpHeaders.java:522)
        at io.vertx.core.http.impl.headers.VertxHttpHeaders.add(VertxHttpHeaders.java:68)
        at io.vertx.core.http.impl.headers.VertxHttpHeaders.add(VertxHttpHeaders.java:84)
        at io.vertx.core.http.impl.headers.VertxHttpHeaders.addAll(VertxHttpHeaders.java:114)
        at io.vertx.core.http.impl.headers.VertxHttpHeaders.addAll(VertxHttpHeaders.java:104)
        at io.vertx.ext.web.client.impl.HttpContext.handlePrepareRequest(HttpContext.java:351)
        at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:283)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:270)
        at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
        at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
        at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:267)
        at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:277)
        at io.vertx.ext.web.client.impl.HttpContext.prepareRequest(HttpContext.java:166)
        at io.vertx.ext.web.client.impl.HttpRequestImpl.send(HttpRequestImpl.java:290)
        at io.vertx.ext.web.client.impl.HttpRequestImpl.sendBuffer(HttpRequestImpl.java:265)
        at ProxyVerticle.lambda$sendProxiedRequest$10(ProxyVerticle.java:293)
        at o.vertx.core.http.HttpServerRequest.lambda$bodyHandler$0(HttpServerRequest.java:216)
`

I have been trying to reproduce this using a unit test in vertx-core, realizing that there are null guards that should prevent this from happing. In VertxHttpHeaders.set0(CharSequence name, CharSequence strVal) a null header value is normaly silently ignored and should prevent this from happening.
I have however not been able to get a null value into one MultiMap and then add all headers to another VertxHeaders to be able to reproduce the issue.

As a fix I would propose to cause the issue earlier, in the HttpUtils validateHeader method throwing a IllegalArgumentException as it is implemented now for illegal characters.

**Comment by vietj** [comment]
Now setting a null value will remove the header in the multimap @lbroman which should solve this issue as well. Can you have a check ? see https://github.com/eclipse-vertx/vert.x/issues/3267
