### ISSUE TITLE
Regression mount sub router from 3.8.1 to 3.8.2

### ISSUE THREAD

**Issue by Fyro-Ing** [eclipse-vertx/vert.x#3136]
It seems that there is a regression from 3.8.1 to 3.8.2, when we mount subrouter with regex route request

checkout this project to reproduce : https://github.com/Fyro-Ing/vertx-bug-regex

`    router.getWithRegex("^.*regex").handler((rc) -> {
      rc.response().end("regex");
    });`

`router.mountSubRouter("/", new TestRoute().init(vertx));`

`java.lang.NullPointerException
        at io.vertx.ext.web.impl.RouteImpl.validateMount(RouteImpl.java:563)
        at io.vertx.ext.web.impl.RouteImpl.subRouter(RouteImpl.java:180)
        at io.vertx.ext.web.impl.RouterImpl.mountSubRouter(RouterImpl.java:295)
        at io.github.vertx.bug.MainVerticle.start(MainVerticle.java:15)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:556)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by vietj** [comment]
can you reopen this issue on vertx-web project ? (https://github.com/vert-x3/vertx-web) thanks

**Comment by Fyro-Ing** [comment]
oops, sorry => https://github.com/vert-x3/vertx-web/issues/1419
