### ISSUE TITLE
3.8.3 - redeploy on linux fails

### ISSUE THREAD

**Issue by DaveO-Home** [eclipse-vertx/vert.x#3156]
Running  the demo server with run/start works - that is, the server displays text in the browser.
With ***start***, executing ***vertx list*** results with;  
```
Listing vert.x applications...
e586a4f4-9bd4-4535-9d1f-a0adec1ceb25	my.jsc.vertx.Server
```
With ***run***, executing ***vertx list*** results with;
```
Listing vert.x applications...
No vert.x application found.
```
With ***run*** and ***redeploy*** ;
```
Starting vert.x application...
3c34e176-2b83-4ff0-8849-09c6a15fd7fa-redeploy
```
executing ***vertx list*** results with;
```
Listing vert.x applications...
No vert.x application found.
```
And the browser gets a ***Unable to connect***.

executing ps -ef |grep vertx gets the following;
```
31784 31730  0 17:02 pts/3    00:00:02 /usr/java/latest/bin/java -XX:+UseBiasedLocking -XX:BiasedLockingStartupDelay=0 -Djava.util.logging.config.file=/home/daveo/work/vertx3/conf/logging.properties -Dvertx.home=/home/daveo/work/vertx3 -Dvertx.cli.usage.prefix=vertx -Dvertx.clusterManagerFactory=io.vertx.spi.cluster.impl.hazelcast.HazelcastClusterManagerFactory -classpath /usr/lib64/python3.6/site-packages/jep/jep-3.7.0.jar:/home/daveo/work/vertx3/conf:/home/daveo/work/vertx3/lib/* io.vertx.core.Launcher run my.jsc.vertx.Server -cp /usr/lib64/python3.6/site-packages/jep/jep-3.7.0.jar:.:/home/daveo/installs/jin-0.1.0/classes../lib/vertx-core-3.8.3.jar:/home/daveo/installs/jin-0.1.0/classes:/home/daveo/installs/jin-0.1.0/classes../lib/jin/jin.jar --redeploy /home/daveo/installs/jin-0.1.0/classes/my/jsc/vertx/Server.class --launcher-class=io.vertx.core.Launcher
```
While the redeploy is executing, changing code results with;
```
Stopping vert.x application '3c34e176-2b83-4ff0-8849-09c6a15fd7fa-redeploy'
Cannot find process for application using the id '3c34e176-2b83-4ff0-8849-09c6a15fd7fa-redeploy'.
Starting vert.x application...
3c34e176-2b83-4ff0-8849-09c6a15fd7fa-redeploy
```
And the browser still gets a ***Unable to connect***.

The Server code;
```
package my.jsc.vertx;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Promise;

public class Server extends AbstractVerticle {

  @Override
    // public void start(Future<Void> fut) {
    public void start(Promise<Void> fut) {
    
    vertx
        .createHttpServer()
        .requestHandler(r -> {
          r.response().end("<h1>Hello from my first " +
              "Vert.x 3 application</h1>");
        })
        .listen(8083, result -> {
          if (result.succeeded()) {
            fut.complete();
          } else {
            fut.fail(result.cause());
          }
        });
  }
}
```

**Comment by DaveO-Home** [comment]
Seems this error is causing the problem, perhaps I'm executing vertx incorrectly..
```

Watched paths: [/home/daveo/installs/jin-0.1.0/classes/my/jsc/vertx/Server.class] 
Starting the vert.x application in redeploy mode 
java.lang.ClassNotFoundException: run
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:37)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:243)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:216)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:80)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:183)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:156)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:145)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:681)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:168)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:403)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:383)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
	at io.vertx.core.Launcher.main(Launcher.java:45)
```

**Comment by DaveO-Home** [comment]
Duplicate of #1252, however I am using  --launcher-class=io.vertx.core.Launcher
