### ISSUE TITLE
Error on  build a vert.x native image with graalvm

### ISSUE THREAD

**Issue by yuhaibohotmail** [eclipse-vertx/vert.x#3162]
**Describe the bug**
Error on  build a vert.x  (v3.8.3) native image with graalvm.
  
**Log**
`Build on Server(pid: 1970, port: 28040)
[httpvertx2:1970]    classlist:   1,499.06 ms
[httpvertx2:1970]        (cap):     567.00 ms
[httpvertx2:1970]        setup:     826.96 ms
[httpvertx2:1970]     analysis:  11,292.09 ms
Warning: Aborting stand-alone image build. Unsupported features in 6 methods
Detailed message:
Error: No instances of io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace:  object io.netty.buffer.UnreleasableByteBuf
        object io.vertx.core.buffer.impl.BufferImpl
        method io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.access$300()
Call path from entry point to io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.access$300():
        at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.access$300(ClusteredEventBus.java:48)
        at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus$1.handle(ClusteredEventBus.java:321)
        at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus$1.handle(ClusteredEventBus.java:304)
        at io.vertx.core.impl.launcher.commands.RunCommand.stopBackgroundApplication(RunCommand.java:333)
        at io.vertx.core.impl.launcher.commands.RunCommand$$Lambda$3584/881120997.handle(Unknown Source)
        at io.vertx.core.impl.launcher.commands.Watcher.close(Watcher.java:282)
        at io.vertx.core.impl.launcher.commands.Watcher.run(Watcher.java:300)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
`

**Environment:**
 - GraalVM version  : graalvm-ce-19.2.0.1
 - Vert.x version : 3.8.3

**Comment by pmlopes** [comment]
@yuhaibohotmail the latest netty used in vert.x will require some extra classes to be initialized at runtime, a working config would be:

```properties
Args = --initialize-at-build-time=io.netty,io.vertx,com.fasterxml.jackson,javax \
       --initialize-at-run-time=--initialize-at-run-time=io.vertx.core.net.impl.PartialPooledByteBufAllocator,io.netty.handler.codec.http.websocketx.extensions.compression.DeflateEncoder,io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder,io.vertx.core.eventbus.impl.clustered.ClusteredEventBus,io.netty.util.internal.logging.Log4JLogger,io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,io.netty.handler.codec.http2.Http2CodecUtil,io.netty.handler.codec.http2.DefaultHttp2FrameWriter,io.netty.handler.ssl.ReferenceCountedOpenSslServerContext,io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator,io.netty.handler.ssl.ReferenceCountedOpenSslEngine,io.netty.handler.ssl.ConscryptAlpnSslEngine,io.netty.handler.ssl.JettyNpnSslEngine,io.netty.handler.ssl.ReferenceCountedOpenSslClientContext,io.vertx.core.net.impl.transport.EpollTransport,io.vertx.core.net.impl.transport.KQueueTransport,io.vertx.core.http.impl.VertxHttp2ClientUpgradeCodec,io.netty.handler.codec.http2.Http2ConnectionHandler \
       -H:+UseServiceLoaderFeature \
       -H:IncludeResources=(META-INF|static|webroot|template)/.* \
       -H:ReflectionConfigurationResources=${.}/reflection.json
```

**Comment by cescoffier** [comment]
The new contender is the clustered event bus.

**Comment by yuhaibohotmail** [comment]
@pmlopes Thanks！
