### ISSUE TITLE
IllegalArgumentException when using HttpClient with domainSocketAddress

### ISSUE THREAD

**Issue by adamdickmeiss** [eclipse-vertx/vert.x#3225]
Vert.x 3.8.4

````java

@RunWith(VertxUnitRunner.class)
public class DomainSocketTest {
  
  @Test
  public void test(TestContext context) {
    Async async = context.async();
    Logger logger = LoggerFactory.getLogger(DomainSocketTest.class);

    Vertx vertx = Vertx.vertx();
    HttpClient client = vertx.createHttpClient();
    SocketAddress sa = SocketAddress.domainSocketAddress("/var/run/docket.sock");
    // SocketAddress sa = SocketAddress.inetSocketAddress(4243, "localhost");
    HttpClientRequest req = client.requestAbs(HttpMethod.GET, sa, 
      "http://localhost:4243/v1.25/images/json", res -> {
      context.assertEquals(200, res.statusCode());
      async.complete();
    });
    req.exceptionHandler(d -> {
      logger.warn("exceptionHandler " + d, d);
      async.complete();
    });
    req.end();
    async.await();
  }

````

Getting an error that suggests that I'm not allowed to use Domain Socket at all - which is not what I expected.

Running org.folio.okapi.DomainSocketTest
Dec 11, 2019 2:29:29 PM org.folio.okapi.DomainSocketTest
WARNING: exceptionHandler java.lang.IllegalArgumentException
java.lang.IllegalArgumentException
	at io.vertx.core.net.impl.transport.Transport.channelFactory(Transport.java:180)
	at io.vertx.core.http.impl.HttpChannelConnector.doConnect(HttpChannelConnector.java:116)
	at io.vertx.core.http.impl.HttpChannelConnector.connect(HttpChannelConnector.java:100)
	at io.vertx.core.http.impl.pool.Pool$Holder.connect(Pool.java:126)
	at io.vertx.core.http.impl.pool.Pool.checkPendingTasks(Pool.java:256)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by julianladisch** [comment]
After I've changed `Vertx.vertx()` to `Vertx.vertx(new VertxOptions().setPreferNativeTransport(true))` your example runs successfully. For details see the manual: https://vertx.io/docs/vertx-core/java/#_native_transports

**Comment by adamdickmeiss** [comment]
Thx
