### ISSUE TITLE
JacksonCodec fail to encode Json with Enum

### ISSUE THREAD

**Issue by gaol** [eclipse-vertx/vert.x#3227]
Version: **Vertx-core 4.0.0-SNAPSHOT**

When `jackson-databind` is not available in class path, it falls over to use `JacksonCodec`, but the following tests will fail in case `Enums` are in the JsonObject:

<pre>
  enum SomeEnum {
    FOO, BAR
  }

  @Test
  public void testJsonEnumNoJacksonDatabind() {
    JsonObject json = new JsonObject();
    json.put("name", "foo").put("enum", SomeEnum.FOO);
    assertEquals("{\"name\":\"foo\",\"enum\":\"FOO\"}", json.toString());
  }
</pre>

The exceptions are:

    java.lang.UnsupportedOperationException
	    at io.vertx.core.json.jackson.JacksonCodec.encodeJson(JacksonCodec.java:303)
	    at io.vertx.core.json.jackson.JacksonCodec.encodeJson(JacksonCodec.java:268)
	    at io.vertx.core.json.jackson.JacksonCodec.toString(JacksonCodec.java:91)
	    at io.vertx.core.json.JsonObject.encode(JsonObject.java:648)
	    at io.vertx.core.json.JsonObject.toString(JsonObject.java:749)
	    at io.vertx.ext.mail.MailConfigTest.testJsonEnumNoJacksonDatabind(MailConfigTest.java:38)

**Comment by pmlopes** [comment]
Quickly looking at the code it looks the jackson codec misses a few cases:

* enum
* subclasses of number: bigdecimal, biginteger
