### ISSUE TITLE
Race Condition in HttpClientImpl.getConnectionForRequest, ConnectionManager.getConnection

### ISSUE THREAD

**Issue by ctrlshp** [eclipse-vertx/vert.x#3438]
I am using the Vert.x 4.0.0-SNAPSHOT stack with an AdoptOpenJDK 11.0.7 on Ubuntu 20.04. The first time I encountered this was with a Hazelcast-managed distibuted Vertx system (with only one node) with both a standard HTTP server and a vertx-grpc server running on two different ports (both with TLS/SNI enabled). After making a few successful calls to both, I closed the client (cleanly) and I let it rest for a few minutes. Then the console started to output that same error at what seems to be a sub-second interval :

```
[2020-06-05 13:06:34,190] [WARN] [io.vertx.core.impl.BlockedThreadChecker] [] [vertx-blocked-thread-checker] - Thread Thread[vert.x-eventloop-thread-9,5,main] has been blocked for 1120705 ms, time limit is 2000 ms MDC: {}
io.vertx.core.VertxException: Thread blocked
        at java.base@11.0.7/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1691)
        at app//io.vertx.core.net.impl.clientconnection.ConnectionManager.getConnection(ConnectionManager.java:46)
        at app//io.vertx.core.http.impl.HttpClientImpl.getConnectionForRequest(HttpClientImpl.java:1288)
        at app//io.vertx.core.http.impl.HttpClientRequestImpl.connect(HttpClientRequestImpl.java:422)
        at app//io.vertx.core.http.impl.HttpClientRequestImpl.sendHead(HttpClientRequestImpl.java:258)
        at app//io.vertx.ext.web.client.impl.HttpContext.handleSendRequest(HttpContext.java:501)
        at app//io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:285)
        at app//io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:269)
        at app//io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
        at app//io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
        at app//io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:266)
        at app//io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:276)
        at app//io.vertx.ext.web.client.impl.HttpContext.sendRequest(HttpContext.java:178)
        at app//io.vertx.ext.web.client.impl.HttpContext.handlePrepareRequest(HttpContext.java:353)
        at app//io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:282)
        at app//io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:269)
        at app//io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
        at app//io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
        at app//io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:266)
        at app//io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:276)
        at app//io.vertx.ext.web.client.impl.HttpContext.prepareRequest(HttpContext.java:165)
        at app//io.vertx.ext.web.client.impl.HttpRequestImpl.send(HttpRequestImpl.java:318)
        at app//io.vertx.ext.web.client.impl.HttpRequestImpl.send(HttpRequestImpl.java:288)
        at app//io.vertx.reactivex.ext.web.client.HttpRequest.send(HttpRequest.java:694)
        at app//io.vertx.reactivex.ext.web.client.HttpRequest.lambda$rxSend$20(HttpRequest.java:718)
        at app//io.vertx.reactivex.ext.web.client.HttpRequest$$Lambda$314/0x00000008405c5c40.accept(Unknown Source)
        at app//io.vertx.reactivex.impl.AsyncResultSingle.subscribeActual(AsyncResultSingle.java:45)
        at app//io.reactivex.Single.subscribe(Single.java:3603)
        at app//io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
        at app//io.reactivex.Single.subscribe(Single.java:3603)
        at app//io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at app//io.reactivex.Single.subscribe(Single.java:3603)
        at app//io.reactivex.internal.operators.maybe.MaybeFilterSingle.subscribeActual(MaybeFilterSingle.java:40)
        at app//io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at app//io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40)
        at app//io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at app//io.reactivex.internal.operators.maybe.MaybeFilter.subscribeActual(MaybeFilter.java:39)
        at app//io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at app//io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40)
        at app//io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at app//io.reactivex.internal.operators.mixed.MaybeFlatMapPublisher.subscribeActual(MaybeFlatMapPublisher.java:50)
        at app//io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at app//io.reactivex.internal.operators.flowable.FlowableFlatMapCompletableCompletable.subscribeActual(FlowableFlatMapCompletableCompletable.java:56)
        at app//io.reactivex.Completable.subscribe(Completable.java:2309)
        at app//io.reactivex.internal.operators.completable.CompletableOnErrorComplete.subscribeActual(CompletableOnErrorComplete.java:35)
        at app//io.reactivex.Completable.subscribe(Completable.java:2309)
        at app//io.reactivex.internal.operators.completable.CompletableToFlowable.subscribeActual(CompletableToFlowable.java:32)
        at app//io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at app//io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at app//io.reactivex.internal.operators.flowable.FlowableRepeat$RepeatSubscriber.subscribeNext(FlowableRepeat.java:101)
        at app//io.reactivex.internal.operators.flowable.FlowableRepeat$RepeatSubscriber.onComplete(FlowableRepeat.java:80)
        at app//io.reactivex.internal.observers.SubscriberCompletableObserver.onComplete(SubscriberCompletableObserver.java:33)
        at app//io.reactivex.internal.operators.completable.CompletableOnErrorComplete$OnError.onError(CompletableOnErrorComplete.java:64)
        at app//io.reactivex.internal.operators.flowable.FlowableFlatMapCompletableCompletable$FlatMapCompletableMainSubscriber.onError(FlowableFlatMapCompletableCompletable.java:150)
        at app//io.reactivex.internal.operators.mixed.MaybeFlatMapPublisher$FlatMapPublisherSubscriber.onError(MaybeFlatMapPublisher.java:80)
        at app//io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onError(MaybeMap.java:94)
        at app//io.reactivex.internal.operators.maybe.MaybeFilter$FilterMaybeObserver.onError(MaybeFilter.java:97)
        at app//io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onError(MaybeMap.java:94)
        at app//io.reactivex.internal.operators.maybe.MaybeFilterSingle$FilterMaybeObserver.onError(MaybeFilterSingle.java:98)
        at app//io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
        at app//io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
        at app//io.vertx.reactivex.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:56)
        at app//io.vertx.reactivex.impl.AsyncResultSingle$$Lambda$75/0x000000084015f040.handle(Unknown Source)
        at app//io.vertx.reactivex.ext.web.client.HttpRequest$10.handle(HttpRequest.java:699)
        at app//io.vertx.reactivex.ext.web.client.HttpRequest$10.handle(HttpRequest.java:694)
        at app//io.vertx.ext.web.client.impl.HttpContext.handleFailure(HttpContext.java:303)
        at app//io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:297)
        at app//io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:269)
        at app//io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
        at app//io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
        at app//io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:266)
        at app//io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:276)
        at app//io.vertx.ext.web.client.impl.HttpContext.fail(HttpContext.java:256)
        at app//io.vertx.ext.web.client.impl.HttpContext.lambda$handleSendRequest$8(HttpContext.java:416)
        at app//io.vertx.ext.web.client.impl.HttpContext$$Lambda$320/0x00000008405c4440.handle(Unknown Source)
        at app//io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:181)
        at app//io.vertx.core.impl.AbstractContext.lambda$dispatch$0(AbstractContext.java:84)
        at app//io.vertx.core.impl.AbstractContext$$Lambda$131/0x0000000840214c40.handle(Unknown Source)
        at app//io.vertx.core.impl.EventLoopContext.schedule(EventLoopContext.java:59)
        at app//io.vertx.core.impl.AbstractContext.schedule(AbstractContext.java:94)
        at app//io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:84)
        at app//io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:125)
        at app//io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
        at app//io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:170)
        at app//io.vertx.core.http.impl.HttpClientRequestBase.fail(HttpClientRequestBase.java:112)
        at app//io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:107)
        at app//io.vertx.core.http.impl.HttpClientRequestImpl.handleException(HttpClientRequestImpl.java:87)
        at app//io.vertx.core.http.impl.HttpClientRequestImpl.lambda$connect$2(HttpClientRequestImpl.java:433)
        at app//io.vertx.core.http.impl.HttpClientRequestImpl$$Lambda$323/0x00000008405c3040.handle(Unknown Source)
        at app//io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:181)
        at app//io.vertx.core.http.impl.HttpClientImpl.lambda$getConnectionForRequest$6(HttpClientImpl.java:1292)
        at app//io.vertx.core.http.impl.HttpClientImpl$$Lambda$324/0x00000008405c3440.handle(Unknown Source)
        at app//io.vertx.core.net.impl.clientconnection.Endpoint.lambda$getConnection$0(Endpoint.java:51)
        at app//io.vertx.core.net.impl.clientconnection.Endpoint$$Lambda$329/0x00000008405c1840.handle(Unknown Source)
        at app//io.vertx.core.net.impl.clientconnection.Pool.connectFailed(Pool.java:389)
        at app//io.vertx.core.net.impl.clientconnection.Pool.access$600(Pool.java:89)
        at app//io.vertx.core.net.impl.clientconnection.Pool$Holder.lambda$connect$0(Pool.java:130)
        at app//io.vertx.core.net.impl.clientconnection.Pool$Holder$$Lambda$332/0x00000008405c0840.handle(Unknown Source)
        at app//io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:127)
        at app//io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
        at app//io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:170)
        at app//io.vertx.core.http.impl.HttpChannelConnector.connectFailed(HttpChannelConnector.java:272)
        at app//io.vertx.core.http.impl.HttpChannelConnector.lambda$doConnect$0(HttpChannelConnector.java:186)
        at app//io.vertx.core.http.impl.HttpChannelConnector$$Lambda$347/0x000000084060d440.operationComplete(Unknown Source)
        at app//io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at app//io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
        at app//io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
        at app//io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at app//io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
        at app//io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:109)
        at app//io.vertx.core.net.impl.ChannelProvider$1.userEventTriggered(ChannelProvider.java:113)
        at app//io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
        at app//io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
        at app//io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
        at app//io.netty.handler.ssl.SslUtils.handleHandshakeFailure(SslUtils.java:347)
        at app//io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:2058)
        at app//io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at app//io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@11.0.7/java.lang.Thread.run(Thread.java:834)
```

Now I get it everytime I let the system run overnight. I'm the sole user of the system.

Does this ring a bell ? I can't try to use it with the 3.x stack because the Vertx-grpc has a completely different codebase fo 4.0.0.

**Comment by vietj** [comment]
can you provide a reproducer for this ?

**Comment by ctrlshp** [comment]
I can. It's going to take days, however. I'm going to see if I can think of something simpler than just putting out the whole thing. I will first test the microservices independently, try removing Hazelcast, etc.

**Comment by ctrlshp** [comment]
I can assure you that it is not done in a unit test. This is a Vertx instance running on a single node started with `rxClusteredVertx` with Hazelcast as the cluster manager within a Ubuntu 20.04 docker container with a dozen of verticlealll spawning off the main verticle. Now, I'm trying to see if I still have the problem when running Vertx as `Vertx.vertx()`(the rx-ified version) without Hazelcast. I will do the same thing : use it for a little while and then let it sit there overnight. I'll keep you posted. THanks.

**Comment by vietj** [comment]
@ctrlshp did it happen again ? if it does can you do a thread dump capture ?

**Comment by vietj** [comment]
closing for now, please reopen with a thread dump capture to understand what is going on (it could be a thread deadlock)
