### ISSUE TITLE
There is a bug with multi-file uploads

### ISSUE THREAD

**Issue by xiaojianhx** [eclipse-vertx/vert.x#3470]
### Questions

There is a bug with multi-file uploads.It may be changed the length of a boundary token.Occasional.
### Version
3.9.1

### Example

The client
```java
        var request = WebClient.create(Vertx.vertx()).postAbs("http://localhost:8080/test");

        for (var i = 0; i < 50; i++) {

            var body = MultipartForm.create();

            body.binaryFileUpload("files", "1.jpg", "/tmp/xx/a.jpg", "image/jpeg");
            body.binaryFileUpload("files", "2.jpg", "/tmp/xx/b.jpg", "image/jpeg");

            request.sendMultipartForm(body, r -> {

                if (r.failed()) {
                    System.err.println(r.cause());
                    return;
                }
                System.out.println(r.result());
            });
        }
```

The server(springboot:2.3.1.RELEASE)

```java
    @ResponseBody
    @RequestMapping("/test")
    public Map<String, Object> mail(@RequestParam(value = "files", required = false) MultipartFile[] files) {
        return Collections.EMPTY_MAP;
    }
````

The error

```bash
org.apache.tomcat.util.http.fileupload.MultipartStream$IllegalBoundaryException: The length of a boundary token cannot be changed
	at org.apache.tomcat.util.http.fileupload.MultipartStream.setBoundary(MultipartStream.java:459)
	at org.apache.tomcat.util.http.fileupload.impl.FileItemIteratorImpl.findNextItem(FileItemIteratorImpl.java:244)
	at org.apache.tomcat.util.http.fileupload.impl.FileItemIteratorImpl.<init>(FileItemIteratorImpl.java:131)
	at org.apache.tomcat.util.http.fileupload.FileUploadBase.getItemIterator(FileUploadBase.java:255)
	at org.apache.tomcat.util.http.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:279)
 ...
```

**Comment by tsegismont** [comment]
Can you please share a reproducer? Thank you

**Comment by xiaojianhx** [comment]
I have solved the problem. It's not a bug.Thank you.

set **_multipartMixed_** to **_false_**

```java
request.multipartMixed(false).sendMultipartForm(body, r -> {
  // do something ...
});
```
