### ISSUE TITLE
Thread blocked with drainHandler, writeQueueFull 

### ISSUE THREAD

**Issue by adamdickmeiss** [eclipse-vertx/vert.x#3474]
POSTing many buffers to an echoing server gives thread blocked failures when we use drainHandler+writeQueueFull approach.

The same POST with write and a completion handler does not.

Write with handler is a much simpler strategy, but from documentation it's not clear whether it's an alternative for drainHandler. In any case we cannot explain our thread blocked problems with drainHandler.

What's the best strategy for writing?

### Environment

Using vertx-core-4.0.0-milestone4 on Ubuntu 20.04 LTS amd64.

### Reproducer

Below is a unit test with test methods `drainHandler` and  `writeHandler`. Each test sends 10 times 2 GB to an echoing server (part of unit test).

```
import io.vertx.core.Vertx;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.http.HttpClient;
import io.vertx.core.http.HttpClientRequest;
import io.vertx.core.http.HttpClientResponse;
import io.vertx.core.streams.Pump;
import io.vertx.core.streams.WriteStream;
import io.vertx.ext.unit.Async;
import io.vertx.ext.unit.TestContext;
import io.vertx.ext.unit.junit.VertxUnitRunner;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.concurrent.atomic.AtomicLong;

@RunWith(VertxUnitRunner.class)
public class WriteTest {
  Vertx vertx;
  int port = 9210;

  @Before
  public void setUp(TestContext context) {
    vertx = Vertx.vertx();
    vertx.createHttpServer()
        .requestHandler(h -> {
          h.response().setChunked(true);
          h.endHandler(x -> h.response().end());
          Pump.pump(h, h.response()).start();
        }).listen(port, context.asyncAssertSuccess());
  }

  @After
  public void tearDown(TestContext context) {
    vertx.close();
  }

  @Test
  public void drainHandler(TestContext context) {
    testUpload(context, true);
  }

  @Test
  public void writeHandler(TestContext context) {
    testUpload(context, false);
  }

  private void testUpload(TestContext context, boolean useDrain) {
    int bufSz = 200000;
    long bufCnt = 10000;
    long total = bufSz * bufCnt;
    HttpClient client = vertx.createHttpClient();
    for (int loop = 0; loop < 10; loop++) {
      System.out.println("Sending " + total / 1e9 + " GB");
      Async async = context.async();
      HttpClientRequest request = client.postAbs("http://localhost:" + port, res1 -> {
        context.assertTrue(res1.succeeded());
        HttpClientResponse res = res1.result();
        context.assertEquals(200, res.statusCode());
        AtomicLong cnt = new AtomicLong();
        res.handler(h -> cnt.addAndGet(h.length()));
        res.exceptionHandler(ex -> {
          context.fail(ex);
          async.complete();
        });
        res.endHandler(end -> {
          context.assertEquals(total, cnt.get());
          async.complete();
        });
      });
      request.exceptionHandler(ex -> {
        context.fail(ex.getCause());
        async.complete();
      });
      request.putHeader("Content-Type", "text/plain");
      request.setChunked(true);
      Buffer buffer = Buffer.buffer();
      for (int j = 0; j < bufSz; j++) {
        buffer.appendString("X");
      }
      request.setWriteQueueMaxSize(16384);
      if (useDrain) {
        endRequestDrainHandler(request, buffer, 0, bufCnt);
      } else {
        endRequestWriteHandler(request, buffer, 0, bufCnt);
      }
      async.await(50000);
    }
  }

  void endRequestWriteHandler(WriteStream<Buffer> req, Buffer buffer, long i, long cnt) {
    if (i < cnt) {
      req.write(buffer, res -> endRequestWriteHandler(req, buffer, i + 1, cnt));
      return;
    }
    req.end();
  }

  void endRequestDrainHandler(WriteStream<Buffer> req, Buffer buffer, long i, long cnt) {
    req.drainHandler(null);
    while (i < cnt) {
      req.write(buffer);
      i++;
      long next = i;
      if (req.writeQueueFull()) {
        req.drainHandler(res -> endRequestDrainHandler(req, buffer, next, cnt));
        return;
      }
    }
    req.end();
  }
}
```

### Output

Example run:
```
mvn -Dtest=WriteTest#drainHandler test`

Sending 2.0 GB
Sending 2.0 GB
12:44:27 WARN  ?                    Thread Thread[vert.x-eventloop-thread-6,5,main] has been blocked for 2662 ms, time limit is 2000 ms
12:44:28 WARN  ?                    Thread Thread[vert.x-eventloop-thread-6,5,main] has been blocked for 3663 ms, time limit is 2000 ms
12:44:29 WARN  ?                    Thread Thread[vert.x-eventloop-thread-6,5,main] has been blocked for 4663 ms, time limit is 2000 ms
12:44:30 WARN  ?                    Thread Thread[vert.x-eventloop-thread-6,5,main] has been blocked for 5663 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.isNotWritable(Http1xClientConnection.java:383) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
	at io.vertx.core.http.impl.HttpClientRequestImpl.writeQueueFull(HttpClientRequestImpl.java:221) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
	at WriteTest.endRequestDrainHandler(WriteTest.java:105) ~[test-classes/:?]
	at WriteTest.lambda$endRequestDrainHandler$8(WriteTest.java:106) ~[test-classes/:?]
	at WriteTest$$Lambda$98/596706728.handle(Unknown Source) ~[?:?]
	at io.vertx.core.http.impl.HttpClientRequestImpl.handleDrained(HttpClientRequestImpl.java:344) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleWritabilityChanged(Http1xClientConnection.java:436) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
	at io.vertx.core.http.impl.Http1xClientConnection$$Lambda$74/255332034.handle(Unknown Source) ~[?:?]
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:183) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
	at io.vertx.core.impl.EventLoopContext.lambda$execute$0(EventLoopContext.java:42) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
	at io.vertx.core.impl.EventLoopContext$$Lambda$39/347978868.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_252]
12:44:31 WARN  ?                    Thread Thread[vert.x-eventloop-thread-6,5,main] has been blocked for 6664 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.isNotWritable(Http1xClientConnection.java:383) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
	at io.vertx.core.http.impl.HttpClientRequestImpl.writeQueueFull(HttpClientRequestImpl.java:221) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
	at WriteTest.endRequestDrainHandler(WriteTest.java:105) ~[test-classes/:?]
	at WriteTest.lambda$endRequestDrainHandler$8(WriteTest.java:106) ~[test-classes/:?]
	at WriteTest$$Lambda$98/596706728.handle(Unknown Source) ~[?:?]
	at io.vertx.core.http.impl.HttpClientRequestImpl.handleDrained(HttpClientRequestImpl.java:344) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleWritabilityChanged(Http1xClientConnection.java:436) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
	at io.vertx.core.http.impl.Http1xClientConnection$$Lambda$74/255332034.handle(Unknown Source) ~[?:?]
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:183) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
	at io.vertx.core.impl.EventLoopContext.lambda$execute$0(EventLoopContext.java:42) ~[vertx-core-4.0.0-milestone4.jar:4.0.0-milestone4]
	at io.vertx.core.impl.EventLoopContext$$Lambda$39/347978868.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_252]
```

Running

```
mvn -Dtest=WriteTest#writeHandler test
```

always completes and memory usage is low.

**Comment by vietj** [comment]
this is expected given how the drainHandler test is written, the correct way to do would be to schedule every write with a runOnContext so it leaves the opportunity to do perform other tasks:

```java
  void endRequestDrainHandler(WriteStream<Buffer> req, Buffer buffer, long i, long cnt) {
    req.drainHandler(null);
    int writes = 0;
    while (i < cnt) {
      req.write(buffer);
      i++;
      long next = i;
      if (req.writeQueueFull()) {
        req.drainHandler(res -> endRequestDrainHandler(req, buffer, next, cnt));
        return;
      } else if (writes++ > 10) {
        vertx.runOnContext(() -> {
           endRequestDrainHandler(req, buffer, i, next);
        });
        break;
      }
    }
    req.end();
  }
```

**Comment by adamdickmeiss** [comment]
The suggested change does not change the bahavior. In fact it gets worse.. Sometimes hangs .. And at other times thread blocked at same place as before. Something weird going on in writeQueueFull handling if I interpret the trace correctly. With this in mind, I'll empirically use the write with a completion handler; both simpler and reliable fast results in this test.

**Comment by vietj** [comment]
The issue is that doing too many writes on the event-loop is perceived as a blocking task

@adamdickmeiss I haven't tested what I wrote, but I think you get the idea of what should be done and I think this is the right thing to do.

**Comment by vietj** [comment]
I tested your code against the current Vert.x 4.0 SNAPSHOT and I cannot
reproduce it, here is the code adapted (so it can be run in vertx-core
Http1xTest)) :

@Test
public void drainHandler() throws Exception {
  testUpload(true);
}

@Test
public void writeHandler() throws Exception {
  testUpload(false);
}

private void testUpload(boolean useDrain) throws Exception {

  server.requestHandler(h -> {
    h.response().setChunked(true);
    h.endHandler(x -> h.response().end());
    Pump.pump(h, h.response()).start();
  });
  startServer();

  int bufSz = 200000;
  long bufCnt = 10000;
  long total = bufSz * bufCnt;
  HttpClient client = vertx.createHttpClient();
  for (int loop = 0; loop < 10; loop++) {
    System.out.println("Sending " + total / 1e9 + " GB");
    CountDownLatch latch = new CountDownLatch(1);
    HttpClientRequest request = client.request(HttpMethod.POST,
DEFAULT_HTTP_PORT, DEFAULT_HTTP_HOST, DEFAULT_TEST_URI);
    request.onComplete(onSuccess(res -> {
      assertEquals(200, res.statusCode());
      AtomicLong cnt = new AtomicLong();
      res.handler(h -> cnt.addAndGet(h.length()));
      res.exceptionHandler(ex -> {
        fail(ex);
        latch.countDown();
      });
      res.endHandler(end -> {
        assertEquals(total, cnt.get());
        latch.countDown();
      });
    }));
    request.exceptionHandler(ex -> {
      fail(ex.getCause());
      latch.countDown();
    });
    request.putHeader("Content-Type", "text/plain");
    request.setChunked(true);
    Buffer buffer = Buffer.buffer();
    for (int j = 0; j < bufSz; j++) {
      buffer.appendString("X");
    }
    request.setWriteQueueMaxSize(16384);
    if (useDrain) {
      endRequestDrainHandler(request, buffer, 0, bufCnt);
    } else {
      endRequestWriteHandler(request, buffer, 0, bufCnt);
    }
    awaitLatch(latch);
  }
}

void endRequestWriteHandler(WriteStream<Buffer> req, Buffer buffer,
long i, long cnt) {
  if (i < cnt) {
    req.write(buffer, res -> endRequestWriteHandler(req, buffer, i + 1, cnt));
    return;
  }
  req.end();
}

void endRequestDrainHandler(WriteStream<Buffer> req, Buffer buffer,
long i, long cnt) {
  req.drainHandler(null);
  while (i < cnt) {
    req.write(buffer);
    i++;
    long next = i;
    if (req.writeQueueFull()) {
      req.drainHandler(res -> endRequestDrainHandler(req, buffer, next, cnt));
      return;
    }
  }
  req.end();
}


can you have a try and tell me how it behaves for you ?

**Comment by adamdickmeiss** [comment]
Thx for quick reply. I'll try various things out.

**Comment by adamdickmeiss** [comment]
Able to inject the test fine.. What I see is slightly different from before. I was using openjdk 1.8 until now.. Running the drainHandler test does not give thread-blocked in writeQueueFull anymore. However, after a few pushes of 2 GB (seeming random behavior) I get thread-blocked and a spike in memory usage which leads the VM to shut down.

```
[jetty-alpn-agent][ info] alpn-boot not necessary for Java version: 1.8.0_252
Running io.vertx.core.http.Http1xTest
Starting test: Http1xTest#drainHandler 
Sending 2.0 GB
Sending 2.0 GB
Sending 2.0 GB
Sending 2.0 GB
Sending 2.0 GB
Sending 2.0 GB
Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2481 ms, time limit is 2000 ms 
Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3481 ms, time limit is 2000 ms 
Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4481 ms, time limit is 2000 ms 
io.vertx.core.VertxException: Connection was closed
java.lang.AssertionError: Connection was closed
        at org.junit.Assert.fail(Assert.java:88)
        at io.vertx.test.core.AsyncTestBase.fail(AsyncTestBase.java:268)
        at io.vertx.test.core.AsyncTestBase.lambda$onSuccess$2(AsyncTestBase.java:650)
        at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:181)
        at io.vertx.core.impl.AbstractContext.lambda$dispatch$0(AbstractContext.java:84)
        at io.vertx.core.impl.EventLoopContext.schedule(EventLoopContext.java:59)
        at io.vertx.core.impl.AbstractContext.schedule(AbstractContext.java:94)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:84)
        at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:125)
        at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
        at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:170)
        at io.vertx.core.http.impl.HttpClientRequestBase.fail(HttpClientRequestBase.java:112)
        at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:107)
        at io.vertx.core.http.impl.HttpClientRequestImpl.handleException(HttpClientRequestImpl.java:87)
        at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleException(Http1xClientConnection.java:465)
        at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleClosed(Http1xClientConnection.java:470)
        at io.vertx.core.http.impl.Http1xClientConnection.lambda$handleClosed$7(Http1xClientConnection.java:840)
        at io.vertx.core.impl.EventLoopContext.schedule(EventLoopContext.java:59)
        at io.vertx.core.http.impl.Http1xClientConnection.handleClosed(Http1xClientConnection.java:840)
        at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:136)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)


Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 16.534 sec <<< FAILURE! - in io.vertx.core.http.Http1xTest
drainHandler(io.vertx.core.http.Http1xTest)  Time elapsed: 16.426 sec  <<< ERROR!
java.lang.OutOfMemoryError: Java heap space
        at io.netty.util.internal.PlatformDependent.allocateUninitializedArray(PlatformDependent.java:281)
        at io.netty.buffer.UnpooledUnsafeHeapByteBuf.allocateArray(UnpooledUnsafeHeapByteBuf.java:39)
        at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf.allocateArray(UnpooledByteBufAllocator.java:144)
        at io.netty.buffer.UnpooledHeapByteBuf.<init>(UnpooledHeapByteBuf.java:59)
        at io.netty.buffer.UnpooledUnsafeHeapByteBuf.<init>(UnpooledUnsafeHeapByteBuf.java:34)
        at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf.<init>(UnpooledByteBufAllocator.java:139)
        at io.netty.buffer.UnpooledByteBufAllocator.newHeapBuffer(UnpooledByteBufAllocator.java:82)
        at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:168)
        at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:159)
        at io.netty.buffer.CompositeByteBuf.allocBuffer(CompositeByteBuf.java:1853)
        at io.netty.buffer.CompositeByteBuf.consolidate0(CompositeByteBuf.java:1732)
        at io.netty.buffer.CompositeByteBuf.consolidateIfNeeded(CompositeByteBuf.java:559)
        at io.netty.buffer.CompositeByteBuf.addComponent(CompositeByteBuf.java:266)
        at io.netty.buffer.CompositeByteBuf.addComponent(CompositeByteBuf.java:222)
        at io.vertx.core.http.impl.HttpClientRequestImpl.write(HttpClientRequestImpl.java:605)
        at io.vertx.core.http.impl.HttpClientRequestImpl.write(HttpClientRequestImpl.java:540)
        at io.vertx.core.http.impl.HttpClientRequestImpl.write(HttpClientRequestImpl.java:533)
        at io.vertx.core.http.impl.HttpClientRequestImpl.write(HttpClientRequestImpl.java:52)
        at io.vertx.core.http.Http1xTest.endRequestDrainHandler(Http1xTest.java:5049)
        at io.vertx.core.http.Http1xTest.testUpload(Http1xTest.java:5028)
        at io.vertx.core.http.Http1xTest.drainHandler(Http1xTest.java:4977)
```


It does not always happen even with 10 * 2 GB being pushed. I *also* see some kind of dead lock sometimes.. Process goes to idle and the push of 2 GB never completes.

Turned to OpenJDK 11.0.7 .. recompiled Vert.x and ran again.. Still same issues, but happens less often it seems.

Here's what *seem* to affect behavior .. so you could try this in order to provoke.. bufsz bufCnt combo.. Going *10 up on bufCnt and /10 on bufSz seems to provoke the problem more. Also not setting or adjustnig request.setWriteQueueMaxSize has an effect. Which I guess is not a surprise.

I'll try experimenting on another host now.

**Comment by adamdickmeiss** [comment]
Here are set of values that consistently gets hangs on 2nd run on two separate hosts: bufSz=2000, bufCnt=100000, maxQueueSize=16384 (I think it is caused whenever bufSz < maxQueueSize).

**Comment by vietj** [comment]
thanks I'll have a look soon.

**Comment by vietj** [comment]
by the way, could you try with latest Vert.x 4.0 snapshots ?

**Comment by adamdickmeiss** [comment]
I'm testing with 4.0.0-SNAPSHOT https://github.com/eclipse-vertx/vert.x.git

commit 2cba6a5f892df48a675cc724a13183f1cd50dfc0 (HEAD -> master, origin/master, origin/HEAD)
Author: Julien Viet <julien@julienviet.com>
Date:   Wed Jul 1 18:44:37 2020 +0200

    HTTP client redirection does not correctly resolve percent encoded redirections - see #3472
And running mvn -Dtest=Http1xTest#drainHandler test . Is there a more recent code?

**Comment by vietj** [comment]
ok thank you.

**Comment by adamdickmeiss** [comment]
Installed and ran on Windows 10 with OpenJDK 1.8. I got the hangs as mentioned earlier with a bufSz < maxQueueSize.

On Linux again, for a bufCnt=1000 and bufSz=33000 queuemaxsize=16384 I sometimes get an assertion failure.. 

```
[jetty-alpn-agent][ info] alpn-boot not necessary for Java version: 1.8.0_252
Running io.vertx.core.http.Http1xTest
Starting test: Http1xTest#drainHandler 
Sending 0.033 GB
Sending 0.033 GB
Sending 0.033 GB
Sending 0.033 GB
Sending 0.033 GB
java.lang.AssertionError: expected:<33000000> but was:<660000>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.vertx.test.core.AsyncTestBase.assertEquals(AsyncTestBase.java:241)
	at io.vertx.core.http.Http1xTest.lambda$null$561(Http1xTest.java:5012)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:181)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:99)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:230)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$handleBegin$3(Http1xClientConnection.java:446)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleEnd(Http1xClientConnection.java:461)
	at io.vertx.core.impl.EventLoopContext.schedule(EventLoopContext.java:59)
	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:664)
	at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:529)
	at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:504)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:127)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:146)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Unhandled exception 
java.lang.AssertionError: expected:<33000000> but was:<660000>
```

**Comment by vietj** [comment]
I tried several combination as you explained and I'm not able to get issues (OS X)

can you investigate the OOM to find if that's a potential leak ?

**Comment by vietj** [comment]
also we need to keep in mind that the test as written can be racy as sending buffers is performed outside the event loop from the junit thread

**Comment by vietj** [comment]
I've been able to get the thread blocked issue you reported and I did a thread dump, it indicated me that this is due to an allocation issue, i.e when a client request write is performed it will allocate a `ByteBuf` which sometimes can take lot of time because there is an high allocation pressure. As this allocation is done inside a synchronized block then the connected callback cannot be delivered.

I don't think this is an actual problem, however I would like to move the allocation outside of the synchronized block to see how it behaves. All this pertain to the fact that we are using a lazy initialized HTTP client request and there must be a way to buffer buffers when the client is not yet connected.

Which leads me to lean toward a refactor a change of the HTTP client to avoid this buffering and provide a more asynchronous programming, i.e:

```java
// Current lazy
HttpClientRequest request = client.request(...);
request.write(buffer);
request.end();

// Non lazy
client.connect(..., ar -> {
  if (ar.succeeded()) {
    HttpClientRequest request = ar.result();
    // Won't be buffered
    request.write(buffer);
    request.end();
  }
});
```

**Comment by adamdickmeiss** [comment]
The non-lazy way certainly makes sense.. That's not possible yet, with the current API, I assume.

I ran with bufSz=2000 bufCnt=10000 with attached visualvm on the "hanging" process. According to visualvm there's a deadlock situation and it's not what you are seeing above.

[threaddump-1594030314063.txt](https://github.com/eclipse-vertx/vert.x/files/4878266/threaddump-1594030314063.txt)

Hope this might be useful.

**Comment by vietj** [comment]
thanks for the deadlock : I removed the synchronization that was causing it
which was actually not intended to be done anymore :
https://github.com/eclipse-vertx/vert.x/commit/a84f711d28b43b2e31e87cb62611c393ac7d6dac

**Comment by adamdickmeiss** [comment]
git pull and now runs happily. I'll do a bit more testing.
