### ISSUE TITLE
File Upload failed when Content-Disposition has a "filename*" field

### ISSUE THREAD

**Issue by trisight** [eclipse-vertx/vert.x#3476]
### Questions

when upload a nonascii named file, there's a field "filename*" in "Content-Disposition" header , then vertx will throw IllegalCharsetNameException

### Version

3.8.5

### Context

Content-Disposition: form-data; name="eml"; filename="Reminder_ Join the ...Postman 101... Webinar on June 30.eml"; filename*="UTF-8''Reminder_%20Join%20the%20%E2%80%9CPostman%20101%E2%80%9D%20Webinar%20on%20June%2030.eml".
Content-Type: message/rfc822.

### Do you have a reproducer?

allways

**Comment by vietj** [comment]
can you provide more details ? I tried to reproduce it but I could not. I would need a dump of the actual request or a java project for reproducing. I tried an example with the filename* value you gave and it worked.

**Comment by vietj** [comment]
https://github.com/eclipse-vertx/vert.x/commit/b8924b5a0a27c98b755603a545def4f24689f11f here is the test I added

**Comment by trisight** [comment]
I think you must an non ascii filename for testing。 

I used a file names _Reminder_ Join the “Postman 101” Webinar on June 30.eml_

stacktrace following

io.netty.handler.codec.http.multipart.HttpPostRequestDecoder$ErrorDataDecoderException: java.nio.charset.IllegalCharsetNameException: "UTF-8
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.findMultipartDisposition(HttpPostMultipartRequestDecoder.java:699)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.decodeMultipart(HttpPostMultipartRequestDecoder.java:490)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.findMultipartDelimiter(HttpPostMultipartRequestDecoder.java:642)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.decodeMultipart(HttpPostMultipartRequestDecoder.java:477)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.parseBodyMultipart(HttpPostMultipartRequestDecoder.java:442)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.parseBody(HttpPostMultipartRequestDecoder.java:411)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:336)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:53)
	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:227)
	at io.vertx.core.http.impl.HttpServerRequestImpl.onData(HttpServerRequestImpl.java:495)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleContent(HttpServerRequestImpl.java:139)
	at io.vertx.core.http.impl.Http1xServerConnection.handleContent(Http1xServerConnection.java:160)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:140)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.charset.IllegalCharsetNameException: "UTF-8
	at java.nio.charset.Charset.checkName(Charset.java:315)
	at java.nio.charset.Charset.lookup2(Charset.java:484)
	at java.nio.charset.Charset.lookup(Charset.java:464)
	at java.nio.charset.Charset.forName(Charset.java:528)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.getContentDispositionAttribute(HttpPostMultipartRequestDecoder.java:815)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.findMultipartDisposition(HttpPostMultipartRequestDecoder.java:695)
	... 47 more

**Comment by vietj** [comment]
Hi,

it seems that your request is incorrect and provides an invalid character
set name <"UTF-8> instead of <UTF-8>

can you check that ?

**Comment by trisight** [comment]
I'm afraid it's not.

I use postman for testing, and I caught the http request header following, vertx will fail when checking "Content-Disposition"

POST /eml/upload/ HTTP/1.1.
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJkaXNwbGF5IjoidGVzdCIsInBlcm1pc3Npb25zIjpbInVzZXIiLCJhZG1pbiJdLCJpZCI6MSwiaWF0IjoxNTgzMzg4NzkxLCJleHAiOjE1ODM0OTY3OTF9.f2zkeNCysOhQrfdpGnzggri18AJnoHp0pdzoTXyCnww.
User-Agent: PostmanRuntime/7.26.1.
Accept: */*.
Cache-Control: no-cache.
Postman-Token: 8fcde332-357f-4fed-a12d-c395dafdb311.
Host: 172.16.96.17:10080.
Accept-Encoding: gzip, deflate, br.
Connection: keep-alive.
Content-Type: multipart/form-data; boundary=--------------------------111442997097437418261090.
Content-Length: 27691.
.
----------------------------111442997097437418261090.
Content-Disposition: form-data; name="eml"; filename="Reminder_ Join the ...Postman 101... Webinar on June 30.eml"; filename*="UTF-8''Reminder_%20Join%20the%20%E2%80%9CPostman%20101%E2%80%9D%20Webinar%20on%20June%2030.eml".
Content-Type: message/rfc822.

**Comment by vietj** [comment]
can you provide a complete way of reproducing this ?

**Comment by trisight** [comment]
I just wrote a flat html for testing, everything goes ok. The only difference between flat html and postman client, is there's no "filename*" in flat html case. I'm not sure that bug is from postman or vertx.

Try to reproduce, just use postman to upload a file named 'Reminder_ Join the “Postman 101” Webinar on June 30.eml', your vertx app will throw an excetpion.  and I think any non native english named file will do that job too.

Just use **postman** for testing, I think it may be based on a new rfc profile.

**Comment by vietj** [comment]
can you capture your request traffic in a PCAP file (Wireshark, tcpdump), that would work too.

**Comment by vietj** [comment]
@trisight ping, we haven't heard from you back

**Comment by vietj** [comment]
@trisight when I reproduced the problem it seems as I said that the client was sending an incorrect charset

**Comment by pmlopes** [comment]
I've added a test on vertx-web: https://github.com/vert-x3/vertx-web/pull/1693/commits/0c6b34a1db13be9d32b0ce73310d6b3e10f7fbfe and it does not fail.

**Comment by vietj** [comment]
@pmlopes thanks I will close this issue as it looks like an invalid client request reported
