### ISSUE TITLE
Request JSON body sent from client not matching with request  JSON body received on Server.

### ISSUE THREAD

**Issue by SwaroopBandari** [eclipse-vertx/vert.x#3526]
Vertx 3.9.X

Request body sent from client Http2 Client not matching with request  body received on Http2 Server at 15k TPS on Load.

To reproduce increase the size of request body more than 2 KB  and the data should be in JSON.

Getting the following exception .

Ended flag true
&&&&&&&&&&7777777 Length Header 2539Length Received 2430
@@@@@@@@@@@@@**************654515<StreamID>*********null <Body>
org.json.JSONException: Missing value at 2430 [character 2431 line 1]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:432)
        at org.json.JSONTokener.nextValue(JSONTokener.java:386)
        at org.json.JSONObject.<init>(JSONObject.java:208)

**Comment by tsegismont** [comment]
Can you please share a reproducer project? Thank you

**Comment by SwaroopBandari** [comment]
Hi, 
Thanks for you reply, 
https://github.com/SwaroopBandari/VertxHttp2Example.git

Here i am sharing the git repo link .

Please getback if anything else needed.

Thank you.

**Comment by SwaroopBandari** [comment]
> Can you please share a reproducer project? Thank you

Hi,
Thanks for you reply,
https://github.com/SwaroopBandari/VertxHttp2Example.git

Here i am sharing the git repo link .

Please getback if anything else needed.

Thank you.

**Comment by vietj** [comment]
I will have a look

**Comment by vietj** [comment]
@SwaroopBandari can you provide a full reproducer with a build file and a README instead of a collection of files ?

**Comment by SwaroopBandari** [comment]
> @SwaroopBandari can you provide a full reproducer with a build file and a README instead of a collection of files ?
I have committed the Client and Server build files which generates respective jar files .
IP and port need to configured in side main classes.

Thanks in advance
