### ISSUE TITLE
Future related context emission should only happen when calling final handlers

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3534]
Currently the future are generic and when a future attached to a context is transformed, the completion flow performs a lot of un-necessary context dispatches leading to long stack traces.

We should avoid context dispatches for internal purposes and only perform context dispatch for final handlers set by the user.

Transformations like `compose` or using a `Promise<T>` as an `Handler<AsyncResult<T>>` should perform direct invocation and bypass the context attached to the future.

To solve this we split `FutureImpl` into `FutureImpl` and `PromiseImpl` and we add an internal `Listener` interface that `FutureImpl` will deliver the event to.

- calling `onComplete(Handler<AsyncResult<T>>)` wraps the handler as a `Listener` which either calls directly the handler or perform the context event emission.
- `PromiseImpl` extends `FutureImpl` and implements the `Listener` interface
- future transformation are now subclasses of `FutureImpl` and also implement the `Listener` interface

Here is an example with transformation:

```java
VertxInternal vertx = (VertxInternal) Vertx.vertx();
ContextInternal ctx = vertx.getOrCreateContext();
PromiseInternal<String> promise = ctx.promise();
promise.future()
  .compose(s -> ctx.succeededFuture(s.length()))
  .compose(s -> ctx.succeededFuture(" " + s))
  .onComplete(ar -> {
    new Exception().printStackTrace();
});
ctx.runOnContext(v -> {
  promise.complete("ABC");
});
```

Currently it leads to the stack trace 

```
java.lang.Exception
	at io.vertx.core.Main.lambda$main$2(Main.java:20)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:181)
	at io.vertx.core.impl.AbstractContext.lambda$dispatch$0(AbstractContext.java:84)
	at io.vertx.core.impl.EventLoopContext.schedule(EventLoopContext.java:59)
	at io.vertx.core.impl.AbstractContext.schedule(AbstractContext.java:94)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:84)
	at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:144)
	at io.vertx.core.Promise.complete(Promise.java:67)
	at io.vertx.core.Promise.handle(Promise.java:52)
	at io.vertx.core.Promise.handle(Promise.java:30)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:181)
	at io.vertx.core.impl.AbstractContext.lambda$dispatch$0(AbstractContext.java:84)
	at io.vertx.core.impl.EventLoopContext.schedule(EventLoopContext.java:59)
	at io.vertx.core.impl.AbstractContext.schedule(AbstractContext.java:94)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:84)
	at io.vertx.core.impl.SucceededFuture.onComplete(SucceededFuture.java:49)
	at io.vertx.core.Future.lambda$compose$2(Future.java:250)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:181)
	at io.vertx.core.impl.AbstractContext.lambda$dispatch$0(AbstractContext.java:84)
	at io.vertx.core.impl.EventLoopContext.schedule(EventLoopContext.java:59)
	at io.vertx.core.impl.AbstractContext.schedule(AbstractContext.java:94)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:84)
	at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:144)
	at io.vertx.core.Promise.complete(Promise.java:67)
	at io.vertx.core.Promise.handle(Promise.java:52)
	at io.vertx.core.Promise.handle(Promise.java:30)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:181)
	at io.vertx.core.impl.AbstractContext.lambda$dispatch$0(AbstractContext.java:84)
	at io.vertx.core.impl.EventLoopContext.schedule(EventLoopContext.java:59)
	at io.vertx.core.impl.AbstractContext.schedule(AbstractContext.java:94)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:84)
	at io.vertx.core.impl.SucceededFuture.onComplete(SucceededFuture.java:49)
	at io.vertx.core.Future.lambda$compose$2(Future.java:250)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:181)
	at io.vertx.core.impl.AbstractContext.lambda$dispatch$0(AbstractContext.java:84)
	at io.vertx.core.impl.EventLoopContext.schedule(EventLoopContext.java:59)
	at io.vertx.core.impl.AbstractContext.schedule(AbstractContext.java:94)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:84)
	at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:144)
	at io.vertx.core.Promise.complete(Promise.java:67)
	at io.vertx.core.Main.lambda$main$3(Main.java:24)
```

With a patch we are aiming to have instead:

```
java.lang.Exception
	at io.vertx.core.Main.lambda$main$2(Main.java:20)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:182)
	at io.vertx.core.impl.AbstractContext.lambda$emit$0(AbstractContext.java:85)
	at io.vertx.core.impl.EventLoopContext.schedule(EventLoopContext.java:59)
	at io.vertx.core.impl.AbstractContext.schedule(AbstractContext.java:95)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:85)
	at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:92)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:149)
	at io.vertx.core.impl.future.ComposeTransformer$1.onSuccess(ComposeTransformer.java:47)
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:57)
	at io.vertx.core.impl.future.ComposeTransformer.onSuccess(ComposeTransformer.java:28)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:149)
	at io.vertx.core.impl.future.ComposeTransformer$1.onSuccess(ComposeTransformer.java:47)
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:57)
	at io.vertx.core.impl.future.ComposeTransformer.onSuccess(ComposeTransformer.java:28)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:149)
	at io.vertx.core.Promise.complete(Promise.java:67)
	at io.vertx.core.Main.lambda$main$3(Main.java:24)
```

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/tree/future-composition-flow

**Comment by vietj** [comment]
https://github.com/eclipse-vertx/vert.x/pull/3535
