### ISSUE TITLE
Error 500 when trying to call GraphQL subscription query

### ISSUE THREAD

**Issue by FelixGaebler** [eclipse-vertx/vert.x#3557]
### Version

Which version(s) did you encounter this bug ?
- io.vertx:vertx-core:3.9.2
- io.vertx:vertx-web-graphql:3.9.2
- com.graphql-java:graphql-java:15.0

### Context

Trying to implement a GraphQL subscription I'm getting the following error when executing the query (and recieving a 500)
```java
Exception in thread "vert.x-eventloop-thread-1":
java.util.concurrent.CompletionException: io.vertx.core.json.EncodeException: Failed to encode as JSON: No serializer found for class graphql.execution.reactive.CompletionStageMappingPublisher and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.LinkedHashMap["data"])
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at io.vertx.ext.web.handler.graphql.impl.GraphQLHandlerImpl.lambda$null$9(GraphQLHandlerImpl.java:288)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.vertx.core.json.EncodeException: Failed to encode as JSON: No serializer found for class graphql.execution.reactive.CompletionStageMappingPublisher and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.LinkedHashMap["data"])
	at io.vertx.core.json.jackson.JacksonCodec.toBuffer(JacksonCodec.java:176)
	at io.vertx.core.json.JsonObject.toBuffer(JsonObject.java:832)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 14 more
```

### Here is some code to reproduce

```java
import io.reactivex.rxjava3.core.BackpressureStrategy;
import io.reactivex.rxjava3.core.Flowable;
import io.reactivex.rxjava3.subjects.PublishSubject;

PublishSubject<Sign> provider = PublishSubject.create();
Flowable<Sign> publisher = provider.toFlowable(BackpressureStrategy.BUFFER);

RuntimeWiring runtimeWiring = RuntimeWiring.newRuntimeWiring()
        .type("Subscription", wiring -> wiring
            .dataFetcher("subscribeSigns", environment -> publisher)
         ).build();

provider.onNext(obj);
```

**Comment by tsegismont** [comment]
It seems you are trying to execute a subscription on the regular GraphQL handler, which does not support it. You need to enable the ApolloWS transport for this. See https://vertx.io/docs/vertx-web-graphql/java/#_apollo_websocketlink

**Comment by FelixGaebler** [comment]
I actually did. I should have provided more code.

```
/* Initialise vertx instance */
Vertx vertx = Vertx.vertx();
HttpServerOptions options = new HttpServerOptions().addWebSocketSubProtocol("graphql-ws");
HttpServer server = vertx.createHttpServer(options);
Router router = Router.router(vertx);

/* Add cors header for GraphQL client */
router.route().handler(BodyHandler.create());
router.route().handler(CorsHandler.create("*")
     .allowedHeader("Access-Control-Allow-Origin")
     .allowedHeader("Access-Control-Allow-Headers")
     .allowedHeader("Content-Type"));

/* Custom error handler */
router.errorHandler(500, rc -> ModuleLoader.catchException("Vert.x failed to handle request.", rc.failure()));

/* GraphQL server inclusive websocket subscriptions */
router.route("/graphql").handler(ApolloWSHandler.create(graphQL));   router.route("/graphql").handler(GraphQLHandler.create(graphQL));

/* Static handling of client and GraphQL playground */
router.route("/client/*").handler(StaticHandler.create().setWebRoot("webroot/client"));
router.route("/playground").handler(StaticHandler.create().setWebRoot("webroot/playground.html"));

server.requestHandler(router).listen(port);
```

**Comment by tsegismont** [comment]
Then please share a runnable project with reproduction steps. I'm curious in particular how the service is called given the stack trace shows the GraphQL handler is invoked:

```
io.vertx.ext.web.handler.graphql.impl.GraphQLHandlerImpl.lambda$null$9(GraphQLHandlerImpl.java:288)
```

**Comment by FelixGaebler** [comment]
So here is a repository (had to remove the code from the project since I cannot share the project)
https://github.com/FelixGaebler/VertxIssue-3557

If you run the subscription query in postman it will fail
![image](https://user-images.githubusercontent.com/51529181/92456266-fd123600-f1c2-11ea-96e9-37582bfd9250.png)

**Comment by FelixGaebler** [comment]
@tsegismont it does kinda work in the playground enviroment... but the  connection closes after some seconds - Im using it with a react-native app and apollo client, which got the same problem as postman

**Comment by tsegismont** [comment]
@FelixGaebler to my knowledge, postman doesn't support executing subscriptions over the apollo-ws protocol.

The reproducer project doesn't use the Apollo WS Client. How is it configured in your real project?
See https://www.apollographql.com/docs/link/links/ws/

**Comment by FelixGaebler** [comment]
This are the related snippets:
```JS
const client = new ApolloClient({ uri: 'http://localhost:8080/graphql' })  
```

```JSX
<ApolloProvider client={client}>
</ApolloProvider>
```

```JS
import gql from 'graphql-tag'
import { useSubscription } from '@apollo/react-hooks'

const subscription = gql`
    subscription Test {
        subscribeSigns {
            name
            frames {
                line0
                line1
                line2
                line3
            }
        }
    }
`

const { error:subscriptionError, data:subscriptionData } = useSubscription(subscription)
```

I didnt know yet there is a `SubscriptionClient`, I will give it a try and hope that the exception was not missleading me too far.

**Comment by FelixGaebler** [comment]
Well, this was totally the issue. Thanks for your help and sorry for wrong context!
