### ISSUE TITLE
HTTP server response methods impacting the response head should be guarded against head sent

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vert.x#3568]
There are a few methods impacting the HTTP response head (like `setStatusCode(int)`), such methods should throw an exception when the response head has already been written.

**Comment by leolux** [comment]
This prevents Server Sents Events to initialize in my case. The server needs to respond with the header "Content-Type: text/event-stream" for the SSE handshake to setup. The TCP connection used by the browser/client already is reused for the SSE stream.

**Comment by leolux** [comment]
Even worse is that a call to "route.next()" leads to "setStatusCode(200)" which checks for the "headWritten" flag which in turn results in this stacktrace:

```java.lang.IllegalStateException: Header already sent
	at io.vertx.core.http.impl.Http2ServerResponseImpl.checkHeadWritten(Http2ServerResponseImpl.java:143)
	at io.vertx.core.http.impl.Http2ServerResponseImpl.setStatusCode(Http2ServerResponseImpl.java:171)
	at io.vertx.ext.web.impl.RoutingContextImplBase.unhandledFailure(RoutingContextImplBase.java:192)
	at io.vertx.ext.web.impl.RoutingContextImplBase.handleInHandlerRuntimeFailure(RoutingContextImplBase.java:171)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:136)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.vertx.ext.web.impl.RoutingContextImpl.doFail(RoutingContextImpl.java:483)
	at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:172)
	at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:165)
	at io.vertx.ext.web.impl.RoutingContextImplBase.handleInHandlerRuntimeFailure(RoutingContextImplBase.java:165)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:136)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.lambda$authorizeUser$3(AuthHandlerImpl.java:223)
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.lambda$authorize$0(AuthHandlerImpl.java:89)
	at io.vertx.ext.auth.AbstractUser.isAuthorized(AbstractUser.java:47)
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.authorize(AuthHandlerImpl.java:102)
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.authorizeUser(AuthHandlerImpl.java:217)
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.handle(AuthHandlerImpl.java:125)
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.handle(AuthHandlerImpl.java:39)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.vertx.ext.web.handler.impl.UserSessionHandlerImpl.handle(UserSessionHandlerImpl.java:70)
	at io.vertx.ext.web.handler.impl.UserSessionHandlerImpl.handle(UserSessionHandlerImpl.java:29)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.lambda$handle$0(SessionHandlerImpl.java:179)
	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.lambda$doGetSession$2(SessionHandlerImpl.java:210)
	at io.vertx.ext.web.sstore.impl.LocalSessionStoreImpl.get(LocalSessionStoreImpl.java:88)
	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.doGetSession(SessionHandlerImpl.java:195)
	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.getSession(SessionHandlerImpl.java:190)
	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.handle(SessionHandlerImpl.java:136)
	at io.vertx.ext.web.handler.impl.SessionHandlerImpl.handle(SessionHandlerImpl.java:36)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
	at io.vertx.ext.web.handler.impl.CookieHandlerImpl.handle(CookieHandlerImpl.java:39)
	at io.vertx.ext.web.handler.impl.CookieHandlerImpl.handle(CookieHandlerImpl.java:35)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:128)
```
