### ISSUE TITLE
httpclient connectTimeout does not work expected

### ISSUE THREAD

**Issue by jinwik** [eclipse-vertx/vert.x#3805]
### Questions

 httpclient sets `connecttimeout`, when the connection fails (possibly due to network jitter or upstream performance issues), the duration of connect failed callback may be less than the `connecttimeout`.

CircuitBreaker '****' recorded an error: 'io.netty.channel.ConnectTimeoutException: connection timed out: ***/**'. Elapsed time: 1 ms
io.netty.channel.ConnectTimeoutException: connection timed out: **
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

### Version

3.6.x - 3.9.x

### Do you have a reproducer?

https://gist.github.com/jinwik/569938388962a457a93ee87d9b9c6732

**Comment by jinwik** [comment]
update the reproducer

**Comment by rusuionut** [comment]
+1 for this issue, we're reproducing this more in Microsoft Azure cloud and less in AWS. We configured the timeout to be at 10 seconds and we get the error after 200/300ms sometimes. Thanks.

**Comment by vietj** [comment]
can you elaborate more precisely what the issue is ?

**Comment by jinwik** [comment]
vertx httpclient or webclient sets the connection timeout, for example 5 seconds, sometimes it failed and  throws _io.netty.channel.ConnectTimeoutException_ but the whole request time is much less than the configured value, for example 1ms, it is so weird.

**Comment by betanumeric** [comment]
I'm seeing this as well with `setConnectTimeout(2000)` and actual timeouts sometimes taking less than 300ms.

**Comment by vietj** [comment]
I think in 4.1 we should add a connection acquisition timeout and have the global timeout only for the HTTP request operation, now this is possible with the new pool implementation.

**Comment by vietj** [comment]
I am not able to reproduce this with this reproducer locally, can you check this still applies with latest vertx 4?

**Comment by vietj** [comment]
other than that, it seems to be a netty issue

**Comment by jnbdz** [comment]
Looked into this: it is a Vert.x 3.x pool behaviour and it no longer happens in 4.x / 5.x.

In 3.9, `Pool#connectFailed` does `waitersQueue.poll()` and fails whichever request is at the head of the waiters queue, not the request whose connect attempt actually timed out. Under load, an attempt started at t0 fails at t0 + connectTimeout and is delivered to a request that joined the queue later, which then observes a `ConnectTimeoutException` well under the configured timeout — the `unexpected timeout: 21/23/28ms` lines of the reproducer.

The pool rewrite in 4.0 (`SimpleConnectionPool`) delivers a connect failure only to the waiter that initiated that connect. With the reproducer's setup (server accept queue saturated so that connects hang, `connectTimeout=100`, 150 concurrent requests, pool of 200 and pool of 20 so that requests queue), on 4.5.30 and on current master every failure is a `ConnectTimeoutException` observed at >= 100 ms from the request start (3000 and 1500 samples per configuration, none earlier).

So I think this can be closed as fixed by the 4.x pool.
