### ISSUE TITLE
JsonParser NullPointerException

### ISSUE THREAD

**Issue by egorapolonov** [eclipse-vertx/vert.x#3822]
### Version

4.0.0-4.0.3-SNAPSHOT

### Context

I used JsonParser.pause() and JsonParser.resume() methods between time-consuming operations with Vert.X v. 3.9.4. 
Since I upgraded to v. 4.0.0 I started to get NullPointerException. 
I've checked out latest snapshot version 4.0.3 but the problem is still there.

### Do you have a reproducer?

* Link to github project/gist

https://github.com/egorapolonov/vertx-4.0.0-jsonparser-issue/tree/master/vertx-4.0.0-jsonparser-issue
See **JsonParserAsyncFileTest.java**

### Steps to reproduce

1. Try to parse JSON structure like "{...}{...}...{...}"
2. Have more than 2 objects there in JSON
3. See errors

 ``` 
java.lang.NullPointerException: Cannot invoke "io.vertx.core.parsetools.impl.JsonParserImpl$TokenParser.close()" because "this.buffer" is null
	at io.vertx.core.parsetools.impl.JsonParserImpl$BufferingHandler.handle(JsonParserImpl.java:433)
	at io.vertx.core.parsetools.impl.JsonParserImpl$BufferingHandler.handle(JsonParserImpl.java:388)
	at io.vertx.core.parsetools.impl.JsonParserImpl.checkPending(JsonParserImpl.java:241)
	at io.vertx.core.parsetools.impl.JsonParserImpl.fetch(JsonParserImpl.java:84)
	at io.vertx.core.parsetools.impl.JsonParserImpl.resume(JsonParserImpl.java:74)
	at com.vertx.reproducer.JsonParserAsyncFileTest.lambda$parseWithExceptionHandler$0(JsonParserAsyncFileTest.java:58)
	at io.vertx.core.parsetools.impl.JsonParserImpl.handleEvent(JsonParserImpl.java:121)
	at io.vertx.core.parsetools.impl.JsonParserImpl.lambda$objectValueMode$2(JsonParserImpl.java:285)
	at io.vertx.core.parsetools.impl.JsonParserImpl$BufferingHandler.handle(JsonParserImpl.java:432)
	at io.vertx.core.parsetools.impl.JsonParserImpl$BufferingHandler.handle(JsonParserImpl.java:388)
	at io.vertx.core.parsetools.impl.JsonParserImpl.checkPending(JsonParserImpl.java:241)
	at io.vertx.core.parsetools.impl.JsonParserImpl.fetch(JsonParserImpl.java:84)
	at io.vertx.core.parsetools.impl.JsonParserImpl.resume(JsonParserImpl.java:74)
	at com.vertx.reproducer.JsonParserAsyncFileTest.lambda$parseWithExceptionHandler$0(JsonParserAsyncFileTest.java:58)
	at io.vertx.core.parsetools.impl.JsonParserImpl.handleEvent(JsonParserImpl.java:121)
	at io.vertx.core.parsetools.impl.JsonParserImpl.lambda$objectValueMode$2(JsonParserImpl.java:285)
	at io.vertx.core.parsetools.impl.JsonParserImpl$BufferingHandler.handle(JsonParserImpl.java:432)
	at io.vertx.core.parsetools.impl.JsonParserImpl$BufferingHandler.handle(JsonParserImpl.java:388)
	at io.vertx.core.parsetools.impl.JsonParserImpl.checkPending(JsonParserImpl.java:241)
	at io.vertx.core.parsetools.impl.JsonParserImpl.handle(JsonParserImpl.java:207)
	at io.vertx.core.parsetools.impl.JsonParserImpl.handle(JsonParserImpl.java:41)
	at io.vertx.core.file.impl.AsyncFileImpl.handleBuffer(AsyncFileImpl.java:425)
	at io.vertx.core.file.impl.AsyncFileImpl.lambda$new$0(AsyncFileImpl.java:110)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
	at io.vertx.core.file.impl.AsyncFileImpl.lambda$doRead$5(AsyncFileImpl.java:407)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:125)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:53)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)

Feb 23, 2021 10:20:27 PM com.vertx.reproducer.JsonParserAsyncFileTest
INFO: Successfully parsed 4 items of 4

Process finished with exit code 255
```

### Extra

* Ubuntu 20.04 x86_64, JVM openjdk-15.0.1

**Comment by vietj** [comment]
thanks for the reproducer
