### ISSUE TITLE
SQLException: Unsupported feature: getMetaData with the new vertx-jdbc-client with Oracle DB 11g

### ISSUE THREAD

**Issue by yazalulloa** [eclipse-vertx/vert.x#3858]
Vertx version: 4.0.3
Java 11
Running in Intellij 
Windows 10

I'm using Oracle DB 11g 

To connect to it I'm using: 

 <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc11-production</artifactId>
            <version>21.1.0.0</version>
            <type>pom</type>
        </dependency>

I tried the ojdbc8-production and still gave me the same error

Executing either a SELECT or a DELETE with a where clause it triggers this exception:

java.sql.SQLException: Unsupported feature: getMetaData
	at oracle.jdbc.driver.ArrayDataResultSet.getMetaData(ArrayDataResultSet.java:1098)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getMetaData(NewProxyResultSet.java:987)
	at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decodeReturnedKeys(JDBCQueryAction.java:182)
	at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decode(JDBCQueryAction.java:70)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:69)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:39)
	at io.vertx.ext.jdbc.impl.JDBCConnectionImpl.lambda$schedule$3(JDBCConnectionImpl.java:217)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:179)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:177)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

I found this that could explain why is happening https://coderanch.com/t/681925/databases/executing-reading-results-Stored-Procedure

The legacy client does work btw

To reproduce it:

Here is a docker-compose for the database: 

version: '3'
services:

  oracle-db:
    container_name: oracle-db
    image: wnameless/oracle-xe-11g-r2:latest
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
    ports:
      - "1521:1521"
      - "8080:8080"

Table: 

CREATE TABLE product (id VARCHAR2(20) NOT NULL, name VARCHAR2(100) NOT NULL, url VARCHAR2(100), company VARCHAR2(100), area VARCHAR2(100), category VARCHAR2(100), channel VARCHAR2(10), active NUMBER(1,0) NOT NULL, CONSTRAINT product_pk PRIMARY KEY (id) );

The configuration config: 

  driver_class: oracle.jdbc.driver.OracleDriver
  user: system
  password: oracle
  url: jdbc:oracle:thin:@{local ip}:1521:xe
  max_pool_size: 15
  initial_pool_size: 3
  min_pool_size: 1
  max_statements: 0
  max_statements_per_connection: 0
  max_idle_time: 60

Code:

`final var pool = JDBCPool.pool(vertx, config());

final var id = "test";
pool.preparedQuery("DELETE FROM product WHERE id = ?")
                    .execute(Tuple.of(id), ar -> {
                        if (ar.failed()) {
                            System.out.println("ERROR");
                            ar.cause().printStackTrace();
                            
                        } else {
                            System.out.println("SUCESS");
                            System.out.println(ar.result());
                        }

                    });`

**Comment by d53dave** [comment]
Hi, I just ran into the same problem (both Oracle 12 and Oracle 19).

I was quite confused why this is happening, but I think it boils down to this:
If I try to execute a `preparedStatement` that doesn't have any bind variables, such as 

```sql
SELECT col1, col2 from table
```

then the above error is thrown. 
it works fine for me if I have bind vars, i.e. inserts, deletes

**Comment by vietj** [comment]
can you reopen this issue in https://github.com/vert-x3/vertx-jdbc-client ?

**Comment by yazalulloa** [comment]
> can you reopen this issue in https://github.com/vert-x3/vertx-jdbc-client ?

Done https://github.com/vert-x3/vertx-jdbc-client/issues/222
