### ISSUE TITLE
Exceptions after updating to 4.0.3 under load

### ISSUE THREAD

**Issue by underkin** [eclipse-vertx/vert.x#3859]
Hi,

Under high load, and after updating to 4.0.3 I'm seeing the following error in the logs, which I don't know where it's coming from or how to isolate to reproduce.

```
java.lang.IllegalStateException: Result is already complete
	at io.vertx.core.Promise.complete(Promise.java:67)
	at io.vertx.core.eventbus.impl.ReplyHandler.dispatch(ReplyHandler.java:94)
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.next(HandlerRegistration.java:163)
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.dispatch(HandlerRegistration.java:128)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:107)
	at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:104)
	at io.vertx.core.eventbus.impl.ReplyHandler.doReceive(ReplyHandler.java:75)
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

The service in questions does a high number of HTTP client request and the services on the other side may fail from time to time. Don't know if this is somehow related, but wondering that this exception actually means and if it is harmful or not.

Thanks in avance

Env Details: Vertx 4.0.3,  JDX 11, groovy

**Comment by vietj** [comment]
I am suspecting that under high load, the reply exceeded the message reply timeout and therefore we should use `tryComplete` instead of `complete` when it happens.

Can you check whether you have timeout failures ?

**Comment by underkin** [comment]
I have timeout of 2 minutes, but I am pretty sure some can exceed the 2 minutes timeout. 
Actually if was 30 seconds before and was much more evident. I updated to 120 and that is now less frequent, but still there. 
Is there any side effect and if so how can I prevent it?

Thanks

**Comment by vietj** [comment]
can you modify vertx source code (for checking) and change the line 94 in ReplyHandler to use `tryComplete` instead of `complete`

**Comment by underkin** [comment]
Will try

**Comment by vietj** [comment]
I've been able to reproduce it locally and it happens when the consumer replies when the request timeout happens: the ephemeral reply handler it still registered, the timeout has been fired and the actual replies wants to complete the handler.

```java
  @Repeat(times = 1000)
  @Test
  public void testRace() {
    MessageConsumer<String> reg = eb.<String>consumer(ADDRESS1, msg -> {
      vertx.setTimer(8, id -> {
        msg.reply("pong");
      });
    });
    eb.request(ADDRESS1, "ping", new DeliveryOptions().setSendTimeout(10), ar -> {
      testComplete();
    });
    await();
  }
```

**Comment by underkin** [comment]
I was in the process of testing is already.
Will you include in 4.0..4-SNAPSHOT build?

**Comment by vietj** [comment]
yes it will be part of 4.0.4 snapshots when the PR will be submitted and reviewed.
