### ISSUE TITLE
Blocked thread anomaly

### ISSUE THREAD

**Issue by peter-jacobs-tpl** [eclipse-vertx/vert.x#3860]
The following message implies the thread has been blocked for several times longer than the JRE has been running.  

Vertx version: 3.9.6
Java version : 1.8.0_201
Java vendor  : Oracle Corporation

Thread[vert.x-worker-thread-0,5,main]=Thread[vert.x-worker-thread-0,5,main] has been blocked for 97366908 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.LinkedTransferQueue.awaitMatch(LinkedTransferQueue.java:737)
	at java.util.concurrent.LinkedTransferQueue.xfer(LinkedTransferQueue.java:647)
	at java.util.concurrent.LinkedTransferQueue.take(LinkedTransferQueue.java:1269)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vietj** [comment]
did it happen once or several times ?
