### ISSUE TITLE
Cannot invoke Http1xServerRequest.metric() because "request" is null

### ISSUE THREAD

**Issue by synth3** [eclipse-vertx/vert.x#3897]
### Version

4.0.3

### Context

In the logs of one server instance (that hosts a vertx-web based rest api) i see the following NPE every second with some pauses in between where the exception is not logged:

```
ContextImpl       vert.x-eventloop-thread-4  Unhandled exception
java.lang.NullPointerException: Cannot invoke "io.vertx.core.http.impl.Http1xServerRequest.metric()" because "request" is null
    at io.vertx.core.http.impl.Http1xServerConnection.reportResponseComplete(Http1xServerConnection.java:260)
    at io.vertx.core.http.impl.Http1xServerConnection.responseComplete(Http1xServerConnection.java:206)
    at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:409)
    at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:388)
    at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:444)
    at io.vertx.core.streams.impl.PipeImpl.handleSuccess(PipeImpl.java:116)
    at io.vertx.core.streams.impl.PipeImpl.lambda$to$2(PipeImpl.java:102)
    at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124)
    at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
    at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179)
    at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
    at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
    at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59)
    at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76)
    at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:250)
    at io.vertx.core.http.impl.Http2ClientConnection$StreamImpl.handleEnd(Http2ClientConnection.java:433)
    at io.vertx.core.http.impl.VertxHttp2Stream.lambda$new$1(VertxHttp2Stream.java:62)
    at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
    at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
    at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:52)
    at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:194)
    at io.vertx.core.http.impl.VertxHttp2Stream.onEnd(VertxHttp2Stream.java:134)
    at io.vertx.core.http.impl.Http2ClientConnection$Stream.onEnd(Http2ClientConnection.java:277)
    at io.vertx.core.http.impl.VertxHttp2Stream.onEnd(VertxHttp2Stream.java:129)
    at io.vertx.core.http.impl.Http2ConnectionBase.onDataRead(Http2ConnectionBase.java:316)
    at io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:36)
    at io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49)
    at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:318)
    at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422)
    at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
    at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
    at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:181)
    at io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
    at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
    at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
    at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.channelRead(VertxHttp2ConnectionHandler.java:376)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1534)
    at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1283)
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1330)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:832)
```

As the StackTrace contains only classes from vertx and netty I don't know what to do about it or what might cause it, and as it's a NPE I think it might be interesting.

### Extra

Windows Server 2019
AdoptOpenJDK 15.0.1

**Comment by vietj** [comment]
do you have a reproducer for this ?

**Comment by synth3** [comment]
Thanks a lot for looking into that!

Short answer: I have no idea how. :(

The situation can only be observed on one of many similar installations of a pretty complex software and we have no clue what causes this as there is no message or StackTrace-element we could use to track down to our configuration and/or code.

Please let me know if you have any hints about how we could provide additional useful information.

**Comment by liubao68** [comment]
I met this problem too. After chagned netty from 4.1.62.Final to 4.1.60.Final. This problem disapears. 

And this problem is quite similiar to https://github.com/eclipse-vertx/vert.x/issues/3899. When this problem happens 

```
if (request.decoderResult() != DecoderResult.SUCCESS) {
```

decoderResult is `success` and statement got true.

**Comment by vietj** [comment]
thanks for the details @liubao68

**Comment by vietj** [comment]
can you check with 4.1.0.CR1?

**Comment by liubao68** [comment]
I tested for 4.1.0.CR1 and netty 4.1.65.Final, the problem is fixed.

**Comment by vietj** [comment]
thanks, it was the side effect of using a netty version using an incompatible change.
