### ISSUE TITLE
Vert.x IO threads ending up with null TCCL

### ISSUE THREAD

**Issue by stuartwdouglas** [eclipse-vertx/vert.x#3900]
### Version

4.0.3

### Context
We noticed an odd ClassLoading failure when running the MP Rest Client TCK against Resteasy Reactive, on investigation it turned out that the TCCL of the Vert.x thread was null.

### Do you have a reproducer?

If you checkout Quarkus you can uncomment microprofile-rest-client-reactive in tcks/pom.xml and run e.g.

`mvn clean install -Ptcks -pl tcks,tcks/microprofile-rest-client-reactive -Dtest=SslMutualTest`

If you debug and set a breakpoint for ServiceConfigurationError you will see the TCCL is null. If you set `<vertx.disableTCCL>true</vertx.disableTCCL>` the test will pass.

### Extra

The offending code seems to be in io.vertx.core.impl.AbstractContext#endDispatch(), which will null out the TCCL if the previous context is null, instead of returning it to the previous value.

**Comment by vietj** [comment]
do you mean that endDispatch should be modified like

```java
if (!DISABLE_TCCL && previous != null) {
  th.setContextClassLoader(previous.classLoader());
}
```

**Comment by stuartwdouglas** [comment]
That would help I guess. I think the real issue though is that in AbstractContext#beginDispatch() if prev is null then the current TCCL is basically thrown away, ideally there would be some way to restore it.

**Comment by vietj** [comment]
gotcha, I see now what you mean

**Comment by vietj** [comment]
can you provide a stack trace of the caller when this happen ?

**Comment by vietj** [comment]
this happens with the classloader of a non vertx thread ? (I'm assuming not)

**Comment by stuartwdouglas** [comment]
It's only an issue for Vert.x threads:

```
Caused by: java.util.ServiceConfigurationError: javax.json.bind.spi.JsonbProvider: org.eclipse.yasson.JsonBindingProvider not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1237)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at javax.json.bind.spi.JsonbProvider.provider(JsonbProvider.java:88)
	at javax.json.bind.JsonbBuilder.create(JsonbBuilder.java:100)
	at io.quarkus.jsonb.JsonbProducer.jsonb(JsonbProducer.java:31)
	at io.quarkus.jsonb.JsonbProducer_ProducerMethod_jsonb_6145214bda7188823ccf0399aafd9d4c8249722d_Bean.create(JsonbProducer_ProducerMethod_jsonb_6145214bda7188823ccf0399aafd9d4c8249722d_Bean.zig:170)
	at io.quarkus.jsonb.JsonbProducer_ProducerMethod_jsonb_6145214bda7188823ccf0399aafd9d4c8249722d_Bean.create(JsonbProducer_ProducerMethod_jsonb_6145214bda7188823ccf0399aafd9d4c8249722d_Bean.zig:185)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
	at io.quarkus.jsonb.JsonbProducer_ProducerMethod_jsonb_6145214bda7188823ccf0399aafd9d4c8249722d_Bean.get(JsonbProducer_ProducerMethod_jsonb_6145214bda7188823ccf0399aafd9d4c8249722d_Bean.zig:217)
	at io.quarkus.jsonb.JsonbProducer_ProducerMethod_jsonb_6145214bda7188823ccf0399aafd9d4c8249722d_Bean.get(JsonbProducer_ProducerMethod_jsonb_6145214bda7188823ccf0399aafd9d4c8249722d_Bean.zig:233)
	at io.quarkus.resteasy.reactive.jsonb.runtime.serialisers.JsonbMessageBodyReader_Bean.create(JsonbMessageBodyReader_Bean.zig:205)
	at io.quarkus.resteasy.reactive.jsonb.runtime.serialisers.JsonbMessageBodyReader_Bean.get(JsonbMessageBodyReader_Bean.zig:242)
	at io.quarkus.resteasy.reactive.jsonb.runtime.serialisers.JsonbMessageBodyReader_Bean.get(JsonbMessageBodyReader_Bean.zig:277)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:430)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:443)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:266)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:263)
	at io.quarkus.arc.runtime.BeanContainerImpl$1.create(BeanContainerImpl.java:35)
	at io.quarkus.resteasy.reactive.common.runtime.ArcBeanFactory.createInstance(ArcBeanFactory.java:25)
	at org.jboss.resteasy.reactive.common.model.ResourceReader.instance(ResourceReader.java:71)
	at org.jboss.resteasy.reactive.common.core.Serialisers.readerLookup(Serialisers.java:106)
	at org.jboss.resteasy.reactive.common.core.Serialisers.findReaders(Serialisers.java:79)
	at org.jboss.resteasy.reactive.client.impl.ClientReaderInterceptorContextImpl.proceed(ClientReaderInterceptorContextImpl.java:49)
	at org.jboss.resteasy.reactive.client.impl.ClientSerialisers.invokeClientReader(ClientSerialisers.java:132)
	at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext.readEntity(RestClientRequestContext.java:118)
	at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.mapToResponse(ClientResponseCompleteRestHandler.java:26)
	at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.handle(ClientResponseCompleteRestHandler.java:15)
	at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.handle(ClientResponseCompleteRestHandler.java:11)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:132)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by stuartwdouglas** [comment]
Maybe we need to update our code to not delegate to the event loop directly, but to go through Context?

**Comment by vietj** [comment]
@stuartwdouglas this way would work for sure, or when you run netty tasks directly then you need to manage your own classloader association like Vert.x task do ?

**Comment by stuartwdouglas** [comment]
Previously we just relied on the CL that was set when Vert.x was created, and had a hack for dev mode to replace the TCCL of the Vert.x threads.

**Comment by vietj** [comment]
I believe that a task running on the Netty event loop can set TCCL for the duration of the task (i.e it should be set when starting the task and be removed before leaving the task).

Vert.x does that, however it does not respect the existing TCCL and if something relies on the fact that the TCCL is set once and for all on the thread then indeed it is lost, e.g soemthing set the TCCL and assumes that tasks executed will get the same TCCL without the need to set it again.

I think Vert.x could respect the current TCCL when executing its own tasks too.

**Comment by vietj** [comment]
so to clarify, this test is currently modeling this situation:

```java
    ClassLoader cl = new URLClassLoader(new URL[0]);
    ContextInternal ctx = (ContextInternal) vertx.getOrCreateContext();
    EventLoop el = ctx.nettyEventLoop();
    el.execute(() -> {
      Thread.currentThread().setContextClassLoader(cl);
      ctx.runOnContext(v -> {
        el.execute(() -> {
          assertSame(cl, Thread.currentThread().getContextClassLoader());
          testComplete();
        });
      });
    });
    await();
```

**Comment by vietj** [comment]
@stuartwdouglas I think this would solve the issue https://github.com/eclipse-vertx/vert.x/pull/3901
