### ISSUE TITLE
EventBus cannot handle received message when using Future inside

### ISSUE THREAD

**Issue by zero88** [eclipse-vertx/vert.x#3921]
### Version

- `4.0.0`
- `4.0.2`
- `4.0.3`
- `4.1.0.Beta1`

### Context

I encountered an exception which looks suspicious while `executeBlocking` when handling received message in EventBus MessageConsumer

### Do you have a reproducer?

This is a test you can add it in [LocalEventBusTest](https://github.com/eclipse-vertx/vert.x/blob/970fdb84bfc8e596774007a6d6ba21cdba1f3791/src/test/java/io/vertx/core/eventbus/LocalEventBusTest.java)

```java
  @Test
  public void testFuture() throws IOException {
    String path = File.createTempFile("vertx", ".json").toPath().toString();
    Function<String, Buffer> data = d -> new JsonObject().put("key", d).toBuffer();
    System.out.println(path);
    eb.<String>consumer(ADDRESS1)
      .handler((Message<String> msg) -> vertx.executeBlocking(
        p -> p.handle(vertx.fileSystem().writeFile(path, data.apply(msg.body())).map(ignore -> path)),
        ar -> {
          if (ar.failed()) {
            System.out.println("FAILED: " + ar.cause());
            return;
          }
          msg.reply(ar.result());
        }));
    eb.request(ADDRESS1, "whatever", ar -> {
      assertTrue(ar.succeeded());
      assertEquals(path, ar.result().body());
      testComplete();
    });
    await();
  }
```

It is exception when I debug in **my project**, hope this help
```
java.util.concurrent.RejectedExecutionException: Task io.vertx.core.impl.TaskQueue$$Lambda$337/1063462894@6ccba607 rejected from java.util.concurrent.ThreadPoolExecutor@22ad0c08[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 13]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at io.vertx.core.impl.TaskQueue.execute(TaskQueue.java:93)
	at io.vertx.core.impl.ContextImpl.executeBlocking(ContextImpl.java:190)
	at io.vertx.core.impl.DuplicatedContext.executeBlockingInternal(DuplicatedContext.java:158)
	at io.vertx.core.file.impl.FileSystemImpl$BlockingAction.run(FileSystemImpl.java:1143)
	at io.vertx.core.file.impl.FileSystemImpl.writeFile(FileSystemImpl.java:428)
	at io.zero88.qwe.file.TextFileOperatorImpl.lambda$null$6(TextFileOperatorImpl.java:47)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179)
	at io.vertx.core.impl.future.Mapping.onSuccess(Mapping.java:40)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179)
	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179)
	at io.vertx.core.impl.future.Mapping.onSuccess(Mapping.java:40)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179)
	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179)
	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.SucceededFuture.addListener(SucceededFuture.java:82)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:43)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vietj** [comment]
I found that your code is incorrect:

`p.handle(vertx.fileSystem().writeFile(path, data.apply(msg.body())).map(ignore -> path))` tries the promise with an async result that is not completed.

instead the expression should be `vertx.fileSystem().writeFile(path, data.apply(msg.body())).map(ignore -> path).onComplete(p)`

**Comment by zero88** [comment]
ah, oh... I dont realize that :)

But, @vietj in `Promise` document, make me confuse a little bit.
> Represents the writable side of an action that may, or may not, have occurred yet.

Then I understand: `handle(AsyncResult<T> asyncResult)` can handle _an **action** may not have occurred yet_. `Action` here is `external action` - a `future`, not by `promise` itself.
Might be update doc, or one more effort make `handle(AsyncResult<T> asyncResult)` can handle `Future` that not yet completed by cast then do `onComplete`

**Comment by vietj** [comment]
I think hte main issue here is a design issue in vertx with Promise<T> that
implements Handler<AsyncResult<T>>

I think what we could do is add logging

public void handle(AsyncResult<T> asyncResult) {
    if (asyncResult.succeeded()) {
        this.complete(asyncResult.result());
    } else if (asyncResult.failed()) {
        this.fail(asyncResult.cause());
    } else {

        // WARN HERE

    }

}

**Comment by zero88** [comment]
I think the `Promise` design is correct.
The incorrect here should be `AsyncResult`. `AsyncResult` should have `isCompleted()`, it should be `completable`, if not it is a `Result`.
If make upper `isCompleted()` from `Future` to `AsyncResult`, it is nice, then `Promise.handle` can handle an event if not yet occurred. My solution is not yet cared about drawback of API changes. 
Your decision, you have a best view on that :smiley:

**Comment by vietj** [comment]
actually what is not correct is that Future<T> extends AsyncResult<T>
