### ISSUE TITLE
After uprading to 4.0.3 and above uploading multiple files using Pump will get data lost

### ISSUE THREAD

**Issue by liubao68** [eclipse-vertx/vert.x#3949]
### Questions
In our applicatioin, we all upload multiple files using http and using Pump to write contents to HttpClientRequest. And we upgrade from vert.x 3.9.4 to 4.0.3(also tried 4.1.0.RC1) the tests case fails randomly.  The updated code to write multiple files
to HttpClientRequest is:

```
  private void attachFile(String boundary, Iterator<Entry<String, Part>> uploadsIterator) {
    if (!uploadsIterator.hasNext()) {
      request.write(boundaryEndInfo(boundary));
      request.end();
      return;
    }
    Entry<String, Part> entry = uploadsIterator.next();
    // do not use part.getName() to get parameter name
    // because pojo consumer not easy to set name to part
    String name = entry.getKey();
    Part part = entry.getValue();
    String filename = part.getSubmittedFileName();

    LOGGER.info("Start attach file [{}:{}].", name, filename);
    request.write(fileBoundaryInfo(boundary, name, part)).compose(v ->
        Future.fromCompletionStage(new PumpFromPart(context, part).toWriteStream(request, throwableHandler)))
        .onComplete(r -> {
          if (r.failed()) {
            LOGGER.warn("Failed attach file [{}:{}].", name, filename, r.cause());
            asyncResp.consumerFail(r.cause());
            return;
          }

          LOGGER.info("Finish attach file [{}:{}].", name, filename);
          attachFile(boundary, uploadsIterator);
        });
  }
```

see details [here](https://github.com/apache/servicecomb-java-chassis/pull/2394/files#diff-eb2ba960b8188b577883b01315ac99bd4fd8531f5eb3d67a6e12a021498c1b30)

### Version

4.0.3 and above

### Context

After look code at PumpIml 

```
  PumpImpl(ReadStream<T> rs, WriteStream<T> ws) {
    this.readStream = rs;
    this.writeStream = ws;
    drainHandler = v-> readStream.resume();
    dataHandler = data -> {
      writeStream.write(data);
      incPumped();
      if (writeStream.writeQueueFull()) {
        readStream.pause();
        writeStream.drainHandler(drainHandler);
      }
    };
  }
```

I guess the problem happends because vert.x 4.x change 

```
writeStream.write(data);
```

to asynchronouse and not make sure if the data is actually written. And in our context, previously we check if a file successfully by ReadStream endHanlder, now the check can not make sure if the upload is successfully and cause the problem. 

### Do you have a reproducer?

see questions.

### Steps to reproduce

see questions.

**Comment by vietj** [comment]
can you provide a reproducer project ?

**Comment by liubao68** [comment]
It's a bit hard to easily to reproduce it. I am working on it and try get more info. The anaylse in question may be not correct, and each time the failed error is a bit diffrent. I need trying more. 

Some times I got this error, this seams that data is not written in the sequence of calling request.write

````
2021-05-27 20:53:07,579 [ERROR] [transport-vert.x-eventloop-thread-5][] - http server failed. (VertxRestDispatcher.java:87)
java.lang.IndexOutOfBoundsException: index: 146, length: 1 (expected: range(0, 146))
        at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1390)
        at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1397)
        at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1384)
        at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1379)
        at io.netty.buffer.UnpooledUnsafeHeapByteBuf.getByte(UnpooledUnsafeHeapByteBuf.java:44)
        at io.netty.handler.codec.http.multipart.HttpPostBodyUtil.findDelimiter(HttpPostBodyUtil.java:238)
        at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.loadDataMultipartOptimized(HttpPostMultipartRequestDecoder.java:1172)
        at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.decodeMultipart(HttpPostMultipartRequestDecoder.java:559)
        at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.findMultipartDisposition(HttpPostMultipartRequestDecoder.java:802)
        at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.decodeMultipart(HttpPostMultipartRequestDecoder.java:511)
        at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.findMultipartDelimiter(HttpPostMultipartRequestDecoder.java:663)
        at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.decodeMultipart(HttpPostMultipartRequestDecoder.java:498)
        at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.parseBodyMultipart(HttpPostMultipartRequestDecoder.java:463)
        at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.parseBody(HttpPostMultipartRequestDecoder.java:432)
        at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:347)
        at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:54)
        at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:223)
        at io.vertx.core.http.impl.Http1xServerRequest.onData(Http1xServerRequest.java:521)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:70)
        at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:178)
        at io.vertx.core.http.impl.Http1xServerRequest.handleContent(Http1xServerRequest.java:145)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:70)
        at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:178)
        at io.vertx.core.http.impl.Http1xServerConnection.onContent(Http1xServerConnection.java:183)
        at io.vertx.core.http.impl.Http1xServerConnection.handleOther(Http1xServerConnection.java:156)
        at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:144)
        at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:154)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
        at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServ
```

**Comment by liubao68** [comment]
Update.  Seems netty's bug. I debug and found when this problem happens, the server's Buffer has following content's and is not complete(not all contents are dilivered to server yet), and netty throws exception above. 

```
--boundary4f72de9e-d9aa-4299-829e-c5573163a306
Content-Disposition: form-data; name="str"

[some message]
--boundary4f72de9e-d9aa-4299-829e-c5573163a3
```

The complete content should be
```
--boundary4f72de9e-d9aa-4299-829e-c5573163a306
Content-Disposition: form-data; name="foo"

[some message]
--boundary4f72de9e-d9aa-4299-829e-c5573163a306
Content-Disposition: form-data; name="bar"

[some other message]
```

**Comment by vietj** [comment]
can you exhibit a reproducer with Netty only ?

**Comment by vietj** [comment]
do you have a reproducer project ?

**Comment by liubao68** [comment]
I sumit an issue to netty, and I see it is accepted and fixed.

**Comment by vietj** [comment]
can you link to the Netty bug ?

**Comment by liubao68** [comment]
I can see links above. And put it [here](https://github.com/netty/netty/issues/11334) too

**Comment by gregopet** [comment]
We're also hitting this bug, but as far as I can tell, this wasn't merged into any version of Vert.x 4 yet? Would it be safe if we tried forcing the Netty version from the build file?
