### ISSUE TITLE
Provide elliptic curve key delimiter execution path

### ISSUE THREAD

**Issue by fvaleri** [eclipse-vertx/vert.x#3962]
I tried to load an ECDSA key that is formatted using the following delimiter:
```
-----BEGIN EC PRIVATE KEY-----
... private key comes here ...
-----END EC PRIVATE KEY-----
```

This is what I'm getting as a result:
```log
2021-06-04 16:18:22,180 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.RuntimeException: Missing -----BEGIN PRIVATE KEY----- or -----BEGIN RSA PRIVATE KEY----- delimiter
	at io.vertx.core.net.impl.KeyStoreHelper.loadPrivateKey(KeyStoreHelper.java:274)
	at io.vertx.core.net.impl.KeyStoreHelper.loadKeyCert(KeyStoreHelper.java:238)
	at io.vertx.core.net.PemKeyCertOptions.getHelper(PemKeyCertOptions.java:447)
	at io.vertx.core.net.PemKeyCertOptions.getKeyManagerFactory(PemKeyCertOptions.java:465)
	at io.vertx.core.net.impl.SSLHelper.getKeyMgrFactory(SSLHelper.java:341)
	at io.vertx.core.net.impl.SSLHelper.createContext(SSLHelper.java:294)
	at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:511)
	at io.vertx.core.net.impl.SSLHelper.validate(SSLHelper.java:536)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:284)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:205)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:919)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:900)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

As you can see from the stack trace, this is from a Quarkus application that is running on `java-11-openjdk`.

```sh
$ mvn dependency:tree | grep vertx
[INFO] |  +- io.quarkus:quarkus-vertx-http:jar:1.13.3.Final:compile
[INFO] |  |  +- io.quarkus:quarkus-vertx-http-dev-console-runtime-spi:jar:1.13.3.Final:compile
[INFO] |  |  +- io.quarkus:quarkus-vertx-core:jar:1.13.3.Final:compile
[INFO] |  |  |  \- io.vertx:vertx-core:jar:3.9.6:compile
[INFO] |  |  \- io.vertx:vertx-web:jar:3.9.6:compile
[INFO] |  |     +- io.vertx:vertx-web-common:jar:3.9.6:compile
[INFO] |  |     +- io.vertx:vertx-auth-common:jar:3.9.6:compile
[INFO] |  |     \- io.vertx:vertx-bridge-common:jar:3.9.6:compile
[INFO] |  |  +- io.quarkus:quarkus-vertx-http-dev-console-spi:jar:1.13.3.Final:test
```

From the enhancement request #2547, I see that support for parsing ECDSA key is already there, so I guess it would be just a matter of adding the relevant [switch execution path](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java#L261).

**Comment by fvaleri** [comment]
Digging some more into this, I see that my application is being provided with the old version of the PKCS 8 format, which gives the following error on JDK 11.
```log
Running io.vertx.core.net.KeyStoreHelperTest
Starting test: KeyStoreHelperTest#testKeyStoreHelperSupportsECPrivateKeys
Starting test: KeyStoreHelperTest#testKeyStoreHelperSupportsRSAPrivateKeys
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.848 sec <<< FAILURE! - in io.vertx.core.net.KeyStoreHelperTest
testKeyStoreHelperSupportsECPrivateKeys(io.vertx.core.net.KeyStoreHelperTest)  Time elapsed: 0.606 sec  <<< ERROR!
io.vertx.core.VertxException: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException : version mismatch: (supported:     00, parsed:     01
	at java.base/sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:350)
	at java.base/sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:355)
	at jdk.crypto.ec/sun.security.ec.ECPrivateKeyImpl.<init>(ECPrivateKeyImpl.java:74)
	at jdk.crypto.ec/sun.security.ec.ECKeyFactory.implGeneratePrivate(ECKeyFactory.java:237)
	at jdk.crypto.ec/sun.security.ec.ECKeyFactory.engineGeneratePrivate(ECKeyFactory.java:165)
	at java.base/java.security.KeyFactory.generatePrivate(KeyFactory.java:390)
	at io.vertx.core.net.impl.KeyStoreHelper.lambda$loadPrivateKey$1(KeyStoreHelper.java:265)
	at io.vertx.core.net.impl.KeyStoreHelper.loadPems(KeyStoreHelper.java:335)
	at io.vertx.core.net.impl.KeyStoreHelper.loadPrivateKey(KeyStoreHelper.java:259)
	at io.vertx.core.net.impl.KeyStoreHelper.loadKeyCert(KeyStoreHelper.java:246)
	at io.vertx.core.net.PemKeyCertOptions.getHelper(PemKeyCertOptions.java:405)
	at io.vertx.core.net.KeyStoreHelperTest.testKeyStoreHelperSupportsECPrivateKeys(KeyStoreHelperTest.java:69)
```

If I convert that key to version 2, it works fine.
```
openssl pkcs8 -topk8 -inform pem -in tls.key -outform pem -nocrypt -out tls-new.key
```
