### ISSUE TITLE
NPE when trying to get body of a chunked HTTP response in client

### ISSUE THREAD

**Issue by silmeth** [eclipse-vertx/vert.x#4072]
### Version

4.1.2

### Context

I try to create a server streaming a chunked response, and test it using the Vertx HTTP client. The client throws `NullPointerException` on receiving response if no headers were added in the Request.

If any header is set, then the test hangs infinitely – the `HttpClientResponse` never ends and receives the body.

In the first case, this is the NPE’s stack trace:

<details>
<summary>NPE stack trace</summary>
<p>

```
Caused by: java.lang.NullPointerException
	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseBegin(Http1xClientConnection.java:747)
	at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:674)
	at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:649)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:155)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</p>
</details>

### Do you have a reproducer?
Here’s a simple test-case written in Kotlin, test without the header hack, with header hack to avoid NPE, and another one using async-http-client. Only the async-http-client one passes.

[silmeth/vertx-chunked-reproducer](https://github.com/silmeth/vertx-chunked-reproducer)

### Steps to reproduce

1. Clone the repo linked above.
2. Run `./gradlew test` from the repo’s directory.

The code is in [`src/test/kotlin/chunked/reproducer/ChunkedTest.kt`](https://github.com/silmeth/vertx-chunked-reproducer/blob/main/src/test/kotlin/chunked/reproducer/ChunkedTest.kt)

**Comment by vietj** [comment]
thanks for the reproducer, I'll look into it

**Comment by vietj** [comment]
there are two bugs to fix related to this PR, I'll provide a PR soonish

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/pull/4077
