### ISSUE TITLE
java.util.ConcurrentModificationException when creating localConsumer

### ISSUE THREAD

**Issue by neterium-dev** [eclipse-vertx/vert.x#4137]
### Version

4.1.5 (or 4.1.+)

### Context

Vertx is created with a Zookeeper Cluster manager, ZK 3.5 running locally.
If a create a set of verticles in which I setup a localConsumer in the start() method, I nearly always endup with a hidden exception:

`
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.vertx.spi.cluster.zookeeper.impl.SubsMapHelper.get(SubsMapHelper.java:107)
	at io.vertx.spi.cluster.zookeeper.impl.SubsMapHelper.fireRegistrationUpdateEvent(SubsMapHelper.java:196)
	at io.vertx.spi.cluster.zookeeper.impl.SubsMapHelper.put(SubsMapHelper.java:68)
	at io.vertx.spi.cluster.zookeeper.ZookeeperClusterManager.addRegistration(ZookeeperClusterManager.java:388)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.onLocalRegistration(ClusteredEventBus.java:143)
	at io.vertx.core.eventbus.impl.EventBusImpl.addRegistration(EventBusImpl.java:240)
	at io.vertx.core.eventbus.impl.HandlerRegistration.register(HandlerRegistration.java:68)
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.handler(MessageConsumerImpl.java:236)
	at io.vertx.core.eventbus.impl.EventBusImpl.localConsumer(EventBusImpl.java:178)
	at com.example.starter.TestVerticle.start(TestVerticle.java:9)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
`

As a consequence, some messages sent to the same local address endup with a timeout exception, probably because the handler is not correctly registered.

If I do not a ZK manager, no problem.
If I use consumer() instead of localConsumer(), no problem
If I create the localConsumer outside a verticle, no problem
Note that sending the messages from a new thread does not help

### Do you have a reproducer?

Please use the tiny java project attached:
[src.zip](https://github.com/eclipse-vertx/vert.x/files/7338909/src.zip)

### Steps to reproduce

- Setup a VertX cluster with ZK Manager
- Create a batch of verticles and create a localConsumer() in the start() method
- Send a batch of messages to those consumers

--> Seems to be introduced in 4.1.x, no problem with 4.0.3

Thanks,
Thomas

**Comment by vietj** [comment]
since when did you observe this issue @neterium ?

**Comment by neterium** [comment]
Hi @vietj , as soon as we upgraded from 4.0.3 to 4.1.x
