### ISSUE TITLE
IllegalStateException: File handle is closed

### ISSUE THREAD

**Issue by visualage** [eclipse-vertx/vert.x#4165]
### Questions

Unexpected error `IllegalStateException: File handle is closed`.

### Version

vert.x 4.1.4

### Context

We have a web server which is built on top of vertx-web. The web server uses `BodyHandler` to handle file uploads. It looks like if the upload is using HTTP/1.1 protocol, sometimes the following error occurs. It looks like the `AsyncFileImpl` was already closed when the `BodyHandlerImpl` tries to cancel the upload.

```
java.lang.IllegalStateException: File handle is closed
    at io.vertx.core.file.impl.AsyncFileImpl.checkClosed(AsyncFileImpl.java:544)
    at io.vertx.core.file.impl.AsyncFileImpl.check(AsyncFileImpl.java:539)
    at io.vertx.core.file.impl.AsyncFileImpl.drainHandler(AsyncFileImpl.java:271)
    at io.vertx.core.file.impl.AsyncFileImpl.drainHandler(AsyncFileImpl.java:54)
    at io.vertx.core.streams.impl.PipeImpl.close(PipeImpl.java:138)
    at io.vertx.core.http.impl.HttpServerFileUploadImpl.cancelStreamToFileSystem(HttpServerFileUploadImpl.java:223)
    at io.vertx.ext.web.impl.FileUploadImpl.cancel(FileUploadImpl.java:72)
    at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.cancelAndCleanupFileUploads(BodyHandlerImpl.java:323)
    at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.lambda$new$2(BodyHandlerImpl.java:219)
    at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
    at io.vertx.core.http.impl.HttpEventHandler.handleException(HttpEventHandler.java:89)
    at io.vertx.core.http.impl.Http1xServerRequest.handleException(Http1xServerRequest.java:639)
    at io.vertx.core.http.impl.Http1xServerConnection.lambda$handleClosed$5(Http1xServerConnection.java:448)
    at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:71)
    at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:163)
    at io.vertx.core.impl.AbstractContext.execute(AbstractContext.java:58)
    at io.vertx.core.http.impl.Http1xServerConnection.handleClosed(Http1xServerConnection.java:447)
    at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:144)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
    at io.netty.handler.stream.ChunkedWriteHandler.channelInactive(ChunkedWriteHandler.java:137)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
    at io.netty.handler.codec.http.HttpContentEncoder.channelInactive(HttpContentEncoder.java:313)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
    at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
    at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
    at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Unknown Source)
```

### Do you have a reproducer?

I don't have a readily available reproducer.

### Extra

* It happens on both JDK 14 and JDK 17, so it should not be JDK version specific.

**Comment by vietj** [comment]
please provide a reproducer or reopen if that still happens
