### ISSUE TITLE
Eventbus - Contextual data shared between different contexts

### ISSUE THREAD

**Issue by glassfox** [eclipse-vertx/vert.x#4180]
Hi Friends, After investigations of miss behavior of contextual tracing, I think that we found regression.

Following details:
Several eventbus events have a single (shared) context local data.
This happened in worker verticle and in inboundInterceptor of Reply.

Following the reproduce test:

``` java
  @Test
  void testRequestReceive(Vertx vertx, VertxTestContext ctx) {
    logger.trace("testRequestReceive");
    
    vertx.runOnContext(nil -> {
      vertx.eventBus().addOutboundInterceptor(event-> {
        var value = get(CONTEXTUAL_KEY);
        if(null != value) {
          logger.trace("put contextual value: {} to header", value);
          event.message().headers().add(CONTEXTUAL_KEY, value);
        }
        event.next();
      });
      
      vertx.eventBus().addInboundInterceptor(event-> {
        var value = event.message().headers().get(CONTEXTUAL_KEY);
        if(null != value) {
          put(CONTEXTUAL_KEY, value);
        }
        event.next();
      });
      
      vertx.deployVerticle(new AbstractVerticle() {
        public void start(Promise<Void> startPromise) throws Exception {
          vertx.eventBus().consumer(EVENT_ADDRESS, message -> {
            message.reply(message.body());
          });
          
          startPromise.complete();
        }
      }, new DeploymentOptions().setWorker(true))
      .compose(noig -> vertx.deployVerticle(new AbstractVerticle() {
        public void start(Promise<Void> startPromise) throws Exception {
          final int max = 100;
          AtomicInteger cnt = new AtomicInteger();
          AtomicBoolean failed = new AtomicBoolean(); 
          for (int i = 0; i < max; i++) {
            logger.trace("send:{}", i);
            var value = String.valueOf(i);
            put(CONTEXTUAL_KEY, value);
            vertx.eventBus().request(EVENT_ADDRESS, value, res -> {
              try {
                if(! failed.get()) {
                  var expectedValue = (String)res.result().body();
                  var actualValue = get(CONTEXTUAL_KEY);
                  
                  Assertions.assertEquals(expectedValue, actualValue);
                  logger.trace("received: message:{}, context:{}", expectedValue, actualValue);
                  if(cnt.incrementAndGet() >= max) {
                    ctx.completeNow();
                  }
                }
              } catch (Throwable e) {
                if(failed.compareAndSet(false, true)) {
                  ctx.failNow(e);
                }
              }
            });
          };
          
          startPromise.complete();
        }
      }, new DeploymentOptions().setWorker(true)));
    });  
  }
  
  private static String put(String key, String value) {
    Objects.requireNonNull(key);
    Objects.requireNonNull(value);
    ContextInternal ctx = (ContextInternal) Vertx.currentContext();
    if (ctx == null) {
      if (logger.isTraceEnabled()) {
        logger.trace("Attempt to set contextual data from a non Vert.x thread");
      }
      return null;
    } else {
      return contextualDataMap(ctx).put(key, value);
    }
  }

  public static String get(String key) {
    Objects.requireNonNull(key);
    ContextInternal ctx = (ContextInternal) Vertx.currentContext();
    if (ctx != null) {
      return contextualDataMap(ctx).get(key);
    }
    return null;
  }
  
  private static ConcurrentMap<String, String> contextualDataMap(ContextInternal ctx) {
    Objects.requireNonNull(ctx);
    return (ConcurrentMap<String, String>) ctx.localContextData().computeIfAbsent(EventBusTest2.class, k -> new ConcurrentHashMap<String,String>());
  }
```

**Comment by vietj** [comment]
can you provide a full reproducer ?

**Comment by glassfox** [comment]
did you mean packages and class definitions ?

**Comment by vietj** [comment]
yes as a small maven project hosted on github, your reproducer use classes that are not available

**Comment by glassfox** [comment]
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.DeploymentOptions;
import io.vertx.core.Promise;
import io.vertx.core.Vertx;
import io.vertx.core.impl.ContextInternal;
import io.vertx.junit5.VertxTestContext;

class ReplyIssueTest {

	private static final String CONTEXTUAL_KEY = "contextual_key";
	protected static final String EVENT_ADDRESS = "reply-issue.test.event.address";

	@Test
	  void testRequestReceive(Vertx vertx, VertxTestContext ctx) {
	    
	    vertx.runOnContext(nil -> {
	      vertx.eventBus().addOutboundInterceptor(event-> {
	        var value = get(CONTEXTUAL_KEY);
	        if(null != value) {
	          event.message().headers().add(CONTEXTUAL_KEY, value);
	        }
	        event.next();
	      });
	      
	      vertx.eventBus().addInboundInterceptor(event-> {
	        var value = event.message().headers().get(CONTEXTUAL_KEY);
	        if(null != value) {
	          put(CONTEXTUAL_KEY, value);
	        }
	        event.next();
	      });
	      
	      vertx.deployVerticle(new AbstractVerticle() {
	        public void start(Promise<Void> startPromise) throws Exception {
	          vertx.eventBus().consumer(EVENT_ADDRESS, message -> {
	            message.reply(message.body());
	          });
	          
	          startPromise.complete();
	        }
	      }, new DeploymentOptions().setWorker(true))
	      .compose(noig -> vertx.deployVerticle(new AbstractVerticle() {
	        public void start(Promise<Void> startPromise) throws Exception {
	          final int max = 100;
	          AtomicInteger cnt = new AtomicInteger();
	          AtomicBoolean failed = new AtomicBoolean(); 
	          for (int i = 0; i < max; i++) {
	            var value = String.valueOf(i);
	            put(CONTEXTUAL_KEY, value);
	            vertx.eventBus().request(EVENT_ADDRESS, value, res -> {
	              try {
	                if(! failed.get()) {
	                  var expectedValue = (String)res.result().body();
	                  var actualValue = get(CONTEXTUAL_KEY);
	                  
	                  Assertions.assertEquals(expectedValue, actualValue);
	                  if(cnt.incrementAndGet() >= max) {
	                    ctx.completeNow();
	                  }
	                }
	              } catch (Throwable e) {
	                if(failed.compareAndSet(false, true)) {
	                  ctx.failNow(e);
	                }
	              }
	            });
	          };
	          
	          startPromise.complete();
	        }
	      }, new DeploymentOptions().setWorker(true)));
	    });  
	  }
	  
	  private static String put(String key, String value) {
	    Objects.requireNonNull(key);
	    Objects.requireNonNull(value);
	    ContextInternal ctx = (ContextInternal) Vertx.currentContext();
	    if (ctx == null) {
	      return null;
	    } else {
	      return contextualDataMap(ctx).put(key, value);
	    }
	  }

	  public static String get(String key) {
	    Objects.requireNonNull(key);
	    ContextInternal ctx = (ContextInternal) Vertx.currentContext();
	    if (ctx != null) {
	      return contextualDataMap(ctx).get(key);
	    }
	    return null;
	  }
	  
	  private static ConcurrentMap<String, String> contextualDataMap(ContextInternal ctx) {
	    Objects.requireNonNull(ctx);
	    return (ConcurrentMap<String, String>) ctx.localContextData().computeIfAbsent(EventBusTest2.class, k -> new ConcurrentHashMap<String,String>());
	  }
}

**Comment by glassfox** [comment]
I have  checked the test in vertx-core-4.2.4-SNAPSHOT on macos and test has been failed:
```
java.lang.AssertionError: io.vertx.core.impl.NoStackTraceThrowable: context not empty. value:f95f47fd-0ec7-4407-b616-04e2c103961d
	at io.vertx.junit5.VertxExtension.joinActiveTestContexts(VertxExtension.java:193)
	at io.vertx.junit5.VertxExtension.afterTestExecution(VertxExtension.java:164)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterTestExecutionCallbacks$9(TestMethodTestDescriptor.java:233)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:273)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$14(TestMethodTestDescriptor.java:273)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:272)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterTestExecutionCallbacks(TestMethodTestDescriptor.java:232)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: io.vertx.core.impl.NoStackTraceThrowable: context not empty. value:f95f47fd-0ec7-4407-b616-04e2c103961d
```
