### ISSUE TITLE
Issue with webclient in 4.1.0

### ISSUE THREAD

**Issue by subhashkadam** [eclipse-vertx/vert.x#4181]
Facing issue with webclient 
Having following stackstrace 
1.  SEVERE io.vertx.core.net.impl.ConnectionBase Connection reset
2. java.net.SocketException: Connection reset 
  	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:345) 
  	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:376) 
  	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) 
  	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) 
  	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) 
  	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) 
  	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) 
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) 
  	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) 
  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) 
  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) 
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
  	at java.base/java.lang.Thread.run(Thread.java:832)

3. SEVERE io.vertx.core.http.impl.HttpClientRequestImpl io.vertx.core.VertxException: Connection was closed

above error logs are printed in production logs 
it was clearly working with 3.9.1.
When same api tried from local env it works. no errors are returned.

**Comment by vietj** [comment]
do you have a reproducer ? it does not seem vertx related

**Comment by vietj** [comment]
please reopen an issue when you have more details

**Comment by subhashkadam** [comment]
i don't have reproducer as this is happening randomly in production .. this was working well with 3.9.1

**Comment by vietj** [comment]
we can't see what could be different without a reproducer, the symptoms
looks like a connection reset
