### ISSUE TITLE
`executeBlocking` throw exception instead of return a failed future after the `workerPool` closed, thus caused `RejectedExecutionException` 

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [eclipse-vertx/vert.x#4209]
### Questions
When using `HazelcastClusterManager`, it would thrown `RejectedExecutionException` sometimes after closed the `vertx` instance:

``` log
2021-12-21 11:05:30,529 (:) [ERROR][io.vertx.core.impl.ContextImpl] Unhandled exception
java.util.concurrent.RejectedExecutionException: Task io.vertx.core.impl.ContextImpl$$Lambda$210/0x0000000800ece910@554cbcc6 rejected from java.util.concurrent.ThreadPoolExecutor@5b8b481f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 8]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365) ~[?:?]
	at io.vertx.core.impl.ContextImpl.executeBlocking(ContextImpl.java:172) ~[vertx-core-4.2.2.jar:4.2.2]
	at io.vertx.core.impl.ContextImpl.executeBlocking(ContextImpl.java:137) [vertx-core-4.2.2.jar:4.2.2]
	at io.vertx.core.impl.EventLoopContext.executeBlocking(EventLoopContext.java:22) [vertx-core-4.2.2.jar:4.2.2]
	at io.vertx.core.Vertx.executeBlocking(Vertx.java:581) ~[vertx-core-4.2.2.jar:4.2.2]
	at io.vertx.spi.cluster.hazelcast.impl.Throttling.lambda$run$5(Throttling.java:100) ~[vertx-hazelcast-4.2.2.jar:4.2.2]
```

The `executeBlocking` method throw the exception at [Line#179](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/impl/ContextImpl.java#L179) when failed to execute the command ([because the `workerPool` closed earlier then the netty event loop](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/impl/VertxImpl.java#L809-L813)), is it works as intended? Maybe we should wrapped the exception with a failed future instead, thus the caller could handle the exception or just ignore it.

### Version
4.2.2

**Comment by tsegismont** [comment]
@zhengxiaoyao0716 would it be possible for you to test the changes from vert-x3/vertx-hazelcast#149 in a staging environment?

**Comment by zhengxiaoyao0716** [comment]
@tsegismont I tried the changes and the problem seems resolved, thanks for your work. However, as I don't have a staging environment and the problem is not appeared each time, so I couldn't sure it's solved completely.
