### ISSUE TITLE
Uncaught exception with HTTP Client on HTTP/2.0 connection failure 

### ISSUE THREAD

**Issue by NilsRenaud** [eclipse-vertx/vert.x#4254]
### Version

I use vert.x 4.2.4

### Context

I was playing with the vert.x HTTP client, trying to use it to send an unencrypted HTTP/2.0 request with prior knowledge, but the HTTP server I reached out was only serving HTTP/1.1 requests.
Then, the HTTP/2.0 connection failed but none of my exception handlers have been notified of this failure. I only have these log lines :
```
10:28:11.317 [vert.x-eventloop-thread-1] ERROR io.vertx.core.net.impl.ConnectionBase - First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:108)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:338)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.channelRead(VertxHttp2ConnectionHandler.java:378)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        [...]
10:28:11.317 [vert.x-eventloop-thread-1] WARN io.vertx.core.http.impl.HttpClientConnection - Connection evicted
10:28:11.321 [vert.x-eventloop-thread-1] DEBUG io.netty.handler.codec.http2.Http2ConnectionHandler - [id: 0xb698ce07, L:0.0.0.0/0.0.0.0:63856] Sending GOAWAY failed: lastStreamId '2147483647', errorCode '1', debugData 'First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f'. Forcing shutdown of the connection.
java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:182)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:130)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:493)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:423)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.onError(Http2ConnectionHandler.java:643)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:245)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.channelRead(VertxHttp2ConnectionHandler.java:378)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        [...]
```
### Reproducer

Here is the server set up I used : 
```java
ServerSocket server = new ServerSocket(8282, 1, InetAddress.getLocalHost());
while (true) {
    System.out.println("WAITING");
    Socket client = server.accept();
    System.out.println("RECEIVED");
    String content = "HTTP/1.1 200 OK\r\n"
            + "Content-Length: 2\r\n"
            + "\r\n"
            + "OK";
    client.getOutputStream().write(content.getBytes(StandardCharsets.UTF_8));
    client.getOutputStream().flush();
    client.close();
}
```

And here is my HTTP Client settings : 
```java
Vertx vx = Vertx.vertx();
vx.exceptionHandler(t -> System.out.println("VERTX EXCEPTION HANDLER"));
HttpClientOptions options = new HttpClientOptions()
        .setProtocolVersion(HttpVersion.HTTP_2)
        .setHttp2ClearTextUpgrade(false)
        .setSsl(false);
vx.createHttpClient(options)
    .request(HttpMethod.GET, 8282, "127.0.0.1", "/")
    .onSuccess(req -> req.send().onSuccess(resp -> System.out.println("OK"))
                       .onFailure(t -> System.out.println("RESPONSE EXCEPTION HANDLER"))) 
    .onFailure(t -> System.out.println("REQUEST EXCEPTION HANDLER")); // I'm expecting to get the exception here
    // but non of them has been triggered !
```

**Comment by coding4m** [comment]
`VertxHttp2ConnectionHandler` currently return `Http2ClientConnection` onSettingsRead: 
```
  @Override
  public void onSettingsRead(ChannelHandlerContext ctx, Http2Settings settings) throws Http2Exception {
    if (useDecompressor) {
      decoder().frameListener(new DelegatingDecompressorFrameListener(decoder().connection(), connection));
    } else {
      decoder().frameListener(connection);
    }
    connection.onSettingsRead(ctx, settings);
    if (addHandler != null) {
      addHandler.handle(connection);
    }
  }
```

return `Http2ClientConnection` on handlerAdded ???
```
  @Override
  public void handlerAdded(ChannelHandlerContext ctx) throws Exception {
    super.handlerAdded(ctx);
    chctx = ctx;
    connection = connectionFactory.apply(this);
    if (addHandler != null) {
      addHandler.handle(connection);
    }
  }
```

**Comment by vietj** [comment]
thanks for the reproducer @NilsRenaud
