### ISSUE TITLE
why vertx not support unix domain socket?

### ISSUE THREAD

**Issue by clebeg** [eclipse-vertx/vert.x#4258]
### Questions

```
2022-01-27 15:25:14.549 [vert.x-eventloop-thread-0] INFO  c.q.w.svrkit.server.MeshUDSServer -MeshUDSServer Start Fail: java.lang.IllegalArgumentException
        at io.vertx.core.net.impl.transport.Transport.serverChannelFactory(Transport.java:194)
        at io.vertx.core.net.impl.AsyncResolveConnectHelper.doBind(AsyncResolveConnectHelper.java:37)
        at io.vertx.core.net.impl.TCPServerBase.listen(TCPServerBase.java:143)
        at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:169)
        at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:193)
        at com.qq.weixin.svrkit.server.MeshUDSServer.run(MeshUDSServer.java:65)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:748)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:309)
        at com.qq.weixin.mmbizjmeshdockerdemo.MMBizJMeshDockerDemoServer.main(MMBizJMeshDockerDemoServer.java:27)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:67)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

### Version

4.2.4

### Context

```
    public ChannelFactory<? extends ServerChannel> serverChannelFactory(boolean domainSocket) {
        if (domainSocket) {
            throw new IllegalArgumentException();
        } else {
            return NioServerSocketChannel::new;
        }
    }
```

### Do you have a reproducer?

if i provide 
```
netServer.listen(SocketAddress.domainSocketAddress(meshBizListenPath), res -> {
            if (res.succeeded()) {
                log.info("MeshUDSServer Start Success, listen_path={}, work_cnt={}", meshBizListenPath, meshBizWorkCnt);
            } else {
                log.info("MeshUDSServer Start Fail: {}", ExceptionUtils.getStackTrace(res.cause()));
            }
        });
```
will throw
### Extra

there should return EpollServerSocketChannel ?

**Comment by vietj** [comment]
it is supported you should read the documentation https://vertx.io/docs/vertx-core/java/#_native_transports
