### ISSUE TITLE
StaticHandler with BodyHandler returns 500 status code first time for non-existent static resource

### ISSUE THREAD

**Issue by narras-oss** [eclipse-vertx/vert.x#4357]
### Version

4.2.7

### Context

We started noticing stack traces for requests failing (with 500 status code) when static resources are not found for the first time (subsequent calls return 404 since the path is cached)

```
io.vertx.ext.web.RoutingContext (vert.x-eventloop-thread-1) - Unhandled exception in router
java.lang.IllegalStateException: Request has already been read
	at io.vertx.core.http.impl.Http1xServerRequest.checkEnded(Http1xServerRequest.java:655) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.http.impl.Http1xServerRequest.handler(Http1xServerRequest.java:293) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.handler(HttpServerRequestWrapper.java:103) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:85) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:44) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1127) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:151) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:203) ~[vertx-web-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[vertx-core-4.1.5.jar:4.1.5]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_211]
```

### Do you have a reproducer?
This occurs when BodyHandler is added after Static handler (we have other paths besides "static" which require BodyHandler).

```
 StaticHandler staticHandler = StaticHandler.create("static");
router.get("static/*").handler(staticHandler);

 router.route().handler(BodyHandler.create());
```

Invoking any request for the first time with "/static/<some random string>" would fail with status code 500 in routing context and the stack trace above

Switching the handler order (i.e. BodyHandler first and then StaticHandler works around this issue)

**Comment by narras-oss** [comment]
Moved issue to vertx-web project

**Comment by AhmedX6** [comment]
Hello, same issue here , is it fixed??

**Comment by tsegismont** [comment]
The `BodyHandler` must be declared before the `StaticHandler` because:

- when the requested file does not exist, the `StaticHandler` hands over to the next handler
- the request is already ended when it reaches the `BodyHandler`
