### ISSUE TITLE
http2client stream timeout , opentracing NullPointerException

### ISSUE THREAD

**Issue by xiongrl** [eclipse-vertx/vert.x#4472]
### Questions

[12:01:14:024] vert.x-eventloop-thread-11 [ERROR] - i.n.h.c.h.DefaultHttp2Connection: - Caught Throwable from listener onStreamClosed.
java.lang.NullPointerException: Cannot read field "statusCode" because "resp" is null
	at io.vertx.core.http.impl.HttpUtils$4.value(HttpUtils.java:159) ~[vertx-core-4.3.3.jar:4.3.3]
	at io.vertx.core.http.impl.HttpUtils$4.value(HttpUtils.java:144) ~[vertx-core-4.3.3.jar:4.3.3]
	at io.vertx.tracing.opentracing.OpenTracingTracer.reportTags(OpenTracingTracer.java:162) ~[vertx-opentracing-4.3.3.jar:4.3.3]
	at io.vertx.tracing.opentracing.OpenTracingTracer.receiveResponse(OpenTracingTracer.java:154) ~[vertx-opentracing-4.3.3.jar:4.3.3]
	at io.vertx.tracing.opentracing.OpenTracingTracer.receiveResponse(OpenTracingTracer.java:37) ~[vertx-opentracing-4.3.3.jar:4.3.3]
	at io.vertx.core.http.impl.Http2ClientConnection$Stream.onClose(Http2ClientConnection.java:343) ~[vertx-core-4.3.3.jar:4.3.3]
	at io.vertx.core.http.impl.Http2ConnectionBase.onStreamClosed(Http2ConnectionBase.java:150) ~[vertx-core-4.3.3.jar:4.3.3]
	at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.onStreamClosed(VertxHttp2ConnectionHandler.java:189) ~[vertx-core-4.3.3.jar:4.3.3]
	at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:357) ~[netty-codec-http2-4.1.78.Final.jar:4.1.78.Final]

### Version

4.3.3

### Context
http2 client request timeout,opentracing NullPointerException , httpclient exceptionHandler not work.

**Comment by vietj** [comment]
can you provide a reproducer ?

**Comment by xiongrl** [comment]
![image](https://user-images.githubusercontent.com/4568603/189312789-b367024a-26e2-4d82-83bd-b9d5b749f7ea.png)

**Comment by xiongrl** [comment]
![image](https://user-images.githubusercontent.com/4568603/189313781-10b650f3-98cd-4e13-b64f-8c715983aabe.png)

**Comment by vietj** [comment]
can you provide a small project that reproduces the issue ?

**Comment by xiongrl** [comment]
https://github.com/xiongrl/vertx-opentrace-example

**Comment by vietj** [comment]
can you provide also the CLI to run the agent in a docker container as instruction ? thanks
