### ISSUE TITLE
Vert.x 4.3.3 fails if assertions are enabled with Netty 4.1.80.Final

### ISSUE THREAD

**Issue by jamezp** [eclipse-vertx/vert.x#4477]
### Version

Which version(s) did you encounter this bug ?

4.3.3, but likely any main too.

### Context

[Upgrading RESTEasy](https://github.com/resteasy/resteasy/pull/3231) to Netty 4.1.80 causes assertion errors due to https://github.com/netty/netty/pull/12709.

The [`io.vertx.core.http.impl.AssembledHttpResponse`](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/AssembledHttpResponse.java) implements the `io.netty.handler.codec.http.HttpContent` which triggers the assertion error.

I do not know if this should be considered a Vert.x error or a Netty issue.

### Do you have a reproducer?

It's a larger reproduce, but if you clone https://github.com/resteasy/resteasy and run with:
```
mvn clean verify -am -Dsurefire.failIfNoSpecifiedTests=false -pl server-adapters/resteasy-vertx/ -Dversion.io.netty.netty4=4.1.80.Final -Dtest=SSETest#testSSE
```

### Extra

The stack trace when I enabled some better logging was:
```
13:31:16,879 DEBUG [org.jboss.resteasy.resteasy_jaxrs.i18n] (vert.x-eventloop-thread-19) RESTEASY002030: Failed to write event org.jboss.resteasy.plugins.providers.sse.OutboundSseEventImpl@390f4438: io.netty.handler.codec.EncoderException: java.lang.AssertionError
    at io.netty.handler.codec.http.HttpObjectEncoder.write(HttpObjectEncoder.java:108)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
    at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
    at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.write(WebSocketServerExtensionHandler.java:113)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
    at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:181)
    at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:231)
    at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:216)
    at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:212)
    at io.vertx.core.http.impl.Http1xServerResponse.write(Http1xServerResponse.java:755)
    at io.vertx.core.http.impl.Http1xServerResponse.write(Http1xServerResponse.java:332)
    at io.vertx.core.http.impl.Http1xServerResponse.write(Http1xServerResponse.java:68)
    at org.jboss.resteasy.plugins.server.vertx.ChunkOutputStream.flush(ChunkOutputStream.java:134)
    at org.jboss.resteasy.plugins.server.vertx.ChunkOutputStream.asyncFlush(ChunkOutputStream.java:145)
    at org.jboss.resteasy.plugins.providers.sse.SseEventOutputImpl.lambda$internalFlushResponseToClient$0(SseEventOutputImpl.java:175)
    at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
    at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
    at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
    at org.jboss.resteasy.plugins.providers.sse.SseEventOutputImpl.lambda$internalFlushResponseToClient$3(SseEventOutputImpl.java:175)
    at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$3(ServerResponseWriter.java:109)
    at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:410)
    at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:261)
    at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
    at org.jboss.resteasy.plugins.providers.sse.SseEventOutputImpl.internalFlushResponseToClient(SseEventOutputImpl.java:161)
    at org.jboss.resteasy.plugins.providers.sse.SseEventOutputImpl.send(SseEventOutputImpl.java:242)
    at org.jboss.resteasy.test.asyncio.SSEResource.reset(SSEResource.java:24)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
    at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
    at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
    at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
    at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
    at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
    at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
    at org.jboss.resteasy.plugins.server.vertx.RequestDispatcher.service(RequestDispatcher.java:96)
    at org.jboss.resteasy.plugins.server.vertx.VertxRequestHandler.lambda$handle$0(VertxRequestHandler.java:68)
    at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91)
    at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
    at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:86)
    at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:163)
    at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:51)
    at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
    at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
    at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:79)
    at io.vertx.core.http.impl.Http1xServerRequest.onEnd(Http1xServerRequest.java:581)
    at io.vertx.core.http.impl.Http1xServerRequest.handleEnd(Http1xServerRequest.java:564)
    at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:76)
    at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:153)
    at io.vertx.core.http.impl.Http1xServerConnection.onEnd(Http1xServerConnection.java:191)
    at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:147)
    at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:157)
    at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
    at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
    at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.AssertionError
    at io.netty.handler.codec.http.HttpObjectEncoder.encodeJustHttpMessage(HttpObjectEncoder.java:185)
    at io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:178)
    at io.netty.handler.codec.http.HttpObjectEncoder.write(HttpObjectEncoder.java:97)
    ... 100 more
```

**Comment by vietj** [comment]
can you test the latest 4.1.81.Final ?

**Comment by vietj** [comment]
I think we need to override a specific subclass of the vertx response encoder to tell the interface is legit

**Comment by franz1981** [comment]
https://github.com/netty/netty/issues/12750 and fix are on the just released 81 (80 was breaking other stuff eg certificates IIRC), hence is suggested twice to move to that one instead.

**Comment by franz1981** [comment]
Regarding the scalability issue; it still exists in some form on vertx, although is severely reduced and unlikely if the class hierarchy won't change.

The issue is exactly on https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/AssembledHttpResponse.java that's implementing 2 interfaces (but it's not a full http msg type(!)); if other concrete types fall into the Netty branch here:
```java        
        if (msg instanceof HttpMessage) {
            // HERE!!!
            final H m;
            try {
                m = (H) msg;
            } catch (Exception rethrow) {
                ReferenceCountUtil.release(msg);
                throw rethrow;
            }
            if (m instanceof LastHttpContent) {
                encodeHttpMessageLastContent(ctx, m, out);
            } else if (m instanceof HttpContent) {
                encodeHttpMessageNotLastContent(ctx, m, out);
            } else {
                encodeJustHttpMessage(ctx, m, out);
            }
        } else {
        // ...
```
then the JIT will really perform the instanceof sequence, causing the scalability issue mentioned earlier to happen.
Sadly, Netty doesn't have any mixin interface `HttpMessageContent` we can test against (on Netty) to grant a (successfull) single instanceof branch/check to happen without any scalability hit.

Luckly there are no other concrete types able to successful enter in that code path (`instanceof HttpMessage == true`) used on vertx, but it's still fragile.

A possible solution to make it more robust could be: https://github.com/franz1981/vert.x/tree/netty_idiomatic
This split the assembled type to be a common idiomatic netty type (same with the full version too); making the issue to never happen  (assuming netty code won't change).

**Comment by vietj** [comment]
I did a test too and it seems fine, we will upgrade to 4.1.81.Final this week.

**Comment by vietj** [comment]
Netty was bumped to 4.1.82.Final
