### ISSUE TITLE
import io.netty.handler.logging.ByteBufFormat not found

### ISSUE THREAD

**Issue by leolux** [eclipse-vertx/vert.x#4523]
The class io.vertx.core.net.NetworkOptions imports the following class`import io.netty.handler.logging.ByteBufFormat`.
But ByteBufFormat is not within the dependency of netty-handler 4.1.34. I get the following runtime error because of this import:

Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/handler/logging/ByteBufFormat
	at io.vertx.core.net.NetworkOptions.<clinit>(NetworkOptions.java:60)
	at io.vertx.core.VertxOptions.<init>(VertxOptions.java:130)
	at io.vertx.core.Vertx.vertx(Vertx.java:77)

**Comment by leolux** [comment]
Issue is solved: It was a conflicting maven dependency of a third party library.
