### ISSUE TITLE
Metric - Http1xServerConnection request is null

### ISSUE THREAD

**Issue by glassfox** [eclipse-vertx/vert.x#4546]
Below exception occurred for enabled metric:
```
java.lang.NullPointerException: Cannot invoke "io.vertx.core.http.impl.Http1xServerRequest.metric()" because "request" is null
    at io.vertx.core.http.impl.Http1xServerConnection.reportResponseComplete(Http1xServerConnection.java:253) 
    at io.vertx.core.http.impl.Http1xServerConnection.responseComplete(Http1xServerConnection.java:198) 
    at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:415) 
    at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:388) 
    at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:367) 
    at io.vertx.ext.web.handler.impl.ErrorHandlerImpl.sendError(ErrorHandlerImpl.java:180) 
```
Occurred on vertx version: 4.3.4 and 4.3.5

**Comment by glassfox** [comment]
hi @tsegismont 
After short investigation, has been found incorrect using of context.fail. 
I not sure if this is a bug. Anyway this kind of implementation create recursion and fail in the end with NullPointer exception.

Following example of route:

``` java
router.route().handler(ctx -> {
	ctx.addHeadersEndHandler(c -> {
		...
		ctx.fail(555);
		...
	});
			
	ctx.next();
});
```

Let me know if you agree to close this bug.

**Comment by tsegismont** [comment]
Please do not close yet. If you can add a little more details to the snippet, perhaps we can create a test and change our code to fail nicely instead of failing with a NPE.

**Comment by glassfox** [comment]
Sure. I will create Unitest.

**Comment by tsegismont** [comment]
Thank you

**Comment by glassfox** [comment]
``` java

import java.util.concurrent.atomic.AtomicBoolean;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.Promise;
import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;
import io.vertx.core.http.RequestOptions;
import io.vertx.core.metrics.MetricsOptions;
import io.vertx.ext.web.Router;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;

@ExtendWith(VertxExtension.class)
public class AppImplTest {

	@BeforeEach
	protected void setUp(Vertx vertx) throws Exception {
	}
	
	@Test
	void test(Vertx vertx, VertxTestContext testCtx) {
		AtomicBoolean flag = new AtomicBoolean();
		VertxOptions vertxOptions = new VertxOptions().setMetricsOptions(new MetricsOptions().setEnabled(true));
		Future.succeededFuture().map(Vertx.vertx(vertxOptions))
		.compose(myVertx -> 
			myVertx.deployVerticle(new AbstractVerticle() {
				@Override
				public void start(Promise<Void> startPromise) throws Exception {
					var router = Router.router(this.vertx);
					router.route().handler(ctx -> {
						ctx.addHeadersEndHandler(c-> {
							if(!flag.compareAndExchange(false, true)) {
								ctx.fail(555);
							}
						});
						ctx.end();
					});
					
					router.route().failureHandler(ctx -> {
						if(null != ctx.failure()) {
							testCtx.failNow(ctx.failure());
						}
						
						ctx.next();
						
					});
					
					this.vertx.createHttpServer()
					.requestHandler(router)
					.listen()
					.<Void>mapEmpty()
					.onComplete(startPromise);
				}
			}))
			.compose(nil -> 
				vertx.createHttpClient()
				.request(new RequestOptions())
				.compose(req -> req.send())
			)
			.onComplete(testCtx.succeedingThenComplete());
	}

}

```
