### ISSUE TITLE
io.vertx.core.json.EncodeException: Failed to encode as JSON

### ISSUE THREAD

**Issue by glassfox** [eclipse-vertx/vert.x#4608]
vertx: 4.3.8

JSON: (was java.util.ConcurrentModificationException) (through reference chain: java.util.LinkedHashMap["value"]->java.util.LinkedHashMap["social_security"]->java.util.LinkedHashMap["ongoing"])
    at io.vertx.core.json.jackson.DatabindCodec.toBuffer(DatabindCodec.java:173)
    at io.vertx.core.json.JsonObject.toBuffer(JsonObject.java:1053)
    at io.vertx.ext.common.event.CacheItemCodec.encodeToWire(CacheItemCodec.java:32)
    at io.vertx.ext.common.event.CacheItemCodec.encodeToWire(CacheItemCodec.java:19)
    at io.vertx.core.eventbus.impl.clustered.ClusteredMessage.writeBody(ClusteredMessage.java:241)

**Comment by glassfox** [comment]
Hi,
1. Please bind attached below CacheItemCodec source
2. Unable to reproduce the behavior. Log from Production env.

```Java
public class CacheItemCodec implements MessageCodec<CacheItem, CacheItem> {
	private static final Logger logger = LogManager.getLogger();
	
	@Override
	public void encodeToWire(Buffer buffer, CacheItem model) {
		logger.debug("encodeToWire");
		// Easiest ways is using JSON object
		JsonObject jsonToEncode = new JsonObject();
		jsonToEncode.put("key", model.getKey());
		jsonToEncode.put("value", serializeDataObject(model.getValue()));
		jsonToEncode.put("meta", new JsonObject(model.getMeta()));

		// Encode object to buffer
		var encoded = jsonToEncode.toBuffer();

		// Write data into given buffer
		buffer.appendInt(encoded.length());
		buffer.appendBuffer(encoded);
	}

	private static <T, S> Function<String, T> deserialize(TypeToken<S> typeToken){
		var c = (Class<T>)typeToken.getRawType();
		if(c.equals(JsonObject.class)) {
			return s -> (T)new JsonObject(s);
		}else {
			return Functions.combine(c, Jsons::decodeValue);	
		}
	}
	
	private JsonObject serializeDataObject(Object obj) {
		
		if(null == obj) {
			return null;
		}else if (obj instanceof JsonObject){
			return (JsonObject)obj;
		}else {
			try {
				Method m = obj.getClass().getMethod("toJson", new Class[] {});
				JsonObject resJson = (JsonObject)m.invoke(obj);
				return resJson;	
			} catch (NoSuchMethodException nsmE) {  
				Throws.propagate(new Bug("missing 'toJson()' method in serialized value object within CacheItem"));
			} catch (Throwable t) {  
				logger.error("UnExpected error", t);
				Throws.propagate(t);
			}	
		}
		
		return null;
	}
	
	@Override
	public CacheItem decodeFromWire(int pos, Buffer buffer) {
		logger.debug("decodeFromWire()");
		int length = buffer.getInt(pos);
		pos += 4;
		JsonObject contentJson = new JsonObject(buffer.slice(pos, pos + length));
		
		JsonObject meta = contentJson.getJsonObject("meta", new JsonObject());
		Optional<String> optClassName = Optional.ofNullable(meta.getString("class"));
		
		Function<String, Object> deserializeFunc = 
		optClassName.flatMap(t -> {
			try {
				return Optional.of(ClassLoader.getSystemClassLoader().loadClass(t));
			} catch (ClassNotFoundException e) {
				logger.warn("class with name '{}' not found.", t);
				return Optional.empty();
			}
		})
		.map(TypeToken::of)
		.map(CacheItemCodec::deserialize)
		.orElse(JsonObject::new);
		
		return new CacheItemBuilder()
				.key(contentJson.getString("key"))
				.value(Optional.ofNullable(contentJson.getValue("value"))
						.map(Object::toString)
						.map(deserializeFunc)
						.orElse(null))
				.meta(meta.getMap()).build();
	}

	@Override
	public CacheItem transform(CacheItem model) {
		return CacheItemBuilder.buildUpon(model).build();
	}

	@Override
	public String name() {
		return this.getClass().getSimpleName().toLowerCase();
	}

	@Override
	public byte systemCodecID() {
		return -1;
	}
}
```

**Comment by vietj** [comment]
it seems that the cached item has been modified concurrently when being sent over the wire, your cached item should not be mutated.
