### ISSUE TITLE
Client: When using HTTP/2 and we exceed the timeout to read, it throws `HttpClosedException` instead of `TimeoutException`

### ISSUE THREAD

**Issue by Sgitario** [eclipse-vertx/vert.x#4620]
### Version

4.3.8

### Steps to reproduce

Using a client like:
```java
HttpClient client = ...;
RequestOptions requestOptions = ...;
// use a very short timeout to reproduce
requestOptions.setTimeout(100);
httpClient.request(requestOptions, handler)
```

When performing the request, it will return a `HttpClosedException` exception instead of a `TimeoutException`. When using the protocol version HTTP 1.1, the same was returning a `TimeoutException` exception as expected.

**Comment by vietj** [comment]
this is expected for HTTP/2, the pool gets timeout which does reset the stream which is then reported as an `HttpClosedException` for the code that acquires the connection.

**Comment by Sgitario** [comment]
> this is expected for HTTP/2, the pool gets timeout which does reset the stream which is then reported as an `HttpClosedException` for the code that acquires the connection.

Can we know if the HttpClosedException was thrown because of a timeout or because the HTTP connection was closed?

**Comment by vietj** [comment]
not really, here is an example of stack trace with HTTP/2 when it is reported:

```
/Users/julien/.sdkman/candidates/java/8.0.352-amzn/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:58311,suspend=y,server=n -ea -DbuildDirectory=/Users/julien/java/vert.x/target -Dvertx.version=4.4.0-SNAPSHOT -Dvertx.handle100Continue=true -Dvertx.useNativeTransport=false -Dvertx.useDomainSockets=false -Dvertx.threadChecks=true -Dio.netty.leakDetection.targetRecords=4 -Dio.netty.leakDetection.samplingInterval=128 -Xmx1200M -Didea.test.cyclic.buffer.size=1048576 -javaagent:/Users/julien/Library/Caches/JetBrains/IdeaIC2022.3/captureAgent/debugger-agent.jar=file:/private/var/folders/s2/6f62zqps1qndrwv1y9l57lvh0000gn/T/capture.props -Dfile.encoding=UTF-8 -classpath /Applications/More/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar:/Applications/More/IntelliJ IDEA CE.app/Contents/plugins/junit/lib/junit5-rt.jar:/Applications/More/IntelliJ IDEA CE.app/Contents/plugins/junit/lib/junit-rt.jar:/Users/julien/.sdkman/candidates/java/8.0.352-amzn/jre/lib/charsets.jar:/Users/julien/.sdkman/candidates/java/8.0.352-amzn/jre/lib/ext/cldrdata.jar:/Users/julien/.sdkman/candidates/java/8.0.352-amzn/jre/lib/ext/dnsns.jar:/Users/julien/.sdkman/candidates/java/8.0.352-amzn/jre/lib/ext/jaccess.jar:/Users/julien/.sdkman/candidates/java/8.0.352-amzn/jre/lib/ext/localedata.jar:/Users/julien/.sdkman/candidates/java/8.0.352-amzn/jre/lib/ext/nashorn.jar:/Users/julien/.sdkman/candidates/java/8.0.352-amzn/jre/lib/ext/sunec.jar:/Users/julien/.sdkman/candidates/java/8.0.352-amzn/jre/lib/ext/sunjce_provider.jar:/Users/julien/.sdkman/candidates/java/8.0.352-amzn/jre/lib/ext/sunpkcs11.jar:/Users/julien/.sdkman/candidates/java/8.0.352-amzn/jre/lib/ext/zipfs.jar:/Users/julien/.sdkman/candidates/java/8.0.352-amzn/jre/lib/jce.jar:/Users/julien/.sdkman/candidates/java/8.0.352-amzn/jre/lib/jfr.jar:/Users/julien/.sdkman/candidates/java/8.0.352-amzn/jre/lib/jsse.jar:/Users/julien/.sdkman/candidates/java/8.0.352-amzn/jre/lib/management-agent.jar:/Users/julien/.sdkman/candidates/java/8.0.352-amzn/jre/lib/resources.jar:/Users/julien/.sdkman/candidates/java/8.0.352-amzn/jre/lib/rt.jar:/Users/julien/java/vert.x/target/test-classes:/Users/julien/java/vert.x/target/classes:/Users/julien/.m2/repository/io/netty/netty-common/4.1.89.Final/netty-common-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-buffer/4.1.89.Final/netty-buffer-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-transport/4.1.89.Final/netty-transport-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-handler/4.1.89.Final/netty-handler-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.89.Final/netty-transport-native-unix-common-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-codec/4.1.89.Final/netty-codec-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-handler-proxy/4.1.89.Final/netty-handler-proxy-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-codec-socks/4.1.89.Final/netty-codec-socks-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-codec-http/4.1.89.Final/netty-codec-http-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-codec-http2/4.1.89.Final/netty-codec-http2-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-resolver/4.1.89.Final/netty-resolver-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-resolver-dns/4.1.89.Final/netty-resolver-dns-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-codec-dns/4.1.89.Final/netty-codec-dns-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-codec-haproxy/4.1.89.Final/netty-codec-haproxy-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-transport-native-epoll/4.1.89.Final/netty-transport-native-epoll-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-transport-classes-epoll/4.1.89.Final/netty-transport-classes-epoll-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-transport-native-kqueue/4.1.89.Final/netty-transport-native-kqueue-4.1.89.Final.jar:/Users/julien/.m2/repository/io/netty/netty-transport-classes-kqueue/4.1.89.Final/netty-transport-classes-kqueue-4.1.89.Final.jar:/Users/julien/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.14.0/jackson-core-2.14.0.jar:/Users/julien/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.14.0/jackson-databind-2.14.0.jar:/Users/julien/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.14.0/jackson-annotations-2.14.0.jar:/Users/julien/.m2/repository/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar:/Users/julien/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar:/Users/julien/.m2/repository/io/vertx/vertx-codegen/4.4.0-SNAPSHOT/vertx-codegen-4.4.0-SNAPSHOT.jar:/Users/julien/.m2/repository/io/vertx/vertx-docgen/0.9.4/vertx-docgen-0.9.4.jar:/Users/julien/.m2/repository/junit/junit/4.13.1/junit-4.13.1.jar:/Users/julien/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/julien/.m2/repository/org/apache/directory/server/apacheds-protocol-dns/1.5.7/apacheds-protocol-dns-1.5.7.jar:/Users/julien/.m2/repository/org/apache/directory/server/apacheds-i18n/1.5.7/apacheds-i18n-1.5.7.jar:/Users/julien/.m2/repository/org/apache/directory/server/apacheds-core-jndi/1.5.7/apacheds-core-jndi-1.5.7.jar:/Users/julien/.m2/repository/org/apache/directory/server/apacheds-core/1.5.7/apacheds-core-1.5.7.jar:/Users/julien/.m2/repository/org/apache/directory/server/apacheds-core-api/1.5.7/apacheds-core-api-1.5.7.jar:/Users/julien/.m2/repository/org/apache/directory/server/apacheds-core-entry/1.5.7/apacheds-core-entry-1.5.7.jar:/Users/julien/.m2/repository/org/apache/directory/server/apacheds-core-constants/1.5.7/apacheds-core-constants-1.5.7.jar:/Users/julien/.m2/repository/org/apache/directory/server/apacheds-utils/1.5.7/apacheds-utils-1.5.7.jar:/Users/julien/.m2/repository/bouncycastle/bcprov-jdk15/140/bcprov-jdk15-140.jar:/Users/julien/.m2/repository/org/apache/directory/server/apacheds-protocol-shared/1.5.7/apacheds-protocol-shared-1.5.7.jar:/Users/julien/.m2/repository/org/apache/mina/mina-core/2.0.0-RC1/mina-core-2.0.0-RC1.jar:/Users/julien/.m2/repository/org/apache/directory/shared/shared-ldap/0.9.19/shared-ldap-0.9.19.jar:/Users/julien/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.jar:/Users/julien/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar:/Users/julien/.m2/repository/org/apache/directory/shared/shared-i18n/0.9.19/shared-i18n-0.9.19.jar:/Users/julien/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar:/Users/julien/.m2/repository/org/apache/directory/shared/shared-ldap-schema/0.9.19/shared-ldap-schema-0.9.19.jar:/Users/julien/.m2/repository/org/apache/directory/shared/shared-ldap-schema-loader/0.9.19/shared-ldap-schema-loader-0.9.19.jar:/Users/julien/.m2/repository/org/apache/directory/shared/shared-ldap-schema-manager/0.9.19/shared-ldap-schema-manager-0.9.19.jar:/Users/julien/.m2/repository/org/apache/directory/shared/shared-cursor/0.9.19/shared-cursor-0.9.19.jar:/Users/julien/.m2/repository/org/apache/directory/shared/shared-ldap-jndi/0.9.19/shared-ldap-jndi-0.9.19.jar:/Users/julien/.m2/repository/org/apache/directory/shared/shared-asn1-codec/0.9.19/shared-asn1-codec-0.9.19.jar:/Users/julien/.m2/repository/org/apache/directory/shared/shared-asn1/0.9.19/shared-asn1-0.9.19.jar:/Users/julien/.m2/repository/org/apache/directory/shared/shared-ldap-constants/0.9.19/shared-ldap-constants-0.9.19.jar:/Users/julien/.m2/repository/org/apache/directory/shared/shared-ldap-converter/0.9.19/shared-ldap-converter-0.9.19.jar:/Users/julien/.m2/repository/org/apache/directory/shared/shared-ldap-schema-dao/0.9.19/shared-ldap-schema-dao-0.9.19.jar:/Users/julien/.m2/repository/org/apache/directory/shared/shared-ldif/0.9.19/shared-ldif-0.9.19.jar:/Users/julien/.m2/repository/org/apache/directory/shared/shared-dsml-parser/0.9.19/shared-dsml-parser-0.9.19.jar:/Users/julien/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar:/Users/julien/.m2/repository/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar:/Users/julien/.m2/repository/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.jar:/Users/julien/.m2/repository/org/assertj/assertj-core/3.4.1/assertj-core-3.4.1.jar:/Users/julien/.m2/repository/org/slf4j/slf4j-simple/1.7.21/slf4j-simple-1.7.21.jar:/Users/julien/.m2/repository/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar:/Users/julien/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.56.Final/netty-tcnative-boringssl-static-2.0.56.Final.jar:/Users/julien/.m2/repository/io/netty/netty-tcnative-classes/2.0.56.Final/netty-tcnative-classes-2.0.56.Final.jar:/Users/julien/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.56.Final/netty-tcnative-boringssl-static-2.0.56.Final-linux-x86_64.jar:/Users/julien/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.56.Final/netty-tcnative-boringssl-static-2.0.56.Final-linux-aarch_64.jar:/Users/julien/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.56.Final/netty-tcnative-boringssl-static-2.0.56.Final-osx-x86_64.jar:/Users/julien/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.56.Final/netty-tcnative-boringssl-static-2.0.56.Final-osx-aarch_64.jar:/Users/julien/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.56.Final/netty-tcnative-boringssl-static-2.0.56.Final-windows-x86_64.jar:/Users/julien/.m2/repository/com/aayushatharva/brotli4j/brotli4j/1.8.0/brotli4j-1.8.0.jar:/Users/julien/.m2/repository/com/aayushatharva/brotli4j/native-osx-aarch64/1.8.0/native-osx-aarch64-1.8.0.jar:/Users/julien/.m2/repository/org/openjdk/jmh/jmh-core/1.19/jmh-core-1.19.jar:/Users/julien/.m2/repository/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar:/Users/julien/.m2/repository/org/apache/commons/commons-math3/3.2/commons-math3-3.2.jar:/Users/julien/.m2/repository/io/netty/netty-resolver-dns-native-macos/4.1.89.Final/netty-resolver-dns-native-macos-4.1.89.Final-osx-x86_64.jar:/Users/julien/.m2/repository/io/netty/netty-resolver-dns-classes-macos/4.1.89.Final/netty-resolver-dns-classes-macos-4.1.89.Final.jar:/Users/julien/java/vert.x/src/test/java:/Users/julien/java/vert.x/src/test/classpath/jul com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit4 io.vertx.core.http.Http2Test,testRequestTimesOutWhenIndicatedPeriodExpiresWithoutAResponseFromRemoteServer
Connected to the target VM, address: '127.0.0.1:58311', transport: 'socket'
Starting test: Http2Test#testRequestTimesOutWhenIndicatedPeriodExpiresWithoutAResponseFromRemoteServer 
[main] ERROR io.netty.resolver.dns.DnsServerAddressStreamProviders - Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'. Use DEBUG level to see the full stack: java.lang.UnsatisfiedLinkError: failed to load the required native library
java.lang.Exception
	at io.vertx.core.http.HttpTest.lambda$null$427(HttpTest.java:2463)
	at io.vertx.test.core.AsyncTestBase.lambda$onFailure$0(AsyncTestBase.java:593)
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
	at io.vertx.core.http.impl.HttpClientRequestBase.fail(HttpClientRequestBase.java:165)
	at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:160)
	at io.vertx.core.http.impl.HttpClientRequestImpl.handleException(HttpClientRequestImpl.java:80)
	at io.vertx.core.http.impl.Http2ClientConnection$StreamImpl.handleException(Http2ClientConnection.java:535)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	at io.vertx.core.impl.ContextBase.emit(ContextBase.java:239)
	at io.vertx.core.http.impl.VertxHttp2Stream.onError(VertxHttp2Stream.java:90)
	at io.vertx.core.http.impl.Http2ClientConnection$Stream.onClose(Http2ClientConnection.java:374)
	at io.vertx.core.http.impl.Http2ConnectionBase.onStreamClosed(Http2ConnectionBase.java:153)
	at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.onStreamClosed(VertxHttp2ConnectionHandler.java:189)
	at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:357)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1007)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:963)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:515)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:521)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.closeStream(Http2ConnectionHandler.java:628)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.processRstStreamWriteResult(Http2ConnectionHandler.java:909)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.access$1100(Http2ConnectionHandler.java:66)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$4.operationComplete(Http2ConnectionHandler.java:824)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$4.operationComplete(Http2ConnectionHandler.java:821)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
	at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48)
	at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:52)
	at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:31)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
	at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48)
	at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:717)
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:272)
	at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:352)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:421)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
	at io.netty.handler.ssl.SslHandler.forceFlush(SslHandler.java:2147)
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:804)
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:781)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:925)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:197)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:925)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
	at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967)
	at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:254)
	at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.checkFlush(VertxHttp2ConnectionHandler.java:242)
	at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.writeReset(VertxHttp2ConnectionHandler.java:285)
	at io.vertx.core.http.impl.VertxHttp2Stream.doWriteReset(VertxHttp2Stream.java:241)
	at io.vertx.core.http.impl.VertxHttp2Stream.writeReset(VertxHttp2Stream.java:229)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	at io.vertx.core.impl.ContextBase.emit(ContextBase.java:239)
	at io.vertx.core.http.impl.Http2ClientConnection$StreamImpl.reset(Http2ClientConnection.java:665)
	at io.vertx.core.http.impl.HttpClientRequestImpl.reset(HttpClientRequestImpl.java:268)
	at io.vertx.core.http.impl.HttpClientRequestBase.handleTimeout(HttpClientRequestBase.java:213)
	at io.vertx.core.http.impl.HttpClientRequestBase.lambda$setTimeout$1(HttpClientRequestBase.java:155)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:932)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:903)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	at io.vertx.core.impl.ContextBase.emit(ContextBase.java:239)
	at io.vertx.core.impl.ContextInternal.emit(ContextInternal.java:194)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:921)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask$$$capture(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
```

We can see that the close event is triggered by the Netty layer when the stream reset has been written to the remote endpoint and there is no way to correlate it.

**Comment by vietj** [comment]
the best we could have I think is a way to know if the timer was fired on the HttpClientRequest that could be used to query it

**Comment by Sgitario** [comment]
From my point of view, a TimeoutException should be the right exception to throw as it would behave the same as in HTTP 1.1, but I'm not an expert here and I don't know the technical impediments. 

What I would like to do is to somehow map the `HttpClosedException` exceptions to `TimeoutException`, because we want to give users the same experience regardless of the HTTP protocol or the inner client (but of course, this is our problem, not yours), so if we could identify why the HttpClosedException exception was thrown, it would be good enough for us.

**Comment by vietj** [comment]
Timeout does not exist really in the HTTP protocol.

The main reason we cannot map it, is because we reset the stream, then Netty takes care of the reset operation which triggers the stream to be closed, I don't really see how we could map this.

The best we could do is have the information available on the HttpClientRequest, that could be queried to check whether the timeout has occured when an exception has been processed. Note that would not be 100% reliable, because you can have a timeout and an network failure at the same time.

**Comment by ddavoren** [comment]
Hi, 

I am also facing the same issue in regard to the TimeoutException no longer being thrown when upgrading from vertx 3 to vertx 4. 

Although there is no timeout in the HTTP protocol, from an application writers point of view I think it makes sense that a specific exception is raised to signify the event to the application (TimeoutException), and a reset event is then sent via netty (There may be technical reasons why this cannot be done I am not aware of).

This would allow the application to be independent of whether HTTP1.1 or HTTP2 is used, and also guarantee any timeout is actually a timeout, and appropriate timeout handling can be invoked in the application. If we trigger timeout handling based on TimeoutException (HTTP1.1) and HttpClosedException (HTTP2), we are open to triggering timeouts incorrectly. 

Is there any plan to review this logic?

Thanks.

**Comment by vietj** [comment]
the main reason @ddavoren is technical, the timeout resets the HTTP/2 stream via Netty, there is no possibility to make then vertx aware that this reset is actually a timeout.

**Comment by ddavoren** [comment]
Would it be possible to trigger the timeout to the application handler when the timeout is triggered in the vertx code, and queue the stream reset event for netty. Once netty has reset the stream it can callback to vertx which can do any cleanup required but the application handler would not need to be triggered.

**Comment by vietj** [comment]
as said above this is racy, as you can have a timeout close happen at the same time an actual TCP close happens (or receiving a GO_AWAY frame from the remote server)

**Comment by ddavoren** [comment]
Thanks for feedback.

My thoughts would be, its definitely better to get timeouts to the application writer, I agree there will be race conditions here but that will always be the case when there are local and remote events. 

I believe all these events are processed on the same event loop, so I think it would be safe to just process the first one to executed on the thread, and subsequent events execute any cleanup logic etc.  Even if there are events at the same time, if on the same thread, one event will win, and let the application process the event accordingly. 

If a timeout and TCP close event happen together, one will be processed first. 

Timeout first - vertx invokes timeout handler which throws TimeoutException to the app, which can then process its timeout logic. 
TCP close second - clean up logic executed, including closing any in flight transactions, any timed out events do not call back to the application as they have timed out. 

TCP close first - close events triggered and timeout is cancelled. Timeout may have elapsed but this should not cause a major problem.

From an application writers point of view, they can then handle these events accordingly. 

Without a timeout event, application writers will not be able to react this type of event like in vertx 3. 

If this is not possible, then it is worth updating the docs to say what type of exception is thrown in case of a timeout HTTP1.1 and HTTP2. At present the API states a TimeoutException is thrown.

**Comment by mmopenet** [comment]
Hi @vietj,

I think the proposal from @ddavoren to reset connection asynchronously, throw the TimeoutException and ignore HttpCloseException from netty sounds feasible. It would increase the race condition window, but only by a tiny bit. 
With the current implementation the reset is passed to netty from the timeout handler, however the server originated reset, go away or even response may already be in the buffer. In this cases the server messages are just ignored.

Now if the implementation is changed as suggested by @ddavoren. When timeout happens the reset is queued. If there are server originated frames (reset,  go away or response) and they are processed before the queued client reset, the reset can be ignored if the stream was closed, or sent if it was not. E.g. only headers frame received or partial payload. 

Unless i missed some implementation details that makes it impossible.

**Comment by vietj** [comment]
how about setting a timeout handler on HttpClientRequest that allows to application to be aware of when a timeout fires and keep track of it ?

**Comment by vietj** [comment]
here is a PR with a workaround : https://github.com/eclipse-vertx/vert.x/pull/4808 PTAL

**Comment by ddavoren** [comment]
That would definitely help.

Correct me if Im wrong, with the workaround in PR, the TimeoutException will now be raised instead of the HttpClosedException.

Heres part of the stacktrace I have for when the timeout does trigger and case a stream reset. 

`at [io.vertx.core.http.impl.HttpClientRequestBase.fail(HttpClientRequestBase.java:](https://confluence.openet.com/display/5G/io.vertx.core.http.impl.HttpClientRequestBase.fail(HttpClientRequestBase.java:)169)
at [io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:](https://confluence.openet.com/display/5G/io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:)164)
at [io.vertx.core.http.impl.HttpClientRequestImpl.handleException(HttpClientRequestImpl.java:](https://confluence.openet.com/display/5G/io.vertx.core.http.impl.HttpClientRequestImpl.handleException(HttpClientRequestImpl.java:)80)
at [io.vertx.core.http.impl.Http2ClientConnection$StreamImpl.handleException(Http2ClientConnection.java:](https://confluence.openet.com/display/5G/io.vertx.core.http.impl.Http2ClientConnection$StreamImpl.handleException(Http2ClientConnection.java:)542)
at [io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:](https://confluence.openet.com/display/5G/io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:)55)
at [io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:](https://confluence.openet.com/display/5G/io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:)158)
at [io.vertx.core.http.impl.VertxHttp2Stream.onException(VertxHttp2Stream.java:](https://confluence.openet.com/display/5G/io.vertx.core.http.impl.VertxHttp2Stream.onException(VertxHttp2Stream.java:)95)
at [io.vertx.core.http.impl.Http2ClientConnection$Stream.onClose(Http2ClientConnection.java:](https://confluence.openet.com/display/5G/io.vertx.core.http.impl.Http2ClientConnection$Stream.onClose(Http2ClientConnection.java:)381)
at [io.vertx.core.http.impl.Http2ConnectionBase.onStreamClosed(Http2ConnectionBase.java:](https://confluence.openet.com/display/5G/io.vertx.core.http.impl.Http2ConnectionBase.onStreamClosed(Http2ConnectionBase.java:)156)
at [io.vertx.core.http.impl.VertxHttp2ConnectionHandler.onStreamClosed(VertxHttp2ConnectionHandler.java:](https://confluence.openet.com/display/5G/io.vertx.core.http.impl.VertxHttp2ConnectionHandler.onStreamClosed(VertxHttp2ConnectionHandler.java:)188)
at [io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:](https://confluence.openet.com/display/5G/io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:)357)`

So now that HttpClientRequestBase.fail() method will convert from HttpClosedException to TimeoutException?

-----------------
This covers the case when the HttpClientRequest has been created. 
In vertx 3, we would also get a timeout if connection was not available i.e. DNS took too long, connection taking too long, etc. 

In vertx 4, the HttpClientRequest is not created until there is a connection and stream available. If there is a timeout before the request has even been created, will we get a TimeoutException for these cases, as was done in vertx 3. 

The reason is, once the application calls the send API, we want to be able to determine there was a timeout, whether that be DNS takes too long, connection takes too long, request sent but no response received, from the application point of view we just need to know if the API call has taken too long so we can take some sort of action. 

Thanks for all the info, really appreciate it!!

**Comment by vietj** [comment]
I updated the build due to a incorrect handling of the exception

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/pull/4808 as best effort

**Comment by ddavoren** [comment]
Great, thanks for all the help on this.
