### ISSUE TITLE
RedeployTest and StartStopListCommandsTestTests failing on power architecture

### ISSUE THREAD

**Issue by shreyakajbaje** [eclipse-vertx/vert.x#4622]
RedeployTest and StartStopListCommandsTestTests failing on power architecture 

### Version

- 4.3.7-SNAPSHOT
### Context

StartStopListCommandsTestTests -

Running io.vertx.core.impl.launcher.commands.StartStopListCommandsTest
Tests run: 9, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 3.415 sec <<< FAILURE! - in io.vertx.core.impl.launcher.commands.StartStopListCommandsTest
testStartListStopWithId(io.vertx.core.impl.launcher.commands.StartStopListCommandsTest)  Time elapsed: 2.219 sec  <<< FAILURE!
java.lang.AssertionError:
Expecting:
 <"Listing vert.x applications...
No vert.x application found.
">
to contain:
 <"hello">
        at io.vertx.core.impl.launcher.commands.StartStopListCommandsTest.testStartListStopWithId(StartStopListCommandsTest.java:189)

testStartListStop(io.vertx.core.impl.launcher.commands.StartStopListCommandsTest)  Time elapsed: 0.058 sec  <<< FAILURE!
java.lang.AssertionError:
Expecting:
 <"Listing vert.x applications...
No vert.x application found.
">
to contain:
 <"     io.vertx.core.impl.launcher.commands.HttpTestVerticle">
        at io.vertx.core.impl.launcher.commands.StartStopListCommandsTest.testStartListStop(StartStopListCommandsTest.java:56)

testStartListStopWithJVMOptions(io.vertx.core.impl.launcher.commands.StartStopListCommandsTest)  Time elapsed: 0.433 sec  <<< FAILURE!
java.lang.AssertionError:
Expecting:
 <null>
to be equal to:
 <"bar">
ignoring case considerations
        at io.vertx.core.impl.launcher.commands.StartStopListCommandsTest.testStartListStopWithJVMOptions(StartStopListCommandsTest.java:128)

testStartListStopWithIdAndAnotherArgument(io.vertx.core.impl.launcher.commands.StartStopListCommandsTest)  Time elapsed: 0.042 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at io.vertx.core.impl.launcher.commands.StartStopListCommandsTest.testStartListStopWithIdAndAnotherArgument(StartStopListCommandsTest.java:223)

testStartListStopWithIdAndAnotherArgumentBeforeId(io.vertx.core.impl.launcher.commands.StartStopListCommandsTest)  Time elapsed: 0.051 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at io.vertx.core.impl.launcher.commands.StartStopListCommandsTest.testStartListStopWithIdAndAnotherArgumentBeforeId(StartStopListCommandsTest.java:260)

testStartListStopWithoutCommand(io.vertx.core.impl.launcher.commands.StartStopListCommandsTest)  Time elapsed: 0.047 sec  <<< FAILURE!
java.lang.AssertionError:
Expecting:
 <"Listing vert.x applications...
No vert.x application found.
">
to contain:
 <"     io.vertx.core.impl.launcher.commands.HttpTestVerticle">
        at io.vertx.core.impl.launcher.commands.StartStopListCommandsTest.testStartListStopWithoutCommand(StartStopListCommandsTest.java:93)

RedeployTest -

Tests run: 17, Failures: 5, Errors: 12, Skipped: 0, Time elapsed: 250.952 sec <<< FAILURE! - in io.vertx.core.impl.launcher.commands.RedeployTest
testStartingApplicationInRedeployModeWithFileConf2(io.vertx.core.impl.launcher.commands.RedeployTest)  Time elapsed: 24.179 sec  <<< ERROR!
java.lang.IllegalStateException: Timed out
        at io.vertx.test.core.AsyncTestBase.assertWaitUntil(AsyncTestBase.java:619)
        at io.vertx.core.impl.launcher.commands.CommandTestBase.assertWaitUntil(CommandTestBase.java:103)
        at io.vertx.core.impl.launcher.commands.RedeployTest.waitForTermination(RedeployTest.java:32)
        at io.vertx.core.impl.launcher.commands.RedeployTest.tearDown(RedeployTest.java:57)

testStartingApplicationInRedeployModeWithInlineOptions2(io.vertx.core.impl.launcher.commands.RedeployTest)  Time elapsed: 20.821 sec  <<< FAILURE!
java.lang.AssertionError:
Expecting actual not to be null
        at io.vertx.core.impl.launcher.commands.RedeployTest.testStartingApplicationInRedeployModeWithInlineOptions2(RedeployTest.java:280)

testStartingApplicationInRedeployModeWithInlineOptions2(io.vertx.core.impl.launcher.commands.RedeployTest)  Time elapsed: 20.821 sec  <<< ERROR!
java.lang.IllegalStateException: Timed out
        at io.vertx.test.core.AsyncTestBase.assertWaitUntil(AsyncTestBase.java:619)
        at io.vertx.core.impl.launcher.commands.CommandTestBase.assertWaitUntil(CommandTestBase.java:103)
        at io.vertx.core.impl.launcher.commands.RedeployTest.waitForTermination(RedeployTest.java:32)
        at io.vertx.core.impl.launcher.commands.RedeployTest.tearDown(RedeployTest.java:57)

testRedeployment(io.vertx.core.impl.launcher.commands.RedeployTest)  Time elapsed: 40.781 sec  <<< ERROR!
java.lang.IllegalStateException: Timed out
        at io.vertx.test.core.AsyncTestBase.assertWaitUntil(AsyncTestBase.java:619)
        at io.vertx.core.impl.launcher.commands.CommandTestBase.assertWaitUntil(CommandTestBase.java:111)
        at io.vertx.core.impl.launcher.commands.RedeployTest.testRedeployment(RedeployTest.java:197)

testRedeployment(io.vertx.core.impl.launcher.commands.RedeployTest)  Time elapsed: 40.782 sec  <<< ERROR!
java.lang.IllegalStateException: Timed out
        at io.vertx.test.core.AsyncTestBase.assertWaitUntil(AsyncTestBase.java:619)
        at io.vertx.core.impl.launcher.commands.CommandTestBase.assertWaitUntil(CommandTestBase.java:103)
        at io.vertx.core.impl.launcher.commands.RedeployTest.waitForTermination(RedeployTest.java:32)
        at io.vertx.core.impl.launcher.commands.RedeployTest.tearDown(RedeployTest.java:57)

Other failing native transport tests -
Tests run: 107, Failures: 107, Errors: 0, Skipped: 0, Time elapsed: 0.112 sec <<< FAILURE! - in io.vertx.core.file.FileSystemTest
Tests run: 63, Failures: 60, Errors: 0, Skipped: 3, Time elapsed: 0.067 sec <<< FAILURE! - in io.vertx.core.http.Http2ClientTest
Tests run: 472, Failures: 472, Errors: 0, Skipped: 0, Time elapsed: 1.818 sec <<< FAILURE! - in io.vertx.core.http.Http1xTest
Tests run: 5, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec <<< FAILURE! - in io.vertx.core.http.Http2BrotliCompressionTest
Tests run: 5, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec <<< FAILURE! - in io.vertx.core.http.Http1xBrotliCompressionTest

### Steps to reproduce

1. mvn package
2. mvn test

### Extra

- Linux eltp1.novalocal 4.18.0-383.el8.ppc64le
- openjdk version "1.8.0_362"
OpenJDK Runtime Environment (build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)

**Comment by vietj** [comment]
Please reopen at https://github.com/eclipse-vertx/vertx-launcher
