### ISSUE TITLE
Intermittently seeing no handles for address error with vertx eventbus 

### ISSUE THREAD

**Issue by arushi315** [eclipse-vertx/vert.x#4686]
### Questions

In my single node vertx application, I noticed that one of the consumer which was supposed to be called at service start startup was not handled after a publish event and I noticed this happening intermittently. To further look into this I added some logging in the EventBusImpl class in vertx-core. 

Sample code for publish and consumer to an address: 
``` 
@PostConstruct
    public void init() {
        vertx.eventBus().consumer("test1").toObservable()
                .subscribe(msg -> {
                    LOGGER.info("Message consumed on address test1.");
                }, ex -> LOGGER.error("Error on test1.", ex));
    }

Another method calls: 
vertx.eventBus().publish("test1", "some message");
```

Added logging in vertx-core:
In EventBusImpl
```
@Override
  public EventBus publish(String address, Object message, DeliveryOptions options) {
    log.debug("Publish is called for address " + address);
    sendOrPubInternal(createMessage(false, address, options.getHeaders(), message, options.getCodecName()), options, null, null);
    return this;
  }


  @Override
  public <T> MessageConsumer<T> consumer(String address) {
    checkStarted();
    Objects.requireNonNull(address, "address");
    log.debug("Consuming message for address " + address);
    return new MessageConsumerImpl<>(vertx, vertx.getOrCreateContext(), this, address,  false);
  }


private <T> void sendLocally(OutboundDeliveryContext<T> sendContext) {
    ReplyException failure = deliverMessageLocally(sendContext.message);
    if (failure != null) {
      sendContext.written(failure);
    } else {
      sendContext.written(null);
    }
    log.debug("Publishing message locally " + sendContext.message.address() + " . Failure: {}", failure);
  }

```
 
In ClusteredEventBus

```
@Override
  protected <T> void sendOrPub(OutboundDeliveryContext<T> sendContext) {
    log.debug("Publishing message ClusteredEventBus " + sendContext.message.address());
    if (((ClusteredMessage) sendContext.message).getRepliedTo() != null) {
      clusteredSendReply(((ClusteredMessage) sendContext.message).getRepliedTo(), sendContext);
    } else if (sendContext.options.isLocalOnly()) {
      super.sendOrPub(sendContext);
    } else {
      Serializer serializer = Serializer.get(sendContext.ctx);
      if (sendContext.message.isSend()) {
        Promise<String> promise = sendContext.ctx.promise();
        serializer.queue(sendContext.message, nodeSelector::selectForSend, promise);
        promise.future().onComplete(ar -> {
          if (ar.succeeded()) {
            sendToNode(sendContext, ar.result());
          } else {
            sendOrPublishFailed(sendContext, ar.cause());
          }
        });
      } else {
        Promise<Iterable<String>> promise = sendContext.ctx.promise();
        serializer.queue(sendContext.message, nodeSelector::selectForPublish, promise);
        promise.future().onComplete(ar -> {
          if (ar.succeeded()) {
            sendToNodes(sendContext, ar.result());
          } else {
            sendOrPublishFailed(sendContext, ar.cause());
          }
        });
      }
    }
  }
```

Observed logs when consumer is called successfully:
```
(main) [i.v.c.e.i.EventBusImpl] - Publish is called for address test1
(main) [i.v.c.e.i.c.ClusteredEventBus] - Publishing message ClusteredEventBus test1
(main) [i.v.c.e.i.EventBusImpl] - Consuming message for address test1
(vert.x-eventloop-thread-0) [i.v.c.e.i.EventBusImpl] - Publishing message locally test1 . Failure: {}
```
 
Observed logs when the handler is not found:
```
(main) [i.v.c.e.i.EventBusImpl] - Publish is called for address test1
(main) [i.v.c.e.i.c.ClusteredEventBus] - Publishing message ClusteredEventBus test1
(main) [i.v.c.e.i.EventBusImpl] - Consuming message for address test1
(vert.x-eventloop-thread-0) [i.v.c.e.i.EventBusImpl] - Publishing message locally test1 . Failure: {}
io.vertx.core.eventbus.ReplyException: No handlers for address test1
	at io.vertx.core.eventbus.impl.EventBusImpl.deliverMessageLocally(EventBusImpl.java:395)
	at io.vertx.core.eventbus.impl.EventBusImpl.sendLocally(EventBusImpl.java:351)
	at io.vertx.core.eventbus.impl.EventBusImpl.sendOrPub(EventBusImpl.java:339)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.sendToNodes(ClusteredEventBus.java:351)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.lambda$sendOrPub$6(ClusteredEventBus.java:218)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
	at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.spi.cluster.impl.DefaultNodeSelector.lambda$selectForPublish$1(DefaultNodeSelector.java:51)
	at io.vertx.core.spi.cluster.impl.selector.Selectors.lambda$withSelector$1(Selectors.java:49)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.Promise.complete(Promise.java:66)
	at io.vertx.core.spi.cluster.impl.selector.Selectors.dataReceived(Selectors.java:85)
	at io.vertx.core.spi.cluster.impl.selector.Selectors.lambda$initialize$2(Selectors.java:64)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Version

Vertx version: 4.3.7
Seeing the same behavior with 4.3.8 but did not observe this with 4.1.5
Java version: 11
Platform: Windows Server 2012

Please guide on how to troubleshoot this further and let me know if you require more details.

**Comment by arushi315** [comment]
Also sorry I created this as a bug but feel free to move it to a general query.

**Comment by arushi315** [comment]
Actually not necessarily sequence of events because here are the logs from another address:
Here first no handler error seems fine but the next one should not have been there since consumer was there at 15:45:26.006-0400 and publish event happened at 15:46:23.487-0400
```
2023-05-02 15:45:25.912-0400 node1 DEBUG (main) [i.v.c.e.i.EventBusImpl] - Publish is called for address test2
2023-05-02 15:45:25.912-0400 node1 DEBUG (main) [i.v.c.e.i.c.ClusteredEventBus] - Publishing message ClusteredEventBus test2
2023-05-02 15:45:25.912-0400 node1 DEBUG (vert.x-eventloop-thread-0) [i.v.c.e.i.EventBusImpl] - Publishing message locally test2 . Failure: {}
	io.vertx.core.eventbus.ReplyException: No handlers for address test2
2023-05-02 15:45:26.006-0400 node1 DEBUG (main) [i.v.c.e.i.EventBusImpl] - Consuming message for address test2
2023-05-02 15:46:23.487-0400 node1 DEBUG (main) [i.v.c.e.i.EventBusImpl] - Publish is called for address test2
2023-05-02 15:46:23.487-0400 node1 DEBUG (main) [i.v.c.e.i.c.ClusteredEventBus] - Publishing message ClusteredEventBus test2
2023-05-02 15:46:23.487-0400 node1 DEBUG (vert.x-eventloop-thread-0) [i.v.c.e.i.EventBusImpl] - Publishing message locally test2 . Failure: {}
    io.vertx.core.eventbus.ReplyException: No handlers for address test2
2023-05-02 15:46:23.534-0400 node1 DEBUG (main) [i.v.c.e.i.EventBusImpl] - Consuming message for address test2
2023-05-02 16:16:23.796-0400 node1 DEBUG (vert.x-eventloop-thread-0) [i.v.c.e.i.EventBusImpl] - Publish is called for address test2
2023-05-02 16:16:23.796-0400 node1 DEBUG (vert.x-eventloop-thread-0) [i.v.c.e.i.c.ClusteredEventBus] - Publishing message ClusteredEventBus test2
2023-05-02 16:16:23.796-0400 node1 DEBUG (vert.x-eventloop-thread-0) [i.v.c.e.i.EventBusImpl] - Publishing message locallytest2 . Failure: {}
```

**Comment by arushi315** [comment]
Hi @vietj 
Can you review this when you get a chance? 
I am looking to upgrade vertx for an upcoming release, any guidance on this would be really helpful.

**Comment by tsegismont** [comment]
Hi @arushi315 , consumer registration is an asynchronous process, are your sure the message to `test1` address is sent after the consumer is registered? You could this by registering a [`completionHandler`](https://vertx.io/docs/apidocs/io/vertx/core/eventbus/MessageConsumer.html#completionHandler-io.vertx.core.Handler-) on the consumer.

**Comment by arushi315** [comment]
Hi @tsegismont 
Thanks for your response. 
Let me add that and I will get back to you.

**Comment by arushi315** [comment]
Hi @tsegismont
I added the [completionHandler](https://vertx.io/docs/apidocs/io/vertx/core/eventbus/MessageConsumer.html#completionHandler-io.vertx.core.Handler-) on the consumer and looks like publish event is actually happening before the consumer registration completes. 
Surprising that I am seeing this more often in the latest versions and didn't discover earlier, any idea on that? I am still going to run a few more tests to make sure I am not missing anything. 

Is there any mechanism out of the box to retry the publish if for any reason consumer did not receive the message?
