### ISSUE TITLE
SslContextProvider performance issues with SNI enabled

### ISSUE THREAD

**Issue by conet** [eclipse-vertx/vert.x#4693]
### Version

4.4.1

### Context

We encountered high CPU usage on some https server instances after updating from 4.3.8 to 4.4.1. We did the update to benefit from [this feature](https://github.com/eclipse-vertx/vert.x/pull/4568) and tracked down the performance issue to the same feature. We need the feature so we would like this performance issue to be fixed.

During profiling this call stack was the highest contributor to the load:

```
"vert.x-internal-blocking-16" #56 prio=5 os_prio=0 cpu=7893060.28ms elapsed=38966.62s tid=0x00007f327c3a1000 nid=0x307fea runnable  [0x00007f324d2a3000]
   java.lang.Thread.State: RUNNABLE
	at sun.security.provider.SHA2.implCompressCheck(java.base@11.0.19/SHA2.java:131)
	at sun.security.provider.SHA2.implCompress(java.base@11.0.19/SHA2.java:120)
	at sun.security.provider.DigestBase.engineUpdate(java.base@11.0.19/DigestBase.java:124)
	at java.security.MessageDigest$Delegate.engineUpdate(java.base@11.0.19/MessageDigest.java:623)
	at java.security.MessageDigest.update(java.base@11.0.19/MessageDigest.java:355)
	at com.sun.crypto.provider.HmacCore.engineDoFinal(java.base@11.0.19/HmacCore.java:225)
	at javax.crypto.Mac.doFinal(java.base@11.0.19/Mac.java:581)
	at javax.crypto.Mac.doFinal(java.base@11.0.19/Mac.java:624)
	at com.sun.crypto.provider.PBKDF2KeyImpl.deriveKey(java.base@11.0.19/PBKDF2KeyImpl.java:192)
	at com.sun.crypto.provider.PBKDF2KeyImpl.<init>(java.base@11.0.19/PBKDF2KeyImpl.java:117)
	at com.sun.crypto.provider.PBKDF2Core.engineGenerateSecret(java.base@11.0.19/PBKDF2Core.java:69)
	at com.sun.crypto.provider.PBES2Core.engineInit(java.base@11.0.19/PBES2Core.java:280)
	at com.sun.crypto.provider.PBES2Core.engineInit(java.base@11.0.19/PBES2Core.java:307)
	at javax.crypto.Cipher.implInit(java.base@11.0.19/Cipher.java:847)
	at javax.crypto.Cipher.chooseProvider(java.base@11.0.19/Cipher.java:901)
	- locked <0x00000007c532a9a0> (a java.lang.Object)
	at javax.crypto.Cipher.init(java.base@11.0.19/Cipher.java:1576)
	at javax.crypto.Cipher.init(java.base@11.0.19/Cipher.java:1507)
	at sun.security.pkcs12.PKCS12KeyStore.lambda$engineGetKey$0(java.base@11.0.19/PKCS12KeyStore.java:386)
	at sun.security.pkcs12.PKCS12KeyStore$$Lambda$733/0x00000008405d5040.tryOnce(java.base@11.0.19/Unknown Source)
	at sun.security.pkcs12.PKCS12KeyStore$RetryWithZero.run(java.base@11.0.19/PKCS12KeyStore.java:276)
	at sun.security.pkcs12.PKCS12KeyStore.engineGetKey(java.base@11.0.19/PKCS12KeyStore.java:381)
	at sun.security.util.KeyStoreDelegator.engineGetKey(java.base@11.0.19/KeyStoreDelegator.java:90)
	at java.security.KeyStore.getKey(java.base@11.0.19/KeyStore.java:1057)
	at sun.security.ssl.SunX509KeyManagerImpl.<init>(java.base@11.0.19/SunX509KeyManagerImpl.java:145)
	at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(java.base@11.0.19/KeyManagerFactoryImpl.java:76)
	at javax.net.ssl.KeyManagerFactory.init(java.base@11.0.19/KeyManagerFactory.java:271)
	at io.vertx.core.net.impl.SslContextProvider.loadKeyManagerFactory(SslContextProvider.java:149)
	at io.vertx.core.net.impl.SslContextProvider.resolveKeyManagerFactory(SslContextProvider.java:167)
	at io.vertx.core.net.impl.SslChannelProvider.lambda$null$1(SslChannelProvider.java:105)
	at io.vertx.core.net.impl.SslChannelProvider$$Lambda$840/0x0000000840656c40.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.19/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.19/ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@11.0.19/Thread.java:829)
```

### Do you have a reproducer?

We managed to create [a reproducer](https://github.com/conet/vertx-tls-reproducer/tree/sni-perf-test) in a hurry, sorry for the possible mess in there.

### Steps to reproduce

1. Run the as is (with SNI disabled) and observe the load
2. Uncomment the two lines to enable SNI [in the server](https://github.com/conet/vertx-tls-reproducer/blob/sni-perf-test/src/test/java/SNIPerfTest.java#L85) and [in the client](https://github.com/conet/vertx-tls-reproducer/blob/sni-perf-test/src/test/java/SNIPerfTest.java#L102)
3. Run the test and observe the much higher CPU load

Without SNI `KeyManagerFactory.init` is called twice while with SNI it is called for every connection, it seems like [this is the CPU expensive part](https://github.com/eclipse-vertx/vert.x/blob/4.4.1/src/main/java/io/vertx/core/net/impl/SslContextProvider.java#L143):

```
                String keyStoreType = KeyStore.getDefaultType();
                KeyStore ks = KeyStore.getInstance(keyStoreType);
                ks.load((InputStream)null, (char[])null);
                ks.setKeyEntry("key", mgr.getPrivateKey((String)null), new char[0], mgr.getCertificateChain((String)null));
                String keyAlgorithm = KeyManagerFactory.getDefaultAlgorithm();
                KeyManagerFactory kmf = KeyManagerFactory.getInstance(keyAlgorithm);
                kmf.init(ks, new char[0]);
                return kmf;
```

### Extra
```
Linux 5.14.0-162.18.1.el9_1.x86_64
java -version
openjdk version "11.0.19" 2023-04-18 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.19.0.7-1.el9_1) (build 11.0.19+7-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.19.0.7-1.el9_1) (build 11.0.19+7-LTS, mixed mode, sharing)
```

**Comment by conet** [comment]
Another thing to consider is to add the SNI flag to `SSLOptions` to be able to change it at runtime if possible.

**Comment by vietj** [comment]
I will have a look before 4.4.2 is released

**Comment by vietj** [comment]
so the main reason it happens is that we need to load the server certificate (on a worker pool) in a dynamic fashion for every connection, I will see if we can cache this part

**Comment by conet** [comment]
I think caching the certificates by server name is a must, the overhead of loading the certificate every time is huge on a https server with high connection rate.

**Comment by vietj** [comment]
yes I think it can be achieved easily, I'll come back to you soon

**Comment by vietj** [comment]
@conet please have a look https://github.com/eclipse-vertx/vert.x/pull/4694

**Comment by conet** [comment]
Looks good, although I haven’t ran the code because I don't have a build from source environment set up. I can give some snapshot builds a try though.

**Comment by vietj** [comment]
I tried with your reproducer.

**Comment by vietj** [comment]
normally snapshots should be deployed for 4.4.2-SNAPSHOT :
https://github.com/eclipse-vertx/vert.x/actions/runs/4949272844

**Comment by conet** [comment]
I tested the snapshots, the problem is fixed, thank you.
