### ISSUE TITLE
Does Vert.x support the operation of converting asynchronous results to synchronous ones?

### ISSUE THREAD

**Issue by yhsweetlife** [eclipse-vertx/vert.x#4697]
### Questions

I have a method with a synchronous return value, but it internally calls an asynchronous operation.

Now I use ".toCompletionStage().toCompletableFuture().get". But I have encountered blocked thread problems. I am very confused and suspect it's related to the thread pool. Who can help me explain this?

### Version

4.3.7

### Context

`public String load(){
    
     Future<String> future = /* sample code return future*/;
     String data = future.toCompletionStage().toCompletableFuture().get();
     return data;
}
vertx.consumer("topic", req->{
     String data = load();
     req.reply(data);
}`

When I request the "topic", it will block eventloop thread.

Exception:

`WARN  [vertx-blocked-thread-checker] io.vertx.core.impl.BlockedThreadChecker  - Thread Thread[vert.x-eventloop-thread-4,5,main] has been blocked for 5569735 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at sun.misc.Unsafe.park(Native Method) ~[?:1.8.0_351]
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175) ~[?:1.8.0_351]
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707) ~[?:1.8.0_351]
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3334) ~[?:1.8.0_351]
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742) ~[?:1.8.0_351]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[?:1.8.0_351]
	at com.blocking.DataServingFunction.lambda$start$2(DataServingFunction.java:54) ~[classes/:?]
	at com.blocking.DataServingFunction$$Lambda$95/510417753.handle(Unknown Source) ~[?:?]
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264) ~[vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:177) ~[vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.execute(HandlerRegistration.java:137) ~[vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.eventbus.impl.DeliveryContextBase.next(DeliveryContextBase.java:72) ~[vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.eventbus.impl.DeliveryContextBase.dispatch(DeliveryContextBase.java:43) ~[vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:98) ~[vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:183) ~[vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:168) ~[vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:49) ~[vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.eventbus.impl.HandlerRegistration$$Lambda$116/1428033794.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.86.Final.jar:4.1.86.Final]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_351]`

**Comment by tsegismont** [comment]
You cannot block an event loop to wait for a future result, otherwise the event loop cannot handle any event.

If a part of your code must be implemented in an imperative, blocking fashion, make sure this part is invoked on worker threads. In this case, it is safe to convert Vert.x futures to `CompletableFuture` and block using `get()`.

**Comment by yhsweetlife** [comment]
Thanks. I still have a question that confuses me. Blocking fashion is invoked on executeBlocking. When I wait for executeBlocking result, the thread will be blocking. 
Can you help me explain it ?
Here is the code snippet.
`
vertx.consumer("topic", req->{
   vertx.executeBlocking(h -> {
                    String data = (String) vertx.executeBlocking(h2 -> 
                                                       h2.complete("something")).toCompletionStage().toCompletableFuture().get();
                    h.complete(data);
                    //String data = (String) future.toCompletionStage().toCompletableFuture().get();
            }).onSuccess(h->{
                req.reply(h);
            });
`

When I request the "topic", it still will block eventloop thread.

**Comment by tsegismont** [comment]
`executeBlocking` is a non-blocking, asynchronous method, that offloads a task to a worker pool and returns a future which signals the completion (possibly with a result).

It is meant to be invoked on an event loop perform blocking (or cpu-intensive) tasks.

If you convert the future return by `executingBlocking` to `CompletableFuture` and invoked `get` on an event loop, you are still making a blocking call on the event loop.
