### ISSUE TITLE
cannot decodeValue to JsonObject with reproducer

### ISSUE THREAD

**Issue by gillbates** [eclipse-vertx/vert.x#4730]
### Version

4.4.2

### Do you have a reproducer?

```
        String json = "{\n" +
                "    \"result\": [\n" +
                "        {\n" +
                "            \"id\": \"aaa\",\n" +
                "            \"zone_id\": \"bbb\",\n" +
                "            \"meta\": {\n" +
                "                \"auto_added\": false,\n" +
                "                \"managed_by_apps\": false,\n" +
                "                \"managed_by_argo_tunnel\": false,\n" +
                "                \"source\": \"primary\"\n" +
                "            },\n" +
                "            \"comment\": null,\n" +
                "            \"tags\": [],\n" +
                "            \"created_on\": \"2023-05-09T11:43:07.088802Z\",\n" +
                "            \"modified_on\": \"2023-05-09T11:43:07.088802Z\"\n" +
                "        },\n" +
                "        {\n" +
                "            \"id\": \"ccc\",\n" +
                "            \"zone_id\": \"ddd\",\n" +
                "            \"meta\": {\n" +
                "                \"auto_added\": false,\n" +
                "                \"managed_by_apps\": false,\n" +
                "                \"managed_by_argo_tunnel\": false,\n" +
                "                \"origin_worker_id\": \"eee\",\n" +
                "                \"source\": \"primary\"\n" +
                "            },\n" +
                "            \"comment\": null,\n" +
                "            \"tags\": [],\n" +
                "            \"created_on\": \"2023-05-13T12:30:06.837565Z\",\n" +
                "            \"modified_on\": \"2023-05-13T12:30:06.837565Z\"\n" +
                "        }\n" +
                "    ],\n" +
                "    \"success\": true,\n" +
                "    \"errors\": [],\n" +
                "    \"messages\": [],\n" +
                "    \"result_info\": {\n" +
                "        \"page\": 1,\n" +
                "        \"per_page\": 100,\n" +
                "        \"count\": 4,\n" +
                "        \"total_count\": 4,\n" +
                "        \"total_pages\": 1\n" +
                "    }\n" +
                "}";

        Object object = Json.decodeValue(json);
        if (object instanceof JsonObject) {
            log.debug("json is JsonObject");
        }
        JsonObject jsonObject = Json.decodeValue(json, JsonObject.class);
        log.debug("deserialized json: {}", jsonObject);
```

and it will always throw an exception at
```
        JsonObject jsonObject = Json.decodeValue(json, JsonObject.class);
```

Exception:

```
Exception in thread "main" io.vertx.core.json.DecodeException: Failed to decode:Unrecognized field "result" (class io.vertx.core.json.JsonObject), not marked as ignorable (one known property: "map"])
 at [Source: (String)"{
    "result": [
        {
            "id": "aaa",
            "zone_id": "bbb",
            "meta": {
                "auto_added": false,
                "managed_by_apps": false,
                "managed_by_argo_tunnel": false,
                "source": "primary"
            },
            "comment": null,
            "tags": [],
            "created_on": "2023-05-09T11:43:07.088802Z",
            "modified_on": "2023-05-09T11:43:07.088802Z"
        },
        {
            "id": "ccc",
   "[truncated 657 chars]; line: 2, column: 16] (through reference chain: io.vertx.core.json.JsonObject["result"])
	at io.vertx.core.json.jackson.DatabindCodec.fromParser(DatabindCodec.java:129)
	at io.vertx.core.json.jackson.DatabindCodec.fromString(DatabindCodec.java:90)
	at io.vertx.core.json.Json.decodeValue(Json.java:83)
	at com.runtu.commons.cloud.cloudflare.CFUtil.main(CFUtil.java:83)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "result" (class io.vertx.core.json.JsonObject), not marked as ignorable (one known property: "map"])
 at [Source: (String)"{
    "result": [
        {
            "id": "aaa",
            "zone_id": "bbb",
            "meta": {
                "auto_added": false,
                "managed_by_apps": false,
                "managed_by_argo_tunnel": false,
                "source": "primary"
            },
            "comment": null,
            "tags": [],
            "created_on": "2023-05-09T11:43:07.088802Z",
            "modified_on": "2023-05-09T11:43:07.088802Z"
        },
        {
            "id": "ccc",
   "[truncated 657 chars]; line: 2, column: 16] (through reference chain: io.vertx.core.json.JsonObject["result"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1138)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2224)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1709)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1687)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2974)
	at io.vertx.core.json.jackson.DatabindCodec.fromParser(DatabindCodec.java:126)
	... 3 more
```

### Extra

as object is clearly an instance of JsonObject, maybe its a bug that we cannot directly decode to JsonObject?

**Comment by keksipurkki** [comment]
I have also bumped into this. Essentially, the Jackson object mapper should be taught how to map to JsonObject which is internally backed by a Map<String, Object>.

You can workaround this like so: https://gist.github.com/keksipurkki/49c5b050e7f6fe382eb7f0a006e78754

While I think this technically a bug, a better solution is to obviously create the JsonObject using its constructor.

**Comment by tsegismont** [comment]
This will be solved in Vert.x 5 by https://github.com/eclipse-vertx/vert.x/pull/4709
