### ISSUE TITLE
Intermittent failure in BlockedThreadCheckerTest

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vert.x#4745]
```
2023-06-20T05:13:44.2655701Z Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 23.047 sec <<< FAILURE! - in io.vertx.core.BlockedThreadCheckerTest
2023-06-20T05:13:44.2657913Z testBlockCheckExecuteBlocking(io.vertx.core.BlockedThreadCheckerTest)  Time elapsed: 3.012 sec  <<< ERROR!
2023-06-20T05:13:44.2659803Z Starting test: VertxUseDaemonThreadTest#testUseDaemonThread[0: useDaemonThread=true] 
2023-06-20T05:13:44.2660305Z java.util.ConcurrentModificationException: null
2023-06-20T05:13:44.2660929Z 	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1604)
2023-06-20T05:13:44.2661644Z 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
2023-06-20T05:13:44.2662402Z 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
2023-06-20T05:13:44.2663636Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
2023-06-20T05:13:44.2664370Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2023-06-20T05:13:44.2665098Z 	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
2023-06-20T05:13:44.2665774Z 	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
2023-06-20T05:13:44.2666462Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2023-06-20T05:13:44.2667169Z 	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
2023-06-20T05:13:44.2667921Z 	at io.vertx.core.BlockedThreadCheckerTest.expectMessage(BlockedThreadCheckerTest.java:38)
2023-06-20T05:13:44.2668841Z 	at io.vertx.core.BlockedThreadCheckerTest.testBlockCheckExecuteBlocking(BlockedThreadCheckerTest.java:155)
2023-06-20T05:13:44.2669403Z 
```

**Comment by tsegismont** [comment]
Closed in afd587f6d
