### ISSUE TITLE
Intermittent failure in 

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vert.x#4746]
```
2023-06-19T05:08:16.9015840Z Tests run: 472, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 95.313 sec <<< FAILURE! - in io.vertx.core.http.Http1xTest
2023-06-19T05:08:16.9018312Z testClientConnectionExceptionHandler(io.vertx.core.http.Http1xTest)  Time elapsed: 0.032 sec  <<< FAILURE!
2023-06-19T05:08:16.9019681Z java.lang.AssertionError: Connection was closed
2023-06-19T05:08:16.9021603Z 	at org.junit.Assert.fail(Assert.java:89)
2023-06-19T05:08:16.9084281Z 	at io.vertx.test.core.AsyncTestBase.fail(AsyncTestBase.java:268)
2023-06-19T05:08:16.9810930Z 	at io.vertx.test.core.AsyncTestBase.lambda$onSuccess$3(AsyncTestBase.java:682)
2023-06-19T05:08:16.9834053Z 	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
2023-06-19T05:08:16.9835184Z 	at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69)
2023-06-19T05:08:16.9835952Z 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
2023-06-19T05:08:16.9836729Z 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
2023-06-19T05:08:16.9837937Z 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
2023-06-19T05:08:16.9838730Z 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
2023-06-19T05:08:16.9839422Z 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2023-06-19T05:08:16.9840130Z 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-06-19T05:08:16.9840833Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-06-19T05:08:16.9841866Z 	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by tsegismont** [comment]
Outdated
