### ISSUE TITLE
HttpClient send request may get an expiring connection

### ISSUE THREAD

**Issue by ben1222** [eclipse-vertx/vert.x#4761]
### Version

4.4.4

### Context

I encountered an exception when sending request using `HttpClient`, after investigation, looks like it is due to acquiring a connection from `SimpleConnectionPool` that at almost same time, the connection got evicted from the `SimpleConnectionPool` due to keep-alive timeout.
Reading the `SimpleConnectionPool` implementation, the `evict` will schedule `remove` action for the slots of evicted connections, and if an `acquire` action happens between the `evict` and `remove` actions, the "evicted" connection can still be acquired.
This slot will be removed and closed soon and when the `HttpClient` is using this connection, it may hit exception.

### Do you have a reproducer?

Tried to create a unit test to illustrate the issue.
I changed the `HttpClientImpl.EXPIRED_CHECKER` to be able to get the timestamp when keep-alive timeout is checked.
So that it could schedule requests to run at almost same time when next time the keep-alive timeout will evict the connection.

```java
  private void roundHandler(Vertx vertx, AtomicInteger round, HttpClient client, CountDownLatch latch,
    int requestCount, long intervalMs, AtomicLong msAdjuster) {
    LOG.info("Round {} begin", round.incrementAndGet());
    AtomicInteger remainingResponses = new AtomicInteger(requestCount);
    for (int i = 0; i < requestCount; i++) {
      client.request(GET, DEFAULT_HTTP_PORT, DEFAULT_HTTP_HOST, String.format("test?id=%d.%d", round.get(), i))
        .compose(HttpClientRequest::send)
        .onComplete(onSuccess(resp -> {
          assertEquals(200, resp.statusCode());
          LOG.debug("Received response for {}", resp.request().getURI());
          if (remainingResponses.decrementAndGet() == 0) {
            latch.countDown();
            if (latch.getCount() > 0) {
              long delayTime = intervalMs + msAdjuster.get() + 1000 - System.currentTimeMillis() % 1000;
              vertx.setTimer(delayTime, l -> roundHandler(vertx, round, client, latch, requestCount, intervalMs, msAdjuster));
            }
          }
        }));
    }
  }

  @Test
  public void testAcquireWhenEvict() throws Exception {
    AtomicLong msAdjuster = new AtomicLong(1000);

    // a hack to get the timestamp when keep-alive timeout is checked
    Consumer<Endpoint<Lease<HttpClientConnection>>> oldChecker = HttpClientImpl.EXPIRED_CHECKER;
    HttpClientImpl.EXPIRED_CHECKER = endPoint -> {
      LOG.debug("Expired checker called");
      msAdjuster.set(System.currentTimeMillis() % 1000);
      oldChecker.accept(endPoint);
    };

    Vertx vertx = Vertx.vertx();

    final int keepAliveTimeout = 1;
    HttpClient client = vertx.createHttpClient(new HttpClientOptions()
      .setKeepAlive(true)
      .setKeepAliveTimeout(keepAliveTimeout)
      .setPipelining(false)
      .setMaxPoolSize(2)
      .setPoolCleanerPeriod(1000)
    );

    HttpServer server = vertx.createHttpServer(new HttpServerOptions()
      .setHost(DEFAULT_HTTP_HOST)
      .setPort(DEFAULT_HTTP_PORT));
    server.requestHandler(req -> {
      LOG.debug("Received request {}", req.getParam("id"));
      req.response().end();
    });

    CountDownLatch startServerLatch = new CountDownLatch(1);
    server.listen(testAddress, onSuccess(s -> startServerLatch.countDown()));
    awaitLatch(startServerLatch);
    LOG.info("Started server");

    // run 100 rounds
    AtomicInteger round = new AtomicInteger(0);
    CountDownLatch roundLatch = new CountDownLatch(100);
    vertx.runOnContext(v -> roundHandler(vertx, round, client, roundLatch, 5, keepAliveTimeout*1000, msAdjuster));

    awaitLatch(roundLatch, 10, TimeUnit.MINUTES);

    LOG.info("Closing server");
    CountDownLatch serverCloseLatch = new CountDownLatch(1);
    server.close(onSuccess(s -> serverCloseLatch.countDown()));
    awaitLatch(serverCloseLatch);

    HttpClientImpl.EXPIRED_CHECKER = oldChecker;
  }

```

I ran the test several times and mostly the issue could be reproduced in one run (100 rounds), the exception looks like this:
```
2023-06-29 06:20:38.907 [INFO ] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Round 3 begin
2023-06-29 06:20:38.913 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received request 3.0
2023-06-29 06:20:38.914 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-0] Expired checker called
2023-06-29 06:20:38.914 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received request 3.1
2023-06-29 06:20:38.915 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received response for test?id=3.0
2023-06-29 06:20:38.916 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received response for test?id=3.1
2023-06-29 06:20:38.917 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received request 3.2
2023-06-29 06:20:38.917 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received request 3.3
2023-06-29 06:20:38.918 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received response for test?id=3.2
2023-06-29 06:20:38.919 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received response for test?id=3.3
2023-06-29 06:20:38.919 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received request 3.4
2023-06-29 06:20:38.920 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received response for test?id=3.4
2023-06-29 06:20:39.915 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-0] Expired checker called
2023-06-29 06:20:40.917 [INFO ] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Round 4 begin
2023-06-29 06:20:40.917 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-0] Expired checker called
io.vertx.core.http.HttpClosedException: Connection was closed
java.lang.AssertionError: Connection was closed
	at org.junit.Assert.fail(Assert.java:89)
	at io.vertx.test.core.AsyncTestBase.fail(AsyncTestBase.java:268)
	at io.vertx.test.core.AsyncTestBase.lambda$onSuccess$2(AsyncTestBase.java:650)
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66)
	at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:86)
	at io.vertx.core.impl.ContextBase.execute(ContextBase.java:225)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:66)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
	at io.vertx.core.http.impl.HttpClientRequestBase.fail(HttpClientRequestBase.java:169)
	at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:164)
	at io.vertx.core.http.impl.HttpClientRequestImpl.handleException(HttpClientRequestImpl.java:80)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleException(Http1xClientConnection.java:714)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleClosed(Http1xClientConnection.java:720)
	at io.vertx.core.http.impl.Http1xClientConnection.lambda$handleClosed$12(Http1xClientConnection.java:1222)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:76)
	at io.vertx.core.impl.ContextBase.execute(ContextBase.java:232)
	at io.vertx.core.http.impl.Http1xClientConnection.handleClosed(Http1xClientConnection.java:1222)
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:143)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:329)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Unhandled exception 
java.lang.AssertionError: Connection was closed
	at org.junit.Assert.fail(Assert.java:89)
	at io.vertx.test.core.AsyncTestBase.fail(AsyncTestBase.java:268)
	at io.vertx.test.core.AsyncTestBase.lambda$onSuccess$2(AsyncTestBase.java:650)
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66)
	at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:86)
	at io.vertx.core.impl.ContextBase.execute(ContextBase.java:225)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:66)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
	at io.vertx.core.http.impl.HttpClientRequestBase.fail(HttpClientRequestBase.java:169)
	at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:164)
	at io.vertx.core.http.impl.HttpClientRequestImpl.handleException(HttpClientRequestImpl.java:80)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleException(Http1xClientConnection.java:714)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleClosed(Http1xClientConnection.java:720)
	at io.vertx.core.http.impl.Http1xClientConnection.lambda$handleClosed$12(Http1xClientConnection.java:1222)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:76)
	at io.vertx.core.impl.ContextBase.execute(ContextBase.java:232)
	at io.vertx.core.http.impl.Http1xClientConnection.handleClosed(Http1xClientConnection.java:1222)
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:143)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:329)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

2023-06-29 06:20:40.934 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received request 4.2
2023-06-29 06:20:40.935 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received request 4.1
2023-06-29 06:20:40.936 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received response for test?id=4.2
2023-06-29 06:20:40.937 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received response for test?id=4.1
2023-06-29 06:20:40.938 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received request 4.3
2023-06-29 06:20:40.938 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received request 4.4
2023-06-29 06:20:40.939 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received response for test?id=4.3
2023-06-29 06:20:40.940 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-1] Received response for test?id=4.4
2023-06-29 06:20:41.925 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-0] Expired checker called
2023-06-29 06:20:42.926 [DEBUG] [vertx.core.http.Http1xTest|vert.x-eventloop-thread-0] Expired checker called
```

**Comment by vietj** [comment]
I think we could improve the implementation of evict by directly removing the connection without using an action that would avoid such races

**Comment by vietj** [comment]
I will come with a patch soon for testing

**Comment by vietj** [comment]
do you mind trying https://github.com/eclipse-vertx/vert.x/pull/4784 ?

**Comment by bh-tt** [comment]
I'll see what I can do monday.

**Comment by bh-tt** [comment]
Sigh I keep forgetting to switch between my work and personal account, I'm also Borrelhapje.

**Comment by bh-tt** [comment]
I've found a better workaround: Set `Connection: close` header on the request. Might result in slightly more resource usage but I'm guessing the connection close is received by the client and the connection is removed from the pool, early enough to prevent this timing issue from occuring?

**Comment by vietj** [comment]
@bh-tt can you provide a reproducer ?

**Comment by vietj** [comment]
I tried @ben1222 reproducer (btw thanks for it and the analysis) and the PR fixes this particular issue in the pool after running it multiple times. The PR eliminates the time window in which a connection was evicted and removed allowing the connection to be borrowed before it was removed.

@bh-tt I believe you are observing another manifestation of the same issue that might not happen in the pool (anymore unless there is another unknown bug of course). If you can provide a reproducer that would be great.

**Comment by bh-tt** [comment]
I haven't been able to reproduce it outside of our own setup (involving large servers, lots of load, reverse proxies and the like).  For now the Connection close workaround is fine, I'll open a new issue if I manage to make a reproducer. Feel free to close this.
