### ISSUE TITLE
Request has already been read using vertx 4.4.0

### ISSUE THREAD

**Issue by chaitas90** [eclipse-vertx/vert.x#4786]
Using vertx 4.4.0

I have been getting this error frequently and it is hampering my application 

java.lang.IllegalStateException: Request has already been read
        at io.vertx.core.http.impl.Http2ServerRequest.checkEnded(Http2ServerRequest.java:259)
        at io.vertx.core.http.impl.Http2ServerRequest.handler(Http2ServerRequest.java:298)
        at io.vertx.core.http.impl.HttpServerRequestWrapper.handler(HttpServerRequestWrapper.java:62)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:132)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:46)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at io.vertx.ext.web.handler.impl.JWTAuthHandlerImpl.postAuthentication(JWTAuthHandlerImpl.java:153)
        at io.vertx.ext.web.handler.impl.AuthenticationHandlerImpl.lambda$handle$0(AuthenticationHandlerImpl.java:98)
        at io.vertx.ext.web.handler.impl.JWTAuthHandlerImpl.lambda$null$0(JWTAuthHandlerImpl.java:87)
        at io.vertx.core.impl.future.SucceededFuture.onComplete(SucceededFuture.java:81)
        at io.vertx.ext.auth.authentication.AuthenticationProvider.authenticate(AuthenticationProvider.java:110)
        at io.vertx.ext.web.handler.impl.JWTAuthHandlerImpl.lambda$authenticate$1(JWTAuthHandlerImpl.java:83)
        at io.vertx.ext.web.handler.impl.HTTPAuthorizationHandler.parseAuthorization(HTTPAuthorizationHandler.java:110)
        at io.vertx.ext.web.handler.impl.HTTPAuthorizationHandler.parseAuthorization(HTTPAuthorizationHandler.java:79)
        at io.vertx.ext.web.handler.impl.JWTAuthHandlerImpl.authenticate(JWTAuthHandlerImpl.java:58)
        at io.vertx.ext.web.handler.impl.AuthenticationHandlerImpl.handle(AuthenticationHandlerImpl.java:84)
        at io.vertx.ext.web.handler.impl.AuthenticationHandlerImpl.handle(AuthenticationHandlerImpl.java:31)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:250)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284
        
I have been deploying 2 instance of following verticle::

```
public class APIServer extends AbstractVerticle
{

    private static final Logger LOGGER = new Logger(APIServer.class, GlobalConstants.MOTADATA_API,"API Server");

    private JWTAuth jwtAuth;

    private JWT jwt;
    
    @Override
    public void start(Promise<Void> promise) throws Exception
    {
        var server = vertx.createHttpServer(new HttpServerOptions()
                .setUseAlpn(true) //http2
                .setSsl(CommonUtil.httpsEnabled())
                .setCompressionSupported(true)
                .setPemKeyCertOptions(new PemKeyCertOptions()
                        .setCertPath(GlobalConstants.CURRENT_DIR + GlobalConstants.PATH_SEPARATOR + "server-cert.pem")
                        .setKeyPath(GlobalConstants.CURRENT_DIR + GlobalConstants.PATH_SEPARATOR + "server-key.pem")));

        var router = Router.router(vertx);

        if(CommonUtil.enableHTTPLogging())
        {
            router.route().handler(new RequestLogger()); //log API request

        }

        var bodyHandler = BodyHandler.create().setUploadsDirectory(GlobalConstants.CURRENT_DIR + GlobalConstants.PATH_SEPARATOR + GlobalConstants.UPLOADS).setBodyLimit(MAX_BODY_LIMIT_BYTES);

        router.route().handler(StaticHandler.create("dist/index.html"));

        var apiRouter = Router.router(vertx);
        
        jwtAuth = JWTAuth.create(vertx, new JWTAuthOptions()); // To sign Access token

        apiRouter.route().handler(JWTAuthHandler.create(jwtAuth));
        
        var settingsAPIRouter = Router.router(vertx);

        var auditAPIRouter = Router.router(vertx);
        
        var miscRouter = Router.router(vertx);

        var visualizationRouter = Router.router(vertx);

        apiRouter.route("/settings/*").handler(bodyHandler).handler(this::authenticate).subRouter(settingsAPIRouter);

        apiRouter.route("/audit/*").handler(bodyHandler).handler(this::authenticate).subRouter(auditAPIRouter);

        APIRouter.init(settingsAPIRouter, miscRouter,visualizationRouter);

        var userRouter = Router.router(vertx);

        apiRouter.route("/user/*").handler(bodyHandler).handler(this::authenticate).subRouter(userRouter);

        router.route("/api/v1/*").handler(this::statusHandler).subRouter(apiRouter);

        router.route("/samples/*").method(HttpMethod.GET).handler(this::staticResourceHandler);

        router.route("/*").method(HttpMethod.GET).handler(StaticHandler.create(FileSystemAccess.ROOT, CURRENT_DIR + "/dist"));

        router.route("/*").method(HttpMethod.GET).handler(event -> event.response().putHeader(HttpHeaders.CONTENT_TYPE, CONTENT_TYPE_TEXT_HTML)
                .sendFile(CURRENT_DIR + "/dist/index.html"));

        router.errorHandler(SC_PRECONDITION_FAILED, routingContext ->
        {
            if(routingContext.failure() != null)
            {
                routingContext.response().putHeader(CONTENT_TYPE, CONTENT_TYPE_APPLICATION_JSON).setStatusCode(SC_PRECONDITION_FAILED)
                        .end(new JsonObject().put(STATUS, STATUS_FAIL).put(RESPONSE_CODE, SC_PRECONDITION_FAILED).put(MESSAGE, routingContext.failure().getMessage()).encodePrettily());
            }
        });

        router.errorHandler(SC_INTERNAL_SERVER_ERROR, routingContext ->
        {

            if(routingContext.failure() != null)
            {
                LOGGER.error(routingContext.failure());

                routingContext.response().putHeader(CONTENT_TYPE, CONTENT_TYPE_APPLICATION_JSON).setStatusCode(SC_INTERNAL_SERVER_ERROR)
                        .end(new JsonObject().put(STATUS, STATUS_FAIL).put(RESPONSE_CODE, SC_INTERNAL_SERVER_ERROR).put(MESSAGE, routingContext.failure()).encodePrettily());
            }
        });

        server.requestHandler(router)
                .exceptionHandler(LOGGER::error)
                .listen(CommonUtil.getHTTPServerPort(), result ->
                {
                    if(result.succeeded())
                    {
                        promise.complete();
                    }
                    else
                    {
                        promise.fail(result.cause());
                    }
                });
    }

    //as of now we are going to disable api access from outside... // only Motadata UI can access API ... no one else can access it...
    private void authenticate(RoutingContext routingContext)
    {
        try
        {
            var cookie = routingContext.request().getCookie(CLIENT_ID);

            if(cookie !=null && cookie.getValue().equalsIgnoreCase(UI_CLIENT_ID))
            {
                if (routingContext.user() != null)
                {
                    var request = routingContext.request();

                    if (request.path() != null)
                    {
                        var paths = request.path().replace(routingContext.mountPoint(), EMPTY_VALUE).split("/");

                        var endpoint = paths.length > 1 ? paths[1].trim() : paths[0].trim();

                        var authorizations =  routingContext.user().authorizations();

                        var valid = false;

                        if(authorizations != null && authorizations.get("jwt-authentication") != null)
                        {
                            var visualizationModule = VISUALIZATION_MODULES.containsKey(paths[0].trim());

                            var path = visualizationModule ? getPermission(paths[0].trim(),request,routingContext.body().asJsonObject())
                                    : getPermission(endpoint,request,routingContext.body().asJsonObject());

                            for(var authorization : authorizations.get("jwt-authentication"))
                            {
                                if(((PermissionBasedAuthorizationImpl) authorization).getPermission().matches(path) || visualizationModule)
                                {
                                    valid = true;

                                    break;
                                }
                            }
                        }

                        if(valid)
                        {
                            routingContext.next();
                        }
                        else
                        {
                            routingContext.response().putHeader(HttpHeaders.CONTENT_TYPE, CONTENT_TYPE_APPLICATION_JSON)
                                    .setStatusCode(SC_FORBIDDEN).end(new JsonObject().put(ERROR_CODE, ErrorCodes.ERROR_CODE_BAD_REQUEST).put(MESSAGE,String.format(API_ACCESS_FAILED_NOT_AUTHORIZED, getModuleAndRolePermission(endpoint,request,routingContext.body().asJsonObject()))).encodePrettily());
                        }
                    }
                    else
                    {
                        routingContext.next();
                    }
                }
                else
                {
                    routingContext.next();
                }
            }
            else
            {
                routingContext.response().putHeader(HttpHeaders.CONTENT_TYPE, CONTENT_TYPE_APPLICATION_JSON)
                        .setStatusCode(SC_FORBIDDEN).end(new JsonObject().put(ERROR_CODE, ErrorCodes.ERROR_CODE_BAD_REQUEST).put(MESSAGE,API_ACCESS_FAILED_NOT_AUTHORIZED).encodePrettily());

                LOGGER.warn(API_ACCESS_FAILED_NOT_AUTHORIZED);
            }
        }
        catch (Exception exception)
        {
            APIUtil.sendResponse(exception, routingContext);
        }

    }

    private void staticResourceHandler(RoutingContext routingContext)
    {
        var route = routingContext.normalizedPath();

        var filePath = route.substring(route.indexOf("samples"));

        try(var inputStream = Thread.currentThread().getContextClassLoader().getResourceAsStream(filePath))
        {
            if(inputStream != null)
            {
                var fileName = filePath.substring(filePath.lastIndexOf('/') + 1);

                var content = IOUtils.toString(Objects.requireNonNull(inputStream), StandardCharsets.UTF_8);

                routingContext.response().putHeader(CONTENT_DISPOSITION, "attachment; filename=\"" + fileName + '"')
                        .putHeader(CONTENT_LENGTH, CommonUtil.getString(content.length())).setStatusCode(SC_OK).end(content);
            }

            else
            {
                routingContext.response().putHeader(CONTENT_TYPE, CONTENT_TYPE_APPLICATION_JSON).setStatusCode(SC_BAD_REQUEST)
                        .end(new JsonObject().put(STATUS, STATUS_FAIL).put(RESPONSE_CODE, SC_BAD_REQUEST).put(MESSAGE, String.format(FILE_NOT_FOUND, filePath)).encodePrettily());
            }

        }
        catch (Exception exception)
        {
            LOGGER.error(exception);

            routingContext.response().putHeader(CONTENT_TYPE, CONTENT_TYPE_APPLICATION_JSON).setStatusCode(SC_INTERNAL_SERVER_ERROR)
                    .end(new JsonObject().put(STATUS, STATUS_FAIL).put(RESPONSE_CODE, SC_INTERNAL_SERVER_ERROR).put(MESSAGE, exception.getMessage()).encodePrettily());
        }
    }

    private String getPermission(String endPoint, HttpServerRequest request, JsonObject params)
    {
        //for schedulers specific check
         if (endPoint.equalsIgnoreCase("schedulers"))
        {
            endPoint = switch (JobScheduler.JobType.valueOfName(request.getParam(FILTER) != null ? JsonObject.mapFrom(Json.decodeValue(request.getParam(FILTER))).getString(Scheduler.SCHEDULER_JOB_TYPE) : request.getParam(Scheduler.SCHEDULER_JOB_TYPE) != null ? request.getParam(Scheduler.SCHEDULER_JOB_TYPE) : params.getString(Scheduler.SCHEDULER_JOB_TYPE)))
                    {
                        case DISCOVERY -> "discoveries";
                        case MAINTENANCE, REDISCOVER, TOPOLOGY ->  NMSConstants.OBJECTS;
                        case RUNBOOK ->  "runbook-plugins";
                        case REPORT -> "reports";
                        default -> "schedulers";
                    };
        }

        return ENDPOINTS_BY_MODULE.get(endPoint) + ":" + APIConstants.RequestType.valueOf(VISUALIZATION_MODULES.containsKey(endPoint) ? REQUEST_GET.toUpperCase() : request.method().name()).getName();
    }

    // #3420 improvement - Module name and role permission will append with error message ( "Client is not allowed to access API")
    private String getModuleAndRolePermission(String endPoint, HttpServerRequest request,JsonObject params)
    {
        //for schedulers specific check
        if (endPoint.equalsIgnoreCase("schedulers"))
        {
            endPoint = switch (JobScheduler.JobType.valueOfName(request.getParam(FILTER) != null ? JsonObject.mapFrom(Json.decodeValue(request.getParam(FILTER))).getString(Scheduler.SCHEDULER_JOB_TYPE) : request.getParam(Scheduler.SCHEDULER_JOB_TYPE) != null ? request.getParam(Scheduler.SCHEDULER_JOB_TYPE) : params.getString(Scheduler.SCHEDULER_JOB_TYPE)))
                    {
                        case DISCOVERY -> "discoveries";
                        case MAINTENANCE, REDISCOVER, TOPOLOGY ->  NMSConstants.OBJECTS;
                        case RUNBOOK ->  "runbook-plugins";
                        case REPORT -> "reports";
                        default -> "schedulers";
                    };
        }

        return StringUtils.capitalize(ENDPOINTS_BY_MODULE.getOrDefault(endPoint, EMPTY_VALUE).replace("-"," "))+" "+StringUtils.capitalize(APIConstants.RequestType.valueOf(VISUALIZATION_MODULES.containsKey(endPoint) ? REQUEST_GET.toUpperCase() : request.method().name()).getName());
    }

    /**
     * proxy handler to check server Status
     * in case of unhealthy server status, redirect to error page instead of serving application.
     *
     * @param routingContext
     */
    private void statusHandler(RoutingContext routingContext)
    {
        if (Bootstrap.APP_SERVER_ONLINE.get())
        {
            routingContext.next();
        }
        else
        {
            routingContext.fail(SC_PRECONDITION_FAILED, new Exception(ErrorMessageConstants.INSUFFICIENT_DISK_SPACE_ERROR));
        }
    }

}
```

Please let me know what can be done and how can i mitigate the issue..

**Comment by vietj** [comment]
you should pause / resume the request when you have an asynchronous operation and the request has not been read entirely.
