### ISSUE TITLE
Failed in deploying verticle

### ISSUE THREAD

**Issue by Manuv79** [eclipse-vertx/vert.x#4813]
### Questions

Failed in deploying verticle 
[ERROR] [i.v.c.i.l.c.VertxIsolatedDeployer]: Failed in deploying verticle
java.lang.ExceptionInInitializerError

### Version

studio-web-ui-0.3.1 - file : studio-macos.sh

### Context

I tried to open the file studio-macos.sh in terminal to install it, but i have an error : 

2023-08-20 08:07:38,355 [ERROR] [i.v.c.i.l.c.VertxIsolatedDeployer]: Failed in deploying verticle
java.lang.ExceptionInInitializerError
	at studio.driver.LibUsbDetectionHelper.initializeLibUsb(LibUsbDetectionHelper.java:50)
	at studio.driver.raw.RawStoryTellerAsyncDriver.<init>(RawStoryTellerAsyncDriver.java:45)
	at studio.webui.service.StoryTellerService.<init>(StoryTellerService.java:54)
	at studio.webui.MainVerticle.start(MainVerticle.java:60)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: org.usb4java.LoaderException: Native library not found in classpath: /org/usb4java/darwin-aarch64/libusb4java.dylib
	at org.usb4java.Loader.extractLibrary(Loader.java:246)
	at org.usb4java.Loader.load(Loader.java:323)
	at org.usb4java.LibUsb.<clinit>(LibUsb.java:690)
	... 16 more

I'm on a mac book Pro M1 2020 - Ventura 13.3.1

Thanks for your help

**Comment by He-Pin** [comment]
This should be a bug in your library.

**Comment by tsegismont** [comment]
@Manuv79 the problem is explained at the bottom of the stacktrace:

`Caused by: org.usb4java.LoaderException: Native library not found in classpath: /org/usb4java/darwin-aarch64/libusb4java.dylib`

I'm not familiar with usb4java, I would recommend to check their documentation
