### ISSUE TITLE
EventBus in arm64 Architecture Docker Container  UnknownHostException

### ISSUE THREAD

**Issue by shihb** [eclipse-vertx/vert.x#4822]
### Questions

I'm encountering an UnknownHostException related to EventBus inside a Docker container on the arm64 architecture.  How can I address this issue?

### Version

vertx 4.4.0
The Vert.x version is 4.4.0, and the Docker image version is openjdk:17-bullseye.

### Context

on my local machine with an x86_64 environment, but issues arise within the container on an aarch64 architecture. I'm feeling puzzled about whether there's support for aarch64. Could someone knowledgeable guide me?

 
```java
 2023-08-25 22:08:42.981 [vert.x-eventloop-thread-1] ERROR c.qiliapp.crdt.sys.openapi.org.impl.UserApiService - 堆栈信息 
io.vertx.serviceproxy.ServiceException: UnknownHostException: 13d460e6a00d45a6917b1b2198d01e6a
        at io.vertx.serviceproxy.HelperUtils.manageFailure(HelperUtils.java:125)
        at io.vertx.serviceproxy.HelperUtils.lambda$createHandler$0(HelperUtils.java:35)
        at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
        at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:191)
        at io.vertx.core.impl.future.PromiseImpl.addListener(PromiseImpl.java:23)
        at io.vertx.core.impl.future.FutureImpl.onComplete(FutureImpl.java:164)
        at io.vertx.core.impl.future.PromiseImpl.onComplete(PromiseImpl.java:23)
        at com.qiliapp.crdt.sys.proxy.org.UserServiceVertxProxyHandler.handle(UserServiceVertxProxyHandler.java:193)
        at com.qiliapp.crdt.sys.proxy.org.UserServiceVertxProxyHandler.handle(UserServiceVertxProxyHandler.java:53)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:177)
        at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.execute(HandlerRegistration.java:137)
        at io.vertx.core.eventbus.impl.DeliveryContextBase.next(DeliveryContextBase.java:72)
        at io.vertx.core.eventbus.impl.DeliveryContextBase.dispatch(DeliveryContextBase.java:43)
        at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:98)
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:183)
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:168)
        at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:49)
        at io.vertx.core.impl.WorkerContext.lambda$null$1(WorkerContext.java:92)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by tsegismont** [comment]
Yes, Vert.x can run on aarch64

The stacktrace indicates that the message consumer received a failure (unknown host). Perhaps as a reply to a service deployed on the eventbus? Then what does this remote service do and why does it fail?

Without more details (ideally a small reproducer!) we can only guess.

**Comment by shihb** [comment]
Thank you for your response, tsegismont. Indeed, it's difficult to make a precise judgment from the relatively coarse exception stack
```java
     //UserServiceVertxProxyHandler Line 193 question
        case "doLogin": {
          service.doLogin((io.vertx.core.json.JsonObject)json.getValue("params"),
                        (java.lang.String)json.getValue("loginIp"),
                        (io.vertx.core.json.JsonObject)json.getValue("config")).onComplete(HelperUtils.createHandler(msg, includeDebugInfo));
          break;
        }
```
conducting tests, I discovered that the issue lies within my code. Vertx runs well on aarch64 architecture. However, I desired a more user-friendly exception handling. Hence, I made modifications to the code generated through @ProxyGen, specifically in the UserServiceVertxProxyHandler.
```java
case "doLogin": {
          service.doLogin((io.vertx.core.json.JsonObject)json.getValue("params"),
                        (java.lang.String)json.getValue("loginIp"),
                        (io.vertx.core.json.JsonObject)json.getValue("config")).onComplete(res -> {
                          if (res.failed()) {
                           //Output stack trace in case of failure.
                            res.cause().printStackTrace();
                            HelperUtils.manageFailure(msg, res.cause(), includeDebugInfo);
                          } else {
                              msg.reply(res.result());
                          }
                        });
          break;
        }
```
Following the mentioned modifications, I am now outputting detailed stack
```java
UnknownHostException: 13d460e6a00d45a6917b1b2198d01e6a
cn.hutool.core.io.IORuntimeException: UnknownHostException: 13d460e6a00d45a6917b1b2198d01e6a
        at cn.hutool.http.HttpRequest.send(HttpRequest.java:1163)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:968)
        at cn.hutool.http.HttpRequest.execute(HttpRequest.java:939)
        at com.qiliapp.crdt.sys.proxy.org.impl.UserServiceImpl.getUserByAccount(UserServiceImpl.java:94)
        at com.qiliapp.crdt.sys.proxy.org.impl.UserServiceImpl.validateAccount(UserServiceImpl.java:626)
        at com.qiliapp.crdt.sys.proxy.org.impl.UserServiceImpl.doLogin(UserServiceImpl.java:511)
        at com.qiliapp.crdt.sys.proxy.org.UserServiceVertxProxyHandler.handle(UserServiceVertxProxyHandler.java:191)
        at com.qiliapp.crdt.sys.proxy.org.UserServiceVertxProxyHandler.handle(UserServiceVertxProxyHandler.java:53)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:177)
        at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.execute(HandlerRegistration.java:137)
        at io.vertx.core.eventbus.impl.DeliveryContextBase.next(DeliveryContextBase.java:72)
        at io.vertx.core.eventbus.impl.DeliveryContextBase.dispatch(DeliveryContextBase.java:43)
        at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:98)
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:183)
        at io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:168)
        at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:49)
        at io.vertx.core.impl.WorkerContext.lambda$null$1(WorkerContext.java:92)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.UnknownHostException: 13d460e6a00d45a6917b1b2198d01e6a
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:246)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:351)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:373)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
        at cn.hutool.http.HttpConnection.connect(HttpConnection.java:377)
        at cn.hutool.http.HttpRequest.send(HttpRequest.java:1158)
        ... 22 more
```
I am now outputting detailed stack realized that a lack of configuration led to an incomplete URL address.  The correct address is http://39.97.193.116:8010/content/attachment/13d460e6a00d45a6917b1b2198d01e6a.
This was my own issue.  Vertx performs well on aarch64 architecture.  It would be beneficial for newcomers learning Vertx to have improved exception handling.  I hope that HelperUtils can provide more detailed stack trace outputs for exceptions.
