### ISSUE TITLE
httpclient unhandled exception

### ISSUE THREAD

**Issue by gillbates** [eclipse-vertx/vert.x#4823]
### Questions

Sometimes httpclient will throw an exception uncaught ... 

### Version

4.4.4

### Context

we have a vertx crawler which will submit 10000/s requests to our vertx server.
And it will throws following exception sometimes, any ideas why?

```
[08-28 00:44:31.757][vert.x-eventloop-thread-1][ERROR][i.v.c.i.ContextBase][] - [Unhandled exception]
java.lang.StackOverflowError: null
	at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FailedFuture.addListener(FailedFuture.java:98) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Composition.onFailure(Composition.java:55) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Mapping.onFailure(Mapping.java:45) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FailedFuture.addListener(FailedFuture.java:98) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Composition.onFailure(Composition.java:55) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Mapping.onFailure(Mapping.java:45) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
```

### Do you have a reproducer?

my code
```
  private static Future<String> post(long traceId, WebClient webClient, String url, Map<String, String> headers, String body) {
        Promise<String> promise = Promise.promise();
        HttpRequest<Buffer> abs = webClient.postAbs(url);
        headers.forEach(abs::putHeader);
        Future<HttpResponse<Buffer>> send;
        send = abs.sendBuffer(Buffer.buffer(body));
        return send.map(response -> {
            log.debug("[{}] posted url {} response code[{}][{}]", traceId, url, response.statusCode(), response.bodyAsString("UTF-8"));
            return response.bodyAsString("UTF-8");
        }).onFailure(throwable -> {
            log.error("[{}] post url {} error:[{}]", traceId, url, Throwables.getStackTraceAsString(throwable));
            promise.fail(throwable);
        }).onSuccess(promise::complete);
    }
```

so it will first print

```
[08-28 00:44:31.738][vert.x-eventloop-thread-1][ERROR][c.r.w.h.ApiHelper][188] - [[1693057815644] post url http://192.168.1.2:8889/api/xxx error:[io.vertx.core.http.HttpClosedException: Connection was closed
]]
```
and then 

```
[08-28 00:44:31.757][vert.x-eventloop-thread-1][ERROR][i.v.c.i.ContextBase][] - [Unhandled exception]
java.lang.StackOverflowError: null
	at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FailedFuture.addListener(FailedFuture.java:98) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Composition.onFailure(Composition.java:55) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Mapping.onFailure(Mapping.java:45) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FailedFuture.addListener(FailedFuture.java:98) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Composition.onFailure(Composition.java:55) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Mapping.onFailure(Mapping.java:45) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FailedFuture.addListener(FailedFuture.java:98) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Composition.onFailure(Composition.java:55) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Mapping.onFailure(Mapping.java:45) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66) ~[vertx-core-4.4.4.jar:4.4.4]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.4.4.jar:4.4.4]
```

### Extra

* Anything that can be relevant such as OS version, JVM version
it happens everyday on jdk21 and ubuntu ..., please help :)

**Comment by vietj** [comment]
can you provide a reproducer project ?

**Comment by tsegismont** [comment]
I've spent some time looking into this and trying to reproduce without success.

What's the role of the `promise` in your method? it doesn't seem to be used, really. Perhaps you've removed some part of the method implementation?

**Comment by gillbates** [comment]
>

nothing removed ..
 
```
onSuccess(promise::complete);
```

this line will wrap the resp body and returned in the promise to the caller of this function ...

**Comment by gillbates** [comment]
```
@Log4j2
public class Reproducer {

    public static int PORT = 7777;
    private static int MAX_CONCURRENT = 100;

    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();

        int tasksCount = 10000;
        List<Integer> tasks = new ArrayList<>();
        for (int i = 0; i < tasksCount; i++) {
            tasks.add(i);
        }
        Future.succeededFuture().compose(v -> startWebServer(vertx, PORT)).compose(v -> {
            Future<Void> future = Future.succeededFuture();
            future = future.compose(vv -> {
                DeploymentOptions options = new DeploymentOptions();
                options.setWorker(true);
                options.setInstances(MAX_CONCURRENT);
                options.setWorkerPoolName("worker");
                options.setWorkerPoolSize(MAX_CONCURRENT);
                return vertx.deployVerticle(DummyWorker.class, options);
            }).map(vv -> null);
            return future;
        }).compose(v -> {
            List<Future<Void>> future = new ArrayList<>();

            for (int i = 0; i < tasks.size(); i++) {
                int finalI = i;
                int task = tasks.get(finalI);
                DeliveryOptions deliveryOptions = new DeliveryOptions();
                Future<Void> futureX = vertx.eventBus().request(DummyWorker.ADDR, String.valueOf(task), deliveryOptions).map(res -> {
                    log.debug("res: {}", res.body());
                    return null;
                });
                future.add(futureX);
            }
            return Future.join(future).map(res -> null);
        }).onComplete(res -> {
            if (res.succeeded()) {
                log.debug("{} workers finished {} tasks ", MAX_CONCURRENT, tasks.size());
            } else {
                log.error(res.cause());
            }
        });
    }

    private static Future<Void> startWebServer(Vertx vertx, int port) {
        Promise<Void> promise = Promise.promise();
        HttpServer server = vertx.createHttpServer();
        Set<String> received = new HashSet<>();

        server.requestHandler(request -> {
            String id = request.getParam("id");
            if (received.contains(id)) {
                log.error("Error: id {} already received", id);
            } else {
                received.add(id);
            }
            // This handler gets called for each request that arrives on the server
            HttpServerResponse response = request.response();
            response.putHeader("content-type", "text/plain");

            // Write to the response and end it
            response.end("hallo world, id:" + id);
        });

        server.listen(port, r -> {
            if (r.succeeded()) {
                log.debug("server started on port {}", port);
                promise.complete();
            } else {
                promise.fail(r.cause());
            }
        });

        return promise.future();
    }


}
```


```
@Log4j2
public class DummyWorker extends AbstractVerticle {
    public static String ADDR = "/test";
    private WebClient httpClient;

    private static Future<String> post(long traceId, WebClient webClient, String url) {
        Promise<String> promise = Promise.promise();
        HttpRequest<Buffer> abs = webClient.postAbs(url);
        Future<HttpResponse<Buffer>> send;
        send = abs.send();
        return send.map(response -> {
            log.debug("[{}] posted url {} response code[{}][{}]", traceId, url, response.statusCode(), response.bodyAsString("UTF-8"));
            return response.bodyAsString("UTF-8");
        }).onFailure(throwable -> {
            log.error("[{}] post url {} error:[{}]", traceId, url, Throwables.getStackTraceAsString(throwable));
            promise.fail(throwable);
        }).onSuccess(promise::complete);
    }

    public void start() {
        httpClient = WebClient.create(vertx);
        vertx.eventBus().consumer(ADDR, this::onMessage).completionHandler(res -> {
            if (res.succeeded()) {
                log.debug("DummyWorker address: [{}] registration has reached all nodes ...", ADDR);
            } else {
                log.error("Failed to register DummyWorker at address: [{}] with error: [{}]", ADDR, res.cause());
            }
        });
    }

    private void onMessage(Message<String> message) {
        Future.succeededFuture().map(v -> {
            log.debug("[{}] Received message: [{}]", ADDR, message.body());
            return message.body();
        }).compose(id -> {
            String url = "http://localhost:" + Reproducer.PORT + "/test?id=" + id;
            return post(System.currentTimeMillis(), httpClient, url);
        }).map(resp -> {
            log.debug("resp: {}", resp);
            return null;
        }).onComplete(ar -> {
            if (ar.succeeded()) {
                message.reply("OK");
            } else {
                log.error("Failed to process message: [{}] with error: [{}]", message.body(), Throwables.getStackTraceAsString(ar.cause()));
                message.reply("OK");
            }
        });
    }
}

```

ok, it will now throws following on my macbook m1 pro using oracle jdk 20
```
[08-28 18:45:05.894][worker-14][ERROR][c.r.p.t.DummyWorker][58] - [Failed to process message: [415] with error: [io.netty.channel.AbstractChannel$AnnotatedSocketException: Connection reset by peer: localhost/127.0.0.1:7777
Caused by: java.net.SocketException: Connection reset by peer
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:673)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
]]
```

**Comment by gillbates** [comment]
> That means the remote peer closed the exception

Currently we are using similar code as provided above to implement our api server. i.e. our api server/client are both implemented in vertx.

And it will throw exceptions when there is high load of requests.
So what parameters should I set there in vertx to fix this??

**Comment by tsegismont** [comment]
I don't know. There can be many reasons: problem on the server, problem on a proxy in between. To get more info you could:

- use network logging
- capture traffic and analyze it with Wireshark
- check server logs

Anyway so far I can't reproduce a problem with these snippets

**Comment by gillbates** [comment]
> I don't know. There can be many reasons: problem on the server, problem on a proxy in between. To get more info you could:
> 
> * use network logging
> * capture traffic and analyze it with Wireshark
> * check server logs
> 
> Anyway so far I can't reproduce a problem with these snippets

https://github.com/eclipse-vertx/vert.x/issues/4823#issuecomment-1695473857

with this code above, you could reproduce the issue ... @tsegismont

**Comment by tsegismont** [comment]
I did try these snippets and wasn't able to reproduce
