### ISSUE TITLE
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Type io.vertx.codegen.format.LowerCamelCase not present (through reference chain: java.util.LinkedList[0])

### ISSUE THREAD

**Issue by Areeb-Gillani** [eclipse-vertx/vert.x#4871]
### Questions

I am using Vertx CodeGen Annotations on my Model class and when I try to convert it using Json.encode() is says that the LowerCamelCase format is not present in jackson. I have tried SnakeCase as well but it is stuck on the same error. I tried ObjectMapper as well but it's giving the same error for obvious reasons

### Version

Vertx (4.4.5) for every lib related to vertx

### Code?
This is where the response body is failing
```java
        eventBus.request(EventTopics.READ_MESSAGES, body, (reply) -> {
            if (reply.succeeded()) {
                try {
                    this.getRequestContext().json(new ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(reply.result().body()));


          //this.getRequestContext().json(reply.result().body());;
                } catch (JsonProcessingException e) {
                    throw new RuntimeException(e);
                }
            } else {
                context.getRequestContext().json(reply.cause());
            }
        });
```
### Database Call
```java
CompletableFuture<List<Test>> messages = myRepo.read("select * from Test", TestRowMapper.INSTANCE, null);
        try {
            message.reply(messages.get());
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        } catch (ExecutionException e) {
            throw new RuntimeException(e);
        }
```
### DB Model
```java
@DataObject//I have used (generateConverter = true) but this doesn't have any easy way for Collection of this class i.e list or map etc
@RowMapped
@ParametersMapped
public class Test implements Serializable{
    @Column(name = "message")
    String message;
    @Column(name = "entry_time")
    String entryTime;
    @Column(name = "id")
    String id;
    @Column(name = "entry_by")
    String entryBy;

    public Test() {
    }
    public Test(JsonObject obj) {
    }

    public Test(String message, String entryTime, String id, String entryBy) {
        this.message = message;
        this.entryTime = entryTime;
        this.id = id;
        this.entryBy = entryBy;
    }
...
}
```
### Logs
```java
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Type io.vertx.codegen.format.LowerCamelCase not present (through reference chain: java.util.LinkedList[0])
	at com.example.controllers.ExampleController.lambda$readAllMessages$0(ExampleController.java:50)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:86)
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:184)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:51)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.Promise.complete(Promise.java:66)
	at io.vertx.core.eventbus.impl.ReplyHandler.dispatch(ReplyHandler.java:97)
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.execute(HandlerRegistration.java:137)
	at io.vertx.core.eventbus.impl.DeliveryContextBase.next(DeliveryContextBase.java:80)
	at io.vertx.core.eventbus.impl.DeliveryContextBase.dispatch(DeliveryContextBase.java:43)
	at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:98)
	at io.vertx.core.eventbus.impl.ReplyHandler.doReceive(ReplyHandler.java:81)
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:49)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Type io.vertx.codegen.format.LowerCamelCase not present (through reference chain: java.util.LinkedList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:373)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:345)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:153)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1572)
	at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1273)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1140)
	at com.example.controllers.ExampleController.lambda$readAllMessages$0(ExampleController.java:48)
	... 23 more
Caused by: java.lang.TypeNotPresentException: Type io.vertx.codegen.format.LowerCamelCase not present
	at java.base/java.lang.reflect.Method.getDefaultValue(Method.java:724)
	at java.base/sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:133)
	at java.base/sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:262)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
	at java.base/java.lang.Class.createAnnotationData(Class.java:4068)
	at java.base/java.lang.Class.annotationData(Class.java:4057)
	at java.base/java.lang.Class.getDeclaredAnnotations(Class.java:4024)
	at com.fasterxml.jackson.databind.util.ClassUtil.findClassAnnotations(ClassUtil.java:1273)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClassResolver.resolveClassAnnotations(AnnotatedClassResolver.java:247)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClassResolver.resolveFully(AnnotatedClassResolver.java:145)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClassResolver.resolve(AnnotatedClassResolver.java:89)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector._resolveAnnotatedClass(BasicClassIntrospector.java:317)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.collectProperties(BasicClassIntrospector.java:183)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forSerialization(BasicClassIntrospector.java:86)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forSerialization(BasicClassIntrospector.java:11)
	at com.fasterxml.jackson.databind.SerializationConfig.introspect(SerializationConfig.java:906)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:144)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1503)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1451)
	at com.fasterxml.jackson.databind.SerializerProvider.findContentValueSerializer(SerializerProvider.java:789)
	at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddSecondarySerializer(PropertySerializerMap.java:90)
	at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase._findAndAddDynamic(AsArraySerializerBase.java:314)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:140)
	... 31 more
Caused by: java.lang.ClassNotFoundException: io.vertx.codegen.format.LowerCamelCase
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:441)
	at java.base/sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:427)
	at java.base/sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:346)
	at java.base/java.lang.reflect.Method.getDefaultValue(Method.java:717)
	... 55 more

```

* I am using jdk17

**Comment by Areeb-Gillani** [comment]
It was not a bug. Hence closing.
