### ISSUE TITLE
Blocked thread during vertx startup

### ISSUE THREAD

**Issue by sishbi** [eclipse-vertx/vert.x#5162]
### Questions

`Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2196 ms, time limit is 2000 ms`

```
io.vertx.core.VertxException: Thread blocked
	at java.base/sun.nio.ch.EPollSelectorImpl.wakeup(EPollSelectorImpl.java:264)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.wakeup(SelectedSelectionKeySetSelector.java:73)
	at io.netty.channel.nio.NioEventLoop.wakeup(NioEventLoop.java:853)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:857)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:827)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:817)
	at io.vertx.core.impl.EventLoopExecutor.execute(EventLoopExecutor.java:35)
	at io.vertx.core.impl.ContextInternal.runOnContext(ContextInternal.java:59)
	at io.vertx.core.impl.DeploymentManager.doDeploy(DeploymentManager.java:205)
	at io.vertx.core.impl.DeploymentManager.doDeploy(DeploymentManager.java:160)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:65)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:836)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:790)
	at io.vertx.core.Vertx.deployVerticle(Vertx.java:507)
	at com.kodypay.cards.MainVerticle.deployVerticles(MainVerticle.kt:149)
	at com.kodypay.cards.MainVerticle.access$deployVerticles(MainVerticle.kt:55)
	at com.kodypay.cards.MainVerticle$deployVerticles$1.invokeSuspend(MainVerticle.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:231)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:187)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:159)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:504)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:493)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:364)
	at io.vertx.kotlin.coroutines.VertxCoroutineKt$coAwait$2$1.handle(VertxCoroutine.kt:144)
	at io.vertx.kotlin.coroutines.VertxCoroutineKt$coAwait$2$1.handle(VertxCoroutine.kt:143)
	at io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:259)
	at io.vertx.core.impl.future.Mapping.onSuccess(Mapping.java:40)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:60)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:298)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:288)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:57)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:259)
	at io.vertx.core.Promise.complete(Promise.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$null$4(DeploymentManager.java:224)
	at io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:231)
	at io.vertx.core.impl.future.FutureImpl.onComplete(FutureImpl.java:199)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:211)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:261)
	at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:59)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Version

4.5.4

### Context

This occurs during the server startup just after verticle deployment.

### Do you have a reproducer?

No

### Steps to reproduce

1. Start application
2. Wait

### Extra

OS: AWS Linux (Docker), host: x64
JVM: JDK 21, eclipse-temurin:21-jdk (Docker)

**Comment by sishbi** [comment]
There was an additional blocked thread report for the same container during startup:
`Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 2594 ms, time limit is 2000 ms`

```
io.vertx.core.VertxException: Thread blocked
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:222)
	at io.vertx.core.impl.future.FutureBase.map(FutureBase.java:121)
	at io.vertx.core.impl.future.FutureImpl.map(FutureImpl.java:28)
	at io.vertx.core.net.impl.TCPServerBase.bind(TCPServerBase.java:179)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:176)
	at io.vertx.core.http.HttpServer.listen(HttpServer.java:216)
	at com.kodypay.cards.http.RestVerticle.start(RestVerticle.kt:53)
	at com.kodypay.cards.http.RestVerticle$start$1.invokeSuspend(RestVerticle.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:231)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:187)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:159)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:504)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:493)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:364)
	at io.vertx.kotlin.coroutines.VertxCoroutineKt$coAwait$2$1.handle(VertxCoroutine.kt:144)
	at io.vertx.kotlin.coroutines.VertxCoroutineKt$coAwait$2$1.handle(VertxCoroutine.kt:143)
	at io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:60)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
